# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        ('ouvidoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OuvidoriaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('publico', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta da ouvidoria',
                'verbose_name_plural': 'Respostas da ouvidoria',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OuvidoriaTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.TextField(blank=True, default='')),
                ('ciencia', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tramitação de ouvidoria',
                'verbose_name_plural': 'Tramitações de ouvidoria',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='ouvidoriacadastro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Chamado de ouvidoria', 'verbose_name_plural': 'Chamados de ouvidoria'},
        ),
        migrations.RemoveConstraint(
            model_name='ouvidoriacadastro',
            name='uniq_ouvidoria_cadastro_municipio_codigo',
        ),
        migrations.RemoveIndex(
            model_name='ouvidoriacadastro',
            name='ouvidoria_o_codigo_f45185_idx',
        ),
        migrations.RemoveIndex(
            model_name='ouvidoriacadastro',
            name='ouvidoria_o_nome_4c5f18_idx',
        ),
        migrations.RenameField(
            model_name='ouvidoriacadastro',
            old_name='codigo',
            new_name='protocolo',
        ),
        migrations.RenameField(
            model_name='ouvidoriacadastro',
            old_name='nome',
            new_name='assunto',
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='prazo_resposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvidoria_chamados_respondidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='solicitante_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='solicitante_nome',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='solicitante_telefone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ouvidoriacadastro',
            name='tipo',
            field=models.CharField(choices=[('RECLAMACAO', 'Reclamação'), ('SUGESTAO', 'Sugestão'), ('ELOGIO', 'Elogio'), ('DENUNCIA', 'Denúncia'), ('ESIC', 'e-SIC')], default='RECLAMACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ouvidoriacadastro',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('ENCAMINHADO', 'Encaminhado'), ('RESPONDIDO', 'Respondido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=12),
        ),
        migrations.AddIndex(
            model_name='ouvidoriacadastro',
            index=models.Index(fields=['protocolo'], name='ouvidoria_o_protoco_41b82e_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvidoriacadastro',
            index=models.Index(fields=['assunto'], name='ouvidoria_o_assunto_5accdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='ouvidoriacadastro',
            constraint=models.UniqueConstraint(fields=('municipio', 'protocolo'), name='uniq_ouvidoria_protocolo_municipio'),
        ),
        migrations.AddField(
            model_name='ouvidoriaresposta',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ouvidoria.ouvidoriacadastro'),
        ),
        migrations.AddField(
            model_name='ouvidoriaresposta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvidoria_respostas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ouvidoriaresposta',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ouvidoria_respostas', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='ouvidoriatramitacao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='ouvidoria.ouvidoriacadastro'),
        ),
        migrations.AddField(
            model_name='ouvidoriatramitacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvidoria_tramitacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ouvidoriatramitacao',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ouvidoria_tramitacoes', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='ouvidoriatramitacao',
            name='setor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ouvidoria_tramitacoes_destino', to='org.setor'),
        ),
        migrations.AddField(
            model_name='ouvidoriatramitacao',
            name='setor_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ouvidoria_tramitacoes_origem', to='org.setor'),
        ),
        migrations.AddIndex(
            model_name='ouvidoriaresposta',
            index=models.Index(fields=['municipio', 'publico'], name='ouvidoria_o_municip_45a417_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvidoriaresposta',
            index=models.Index(fields=['chamado', 'criado_em'], name='ouvidoria_o_chamado_b4be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvidoriatramitacao',
            index=models.Index(fields=['municipio', 'criado_em'], name='ouvidoria_o_municip_b39677_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvidoriatramitacao',
            index=models.Index(fields=['chamado'], name='ouvidoria_o_chamado_e17c56_idx'),
        ),
    ]
