# Generated by Django 5.2.11 on 2026-02-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nee', '0002_acompanhamentonee_laudonee_recursonee_and_more'),
        ('nee', '0002_enterprise_upgrade'),
    ]

    operations = [
    ]
