# Generated by Django 5.2.11 on 2026-02-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0011_avaliacaonota_componentecurricular_notacurricular_and_more'),
        ('nee', '0003_merge_20260221_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentonee',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Acompanhamento NEE', 'verbose_name_plural': 'Acompanhamentos NEE'},
        ),
        migrations.AlterModelOptions(
            name='alunonecessidade',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Necessidade do Aluno', 'verbose_name_plural': 'Necessidades do Aluno'},
        ),
        migrations.AlterModelOptions(
            name='apoiomatricula',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Apoio da Matrícula', 'verbose_name_plural': 'Apoios da Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='laudonee',
            options={'ordering': ['-data_emissao', '-id'], 'verbose_name': 'Laudo NEE', 'verbose_name_plural': 'Laudos NEE'},
        ),
        migrations.AlterModelOptions(
            name='recursonee',
            options={'ordering': ['nome'], 'verbose_name': 'Recurso NEE', 'verbose_name_plural': 'Recursos NEE'},
        ),
        migrations.AlterModelOptions(
            name='tiponecessidade',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Necessidade', 'verbose_name_plural': 'Tipos de Necessidade'},
        ),        migrations.AlterUniqueTogether(
            name='alunonecessidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alunonecessidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alunonecessidade',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CID (opcional)'),
        ),
        migrations.AddField(
            model_name='apoiomatricula',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apoiomatricula',
            name='tipo',
            field=models.CharField(choices=[('AEE', 'AEE (Atendimento Educacional Especializado)'), ('CUIDADOR', 'Cuidador(a)'), ('INTERPRETE_LIBRAS', 'Intérprete de Libras'), ('PROFESSOR_APOIO', 'Professor de Apoio'), ('TRANSPORTE', 'Transporte Adaptado'), ('RECURSO', 'Recurso/Adaptação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='acompanhamentonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamentos_nee', to='educacao.aluno'),
        ),
        migrations.AlterField(
            model_name='alunonecessidade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necessidades', to='educacao.aluno'),
        ),
        migrations.AlterField(
            model_name='apoiomatricula',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apoiomatricula',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoios', to='educacao.matricula'),
        ),
        migrations.AlterField(
            model_name='laudonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos_nee', to='educacao.aluno'),
        ),
        migrations.AlterField(
            model_name='recursonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos_nee', to='educacao.aluno'),
        ),
        migrations.AddIndex(
            model_name='alunonecessidade',
            index=models.Index(fields=['cid'], name='nee_alunone_cid_5ce488_idx'),
        ),
    ]
