# Generated by Django 5.2.11 on 2026-02-23 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0011_avaliacaonota_componentecurricular_notacurricular_and_more'),
        ('nee', '0005_remove_alunonecessidade_nee_alunone_aluno_i_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoClinicoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_revisao', models.DateField(blank=True, null=True)),
                ('objetivo_geral', models.TextField(blank=True, default='')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='plano_clinico_nee', to='educacao.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_clinicos_nee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Clínico NEE',
                'verbose_name_plural': 'Planos Clínicos NEE',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPlanoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('COGNITIVO', 'Cognitivo'), ('SOCIAL', 'Social'), ('MOTOR', 'Motor'), ('COMUNICACAO', 'Comunicação'), ('SENSORIAL', 'Sensorial'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('descricao', models.TextField()),
                ('meta', models.CharField(blank=True, default='', max_length=180)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='nee.planocliniconee')),
            ],
            options={
                'verbose_name': 'Objetivo do Plano NEE',
                'verbose_name_plural': 'Objetivos do Plano NEE',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoPlanoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.TextField()),
                ('avaliacao', models.CharField(blank=True, default='', max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_plano_nee', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='nee.objetivoplanonee')),
            ],
            options={
                'verbose_name': 'Evolução do Plano NEE',
                'verbose_name_plural': 'Evoluções do Plano NEE',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['objetivo'], name='nee_evoluca_objetiv_7127c0_idx'), models.Index(fields=['data'], name='nee_evoluca_data_2ed0fc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='planocliniconee',
            index=models.Index(fields=['aluno'], name='nee_planocl_aluno_i_57e4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='planocliniconee',
            index=models.Index(fields=['data_inicio'], name='nee_planocl_data_in_1ec897_idx'),
        ),
        migrations.AddIndex(
            model_name='planocliniconee',
            index=models.Index(fields=['data_revisao'], name='nee_planocl_data_re_d4c4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivoplanonee',
            index=models.Index(fields=['plano'], name='nee_objetiv_plano_i_62f3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivoplanonee',
            index=models.Index(fields=['area'], name='nee_objetiv_area_d0f669_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivoplanonee',
            index=models.Index(fields=['status'], name='nee_objetiv_status_fd4b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivoplanonee',
            index=models.Index(fields=['prazo'], name='nee_objetiv_prazo_d41ea7_idx'),
        ),
    ]
