# Generated by Django 5.2.11 on 2026-03-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nee', '0007_saude_profissional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolucaoplanonee',
            name='profissional_saude',
        ),
    ]
