# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        ('patrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=12)),
                ('total_bens', models.PositiveIntegerField(default=0)),
                ('total_bens_ativos', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, default='')),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventário patrimonial',
                'verbose_name_plural': 'Inventários patrimoniais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('MANUTENCAO', 'Manutenção'), ('BAIXA', 'Baixa'), ('INVENTARIO', 'Inventário')], default='TRANSFERENCIA', max_length=20)),
                ('data_movimento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_movimento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimentação patrimonial',
                'verbose_name_plural': 'Movimentações patrimoniais',
                'ordering': ['-data_movimento', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='patrimoniocadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Bem patrimonial', 'verbose_name_plural': 'Bens patrimoniais'},
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='categoria',
            field=models.CharField(choices=[('IMOVEL', 'Imóvel'), ('MOVEL', 'Móvel'), ('INFORMATICA', 'Informática'), ('VEICULO', 'Veículo'), ('OUTRO', 'Outro')], default='MOVEL', max_length=20),
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='data_aquisicao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='estado_conservacao',
            field=models.CharField(blank=True, default='Bom', max_length=40),
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='situacao',
            field=models.CharField(choices=[('EM_USO', 'Em uso'), ('ESTOQUE', 'Em estoque'), ('MANUTENCAO', 'Em manutenção'), ('BAIXADO', 'Baixado')], default='EM_USO', max_length=20),
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='tombo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='valor_aquisicao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='patrimoniocadastro',
            index=models.Index(fields=['municipio', 'situacao'], name='patrimonio__municip_b465d5_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniocadastro',
            index=models.Index(fields=['tombo'], name='patrimonio__tombo_14a846_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimoniocadastro',
            constraint=models.UniqueConstraint(condition=models.Q(('tombo', ''), _negated=True), fields=('municipio', 'tombo'), name='uniq_patrimonio_tombo_municipio'),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_inventarios_concluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_inventarios_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_inventarios', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_inventarios', to='org.unidade'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='patrimonio.patrimoniocadastro'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_movimentacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_movimentacoes', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_movimentacoes_destino', to='org.unidade'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_movimentacoes_origem', to='org.unidade'),
        ),
        migrations.AddIndex(
            model_name='patrimonioinventario',
            index=models.Index(fields=['municipio', 'status'], name='patrimonio__municip_0de02f_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimonioinventario',
            constraint=models.UniqueConstraint(fields=('municipio', 'codigo'), name='uniq_patrimonio_inventario_municipio_codigo'),
        ),
        migrations.AddIndex(
            model_name='patrimoniomovimentacao',
            index=models.Index(fields=['municipio', 'tipo'], name='patrimonio__municip_c53734_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniomovimentacao',
            index=models.Index(fields=['bem', 'data_movimento'], name='patrimonio__bem_id_f4fa86_idx'),
        ),
    ]
