# Generated by Django 5.2.12 on 2026-03-21 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_localestrutural'),
        ('patrimonio', '0002_patrimonioinventario_patrimoniomovimentacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniocadastro',
            name='local_estrutural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_cadastros', to='org.localestrutural'),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='local_estrutural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_inventarios', to='org.localestrutural'),
        ),
        migrations.AddField(
            model_name='patrimonioinventario',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_inventarios', to='org.secretaria'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='local_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_movimentacoes_destino', to='org.localestrutural'),
        ),
        migrations.AddField(
            model_name='patrimoniomovimentacao',
            name='local_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_movimentacoes_origem', to='org.localestrutural'),
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tombamento', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=220)),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origem_aquisicao', models.CharField(blank=True, default='', max_length=120)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=180)),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível')], default='BOM', max_length=20)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção'), ('BAIXADO', 'Baixado'), ('EXTRAVIADO', 'Extraviado'), ('EMPRESTADO', 'Emprestado')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='patrimonio/bens/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local_estrutural', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens_patrimoniais', to='org.localestrutural')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens_patrimoniais', to='org.municipio')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimoniais_responsavel', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens_patrimoniais', to='org.secretaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens_patrimoniais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Bem patrimonial (novo)',
                'verbose_name_plural': 'Bens patrimoniais (novo)',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='InventarioPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_patrimoniais', to='org.municipio')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_patrimoniais_responsavel', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_patrimoniais', to='org.secretaria')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_patrimoniais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Inventário patrimonial (novo)',
                'verbose_name_plural': 'Inventários patrimoniais (novo)',
                'ordering': ['-data_abertura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao_encontrada', models.CharField(blank=True, default='', max_length=220)),
                ('status_conferencia', models.CharField(choices=[('LOCALIZADO', 'Localizado'), ('NAO_LOCALIZADO', 'Não localizado'), ('DIVERGENTE', 'Divergente'), ('DANIFICADO', 'Danificado')], default='LOCALIZADO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_itens', to='patrimonio.bempatrimonial')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='patrimonio.inventariopatrimonial')),
            ],
            options={
                'verbose_name': 'Item de inventário patrimonial',
                'verbose_name_plural': 'Itens de inventário patrimonial',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('TRANSFERENCIA_INTERNA', 'Transferência interna'), ('TRANSFERENCIA_UNIDADE', 'Transferência entre unidades'), ('TRANSFERENCIA_SECRETARIA', 'Transferência entre secretarias'), ('MANUTENCAO', 'Manutenção'), ('RETORNO_MANUTENCAO', 'Retorno de manutenção'), ('BAIXA', 'Baixa'), ('EMPRESTIMO', 'Empréstimo'), ('DEVOLUCAO', 'Devolução'), ('INVENTARIO_AJUSTE', 'Ajuste de inventário')], max_length=30)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, default='', max_length=220)),
                ('documento_referencia', models.CharField(blank=True, default='', max_length=80)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimoniais_autorizador', to=settings.AUTH_USER_MODEL)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='patrimonio.bempatrimonial')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_destino', to='org.localestrutural')),
                ('local_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_origem', to='org.localestrutural')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimoniais_responsavel', to=settings.AUTH_USER_MODEL)),
                ('secretaria_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_destino', to='org.secretaria')),
                ('secretaria_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_origem', to='org.secretaria')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_destino', to='org.unidade')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_patrimoniais_origem', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Movimentação patrimonial (novo)',
                'verbose_name_plural': 'Movimentações patrimoniais (novo)',
                'ordering': ['-data_movimentacao', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['municipio', 'secretaria', 'unidade'], name='patrimonio__municip_d5d733_idx'),
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['situacao', 'ativo'], name='patrimonio__situaca_587898_idx'),
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['categoria'], name='patrimonio__categor_2c5af1_idx'),
        ),
        migrations.AddConstraint(
            model_name='bempatrimonial',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero_tombamento'), name='uniq_bem_patrimonial_tombamento_municipio'),
        ),
        migrations.AddIndex(
            model_name='inventariopatrimonial',
            index=models.Index(fields=['municipio', 'status'], name='patrimonio__municip_77fd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariopatrimonial',
            index=models.Index(fields=['secretaria', 'unidade'], name='patrimonio__secreta_850053_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioitem',
            index=models.Index(fields=['status_conferencia'], name='patrimonio__status__29fc20_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventarioitem',
            constraint=models.UniqueConstraint(fields=('inventario', 'bem'), name='uniq_inventario_item_bem'),
        ),
        migrations.AddIndex(
            model_name='movimentacaopatrimonial',
            index=models.Index(fields=['tipo_movimentacao', 'data_movimentacao'], name='patrimonio__tipo_mo_3936da_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaopatrimonial',
            index=models.Index(fields=['bem', 'data_movimentacao'], name='patrimonio__bem_id_db69dc_idx'),
        ),
    ]
