# Generated by Django 5.2.11 on 2026-02-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_foto'),
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='org.secretaria'),
        ),
    ]
