# Generated by Django 5.2.11 on 2026-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
