# Generated by Django 5.2.11 on 2026-02-25 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_cpf_enc_profile_cpf_hash_profile_cpf_last4'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='org.setor'),
        ),
        migrations.CreateModel(
            name='UserManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('ACTIVATE', 'Ativação'), ('DEACTIVATE', 'Desativação'), ('BLOCK', 'Bloqueio'), ('UNBLOCK', 'Desbloqueio'), ('RESET_PASSWORD', 'Reset de senha'), ('RESET_CODE', 'Reset de código de acesso')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de usuário',
                'verbose_name_plural': 'Auditoria de usuários',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target', 'created_at'], name='accounts_us_target__3c6b39_idx'), models.Index(fields=['action', 'created_at'], name='accounts_us_action_be355d_idx')],
            },
        ),
    ]
