# Generated by Django 5.2.11 on 2026-03-01 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_bloqueado_profile_setor_usermanagementaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_expires_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Sistema)'), ('MUNICIPAL', 'Gestor Municipal'), ('SECRETARIA', 'Gestor de Secretaria'), ('UNIDADE', 'Gestor de Unidade'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('NEE', 'Técnico NEE'), ('LEITURA', 'Somente leitura'), ('AUDITORIA', 'Controladoria / Auditoria'), ('RH_GESTOR', 'RH / Gestão de Pessoas'), ('PROTOCOLO', 'Protocolo / Atendimento Geral'), ('CAD_GESTOR', 'Gestor de Cadastros'), ('CAD_OPER', 'Operador de Cadastros'), ('SAU_SECRETARIO', 'Secretário de Saúde'), ('SAU_DIRETOR', 'Diretor de Unidade de Saúde'), ('SAU_COORD', 'Coordenador de Saúde'), ('SAU_MEDICO', 'Médico'), ('SAU_ENFERMEIRO', 'Enfermeiro'), ('SAU_TEC_ENF', 'Técnico de Enfermagem'), ('SAU_ACS', 'ACS'), ('SAU_RECEPCAO', 'Recepção de Saúde'), ('SAU_REGULACAO', 'Regulação de Saúde'), ('SAU_FARMACIA', 'Farmácia'), ('EDU_SECRETARIO', 'Secretário de Educação'), ('EDU_DIRETOR', 'Diretor Escolar'), ('EDU_COORD', 'Coordenador Pedagógico'), ('EDU_PROF', 'Professor (Educação)'), ('EDU_SECRETARIA', 'Secretaria Escolar'), ('EDU_TRANSPORTE', 'Transporte Escolar'), ('NEE_COORD_MUN', 'Coordenador Municipal NEE'), ('NEE_COORD_ESC', 'Coordenador NEE da Escola'), ('NEE_MEDIADOR', 'Mediador / Apoio NEE'), ('NEE_TECNICO', 'Equipe Técnica NEE'), ('DADOS_GESTOR', 'Gestor de Dados / BI'), ('DADOS_ANALISTA', 'Analista Setorial'), ('INT_TI', 'Admin TI (Integrações)'), ('INT_GESTAO', 'Admin Gestão (Integrações)'), ('INT_LEITOR', 'Leitor (Integrações)'), ('PORTAL_ADMIN', 'Admin Portal'), ('PORTAL_EDITOR', 'Editor de Conteúdo'), ('PORTAL_APROV', 'Aprovador de Conteúdo'), ('PORTAL_DESIGN', 'Designer / Tema'), ('CIDADAO', 'Cidadão (Portal)')], default='LEITURA', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de senha',
                'verbose_name_plural': 'Histórico de senhas',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_pa_user_id_a6f7e8_idx')],
            },
        ),
    ]
