# Generated by Django 5.2.11 on 2026-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_mfa_enabled_profile_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('kassya', 'Kassya'), ('inclusao', 'Inclusão'), ('institucional', 'Institucional')], default='', max_length=30),
        ),
    ]
