# Generated by Django 5.2.12 on 2026-03-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_ui_theme'),
        ('org', '0016_localestrutural'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local_estrutural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='org.localestrutural'),
        ),
    ]
