# Generated by Django 5.2.12 on 2026-03-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_local_estrutural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPreviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('START', 'Início'), ('STOP', 'Encerramento')], max_length=20)),
                ('preview_type', models.CharField(choices=[('PROFILE', 'Visualizar como perfil'), ('USER', 'Visualizar como usuário'), ('CONTEXT', 'Visualizar função em contexto')], max_length=20)),
                ('target_role', models.CharField(blank=True, default='', max_length=40)),
                ('scope_type', models.CharField(blank=True, default='', max_length=40)),
                ('scope_payload', models.JSONField(blank=True, default=dict)),
                ('read_only', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_preview_actor_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_preview_target_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de visualização administrativa',
                'verbose_name_plural': 'Auditoria de visualizações administrativas',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='accounts_ac_actor_i_242f2e_idx'), models.Index(fields=['target_user', 'created_at'], name='accounts_ac_target__a8f9a5_idx'), models.Index(fields=['preview_type', 'action'], name='accounts_ac_preview_73f177_idx')],
            },
        ),
    ]
