# Generated by Django 5.2.11 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_accesspreviewlog"),
        ("saude", "0009_cidsaude_pacientesaude_internacaosaude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfis",
                to="saude.pacientesaude",
            ),
        ),
    ]
