# Generated by Django 5.2.11 on 2026-02-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_turma_professores'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aluno',
            name='educacao_al_nome_1d1da1_idx',
        ),
        migrations.RemoveIndex(
            model_name='aluno',
            name='educacao_al_cpf_34125d_idx',
        ),
        migrations.RemoveIndex(
            model_name='aluno',
            name='educacao_al_nis_fae522_idx',
        ),
        migrations.RemoveIndex(
            model_name='aluno',
            name='educacao_al_ativo_142762_idx',
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/', verbose_name='Foto'),
        ),
    ]
