# Generated by Django 5.2.11 on 2026-02-19 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0009_periodoletivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('ordem', models.PositiveSmallIntegerField(help_text='Ordem da aula no dia (1ª, 2ª, 3ª...)')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('componente', models.CharField(help_text='Disciplina / Componente curricular', max_length=120)),
                ('local', models.CharField(blank=True, default='', help_text='Sala ou local da aula', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_aula', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='educacao.turma')),
            ],
            options={
                'ordering': ['dia_semana', 'ordem', 'inicio'],
                'unique_together': {('turma', 'dia_semana', 'ordem')},
            },
        ),
    ]
