# Generated by Django 5.2.11 on 2026-02-19 18:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0010_horarioaula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('data', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso da avaliação (ex.: 1, 2, 0.5).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Nota máxima (ex.: 10, 100).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Avaliação (Notas)',
                'verbose_name_plural': 'Avaliações (Notas)',
                'ordering': ['-criado_em', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(blank=True, default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente curricular',
                'verbose_name_plural': 'Componentes curriculares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.CharField(blank=True, default='', max_length=240)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['matricula_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data', '-id']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['aluno_id']},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_maxima',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='educacao.periodoletivo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['data'], name='educacao_av_data_316e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['ativo'], name='educacao_av_ativo_702ec6_idx'),
        ),
        migrations.AddField(
            model_name='avaliacaonota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_notas', to='educacao.periodoletivo'),
        ),
        migrations.AddField(
            model_name='avaliacaonota',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_notas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaonota',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_notas', to='educacao.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='componentecurricular',
            unique_together={('nome', 'sigla')},
        ),
        migrations.AddField(
            model_name='avaliacaonota',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_notas', to='educacao.componentecurricular'),
        ),
        migrations.AddField(
            model_name='notacurricular',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_curriculares', to='educacao.avaliacaonota'),
        ),
        migrations.AddField(
            model_name='notacurricular',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_curriculares', to='educacao.matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='notacurricular',
            unique_together={('avaliacao', 'matricula')},
        ),
    ]
