# Generated by Django 5.2.11 on 2026-02-25 13:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('STARTER', 'Starter'), ('MUNICIPAL', 'Municipal'), ('GESTAO_TOTAL', 'Gestão Total'), ('CONSORCIO', 'Consórcio/Estado')], max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('preco_base_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('limite_secretarias', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_usuarios', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_alunos', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_atendimentos_ano', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_bi_light', models.BooleanField(default=False)),
                ('feature_bi_municipal', models.BooleanField(default=False)),
                ('feature_bi_avancado', models.BooleanField(default=False)),
                ('feature_importacao_assistida', models.BooleanField(default=False)),
                ('feature_sla_prioritario', models.BooleanField(default=False)),
                ('feature_migracao_assistida', models.BooleanField(default=False)),
                ('feature_treinamento_continuo', models.BooleanField(default=False)),
                ('valor_secretaria_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_usuario_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_aluno_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_atendimento_extra', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano municipal',
                'verbose_name_plural': 'Planos municipais',
                'ordering': ['preco_base_mensal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('contrato_meses', models.PositiveIntegerField(default=12)),
                ('preco_base_congelado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('indice_reajuste', models.CharField(choices=[('INPC', 'INPC'), ('IPCA', 'IPCA')], default='INPC', max_length=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='org.municipio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='billing.planomunicipal')),
            ],
            options={
                'verbose_name': 'Assinatura municipal',
                'verbose_name_plural': 'Assinaturas municipais',
                'ordering': ['-inicio_vigencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SECRETARIAS', '+ secretarias'), ('USUARIOS', '+ usuários'), ('ALUNOS', '+ alunos'), ('ATENDIMENTOS', '+ atendimentos'), ('ADDON', 'Addon'), ('TROCA_PLANO', 'Troca de plano')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_mensal_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_one_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SOLICITADO', 'Solicitado'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='SOLICITADO', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_upgrade', to='billing.addoncatalogo')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_aprovados', to=settings.AUTH_USER_MODEL)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_upgrade', to='billing.assinaturamunicipio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_upgrade', to='org.municipio')),
                ('plano_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_migracao', to='billing.planomunicipal')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de upgrade',
                'verbose_name_plural': 'Solicitações de upgrade',
                'ordering': ['-solicitado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretarias_ativas', models.PositiveIntegerField(default=0)),
                ('usuarios_ativos', models.PositiveIntegerField(default=0)),
                ('alunos_ativos', models.PositiveIntegerField(default=0)),
                ('atendimentos_ano', models.PositiveIntegerField(default=0)),
                ('ano_referencia', models.PositiveIntegerField(default=2026)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso_atual', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Uso municipal',
                'verbose_name_plural': 'Usos municipais',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario_congelado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='billing.addoncatalogo')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='billing.assinaturamunicipio')),
            ],
            options={
                'verbose_name': 'Addon da assinatura',
                'verbose_name_plural': 'Addons da assinatura',
                'ordering': ['addon__nome'],
                'constraints': [models.UniqueConstraint(fields=('assinatura', 'addon'), name='uniq_assinatura_addon')],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaQuotaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SECRETARIAS', 'Secretarias'), ('USUARIOS', 'Usuários'), ('ALUNOS', 'Alunos'), ('ATENDIMENTOS', 'Atendimentos')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('origem', models.CharField(choices=[('UPGRADE', 'Upgrade'), ('BONUS', 'Bônus'), ('MANUAL', 'Manual')], default='UPGRADE', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=180)),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas_extras', to='billing.assinaturamunicipio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas_extras_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota extra',
                'verbose_name_plural': 'Quotas extras',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['assinatura', 'tipo', 'ativo'], name='billing_ass_assinat_4a9af7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaturaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Competência no 1º dia do mês')),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_adicionais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='billing.assinaturamunicipio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-competencia', '-id'],
                'indexes': [models.Index(fields=['municipio', 'competencia'], name='billing_fat_municip_0f6d90_idx'), models.Index(fields=['status'], name='billing_fat_status_299582_idx')],
                'constraints': [models.UniqueConstraint(fields=('assinatura', 'competencia'), name='uniq_fatura_assinatura_competencia')],
            },
        ),
        migrations.AddIndex(
            model_name='assinaturamunicipio',
            index=models.Index(fields=['municipio', 'status'], name='billing_ass_municip_8ec3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturamunicipio',
            index=models.Index(fields=['inicio_vigencia'], name='billing_ass_inicio__e9dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoupgrade',
            index=models.Index(fields=['municipio', 'status'], name='billing_sol_municip_49b960_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoupgrade',
            index=models.Index(fields=['tipo', 'status'], name='billing_sol_tipo_ee45e2_idx'),
        ),
    ]
