# Generated by Django 5.2.12 on 2026-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_reseed_planos_apps_20260303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomunicipal',
            name='codigo',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MUNICIPAL', 'Municipal'), ('GESTAO_TOTAL', 'Gestão Total'), ('CONSORCIO', 'Governo Completo')], max_length=30, unique=True),
        ),
    ]
