# Generated by Django 5.2.11 on 2026-02-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('uf', models.CharField(default='MA', max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('sigla', models.CharField(blank=True, default='', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretarias', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('SECRETARIA', 'Secretaria'), ('OUTRO', 'Outro')], default='ESCOLA', max_length=20)),
                ('codigo_inep', models.CharField(blank=True, default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='org.secretaria')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='secretaria',
            constraint=models.UniqueConstraint(fields=('municipio', 'nome'), name='uniq_secretaria_por_municipio'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(fields=('secretaria', 'nome'), name='uniq_unidade_por_secretaria'),
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='uniq_setor_por_unidade'),
        ),
    ]
