# Generated by Django 5.2.11 on 2026-02-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='cnpj_prefeitura',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ da Prefeitura'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='email_prefeitura',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='endereco_prefeitura',
            field=models.TextField(blank=True, default='', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='nome_fantasia_prefeitura',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='nome_prefeito',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Prefeito(a)'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='razao_social_prefeitura',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='site_prefeitura',
            field=models.URLField(blank=True, default='', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='telefone_prefeitura',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefone'),
        ),
    ]
