# Generated by Django 5.2.11 on 2026-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_municipio_cnpj_prefeitura_municipio_email_prefeitura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.TextField(blank=True, default='', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_inep',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código INEP'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('ESCOLA', 'Escola'), ('CRECHE', 'Creche'), ('SECRETARIA', 'Secretaria/Órgão'), ('OUTRO', 'Outro')], default='ESCOLA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nome'], name='org_municip_nome_60e643_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['uf'], name='org_municip_uf_83746d_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['ativo'], name='org_municip_ativo_b4b551_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['nome'], name='org_secreta_nome_07247e_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['ativo'], name='org_secreta_ativo_864fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='setor',
            index=models.Index(fields=['nome'], name='org_setor_nome_09d31a_idx'),
        ),
        migrations.AddIndex(
            model_name='setor',
            index=models.Index(fields=['ativo'], name='org_setor_ativo_17e485_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['nome'], name='org_unidade_nome_e311f8_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['tipo'], name='org_unidade_tipo_26d3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo_inep'], name='org_unidade_codigo__bbf3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['ativo'], name='org_unidade_ativo_950a53_idx'),
        ),
    ]
