# Generated by Django 5.2.11 on 2026-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codigo_acesso',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
