# Generated by Django 5.2.11 on 2026-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_codigo_acesso_profile_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Sistema)'), ('MUNICIPAL', 'Gestor Municipal'), ('SECRETARIA', 'Gestor de Secretaria'), ('UNIDADE', 'Gestor de Unidade'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('NEE', 'Técnico NEE'), ('LEITURA', 'Somente leitura')], default='LEITURA', max_length=20),
        ),
    ]
