# Generated by Django 5.2.11 on 2026-02-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
        ('educacao', '0003_turma_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='educacao.aluno'),
        ),
    ]
