# Generated by Django 5.2.11 on 2026-02-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('cargo', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('TECNICO', 'Técnico'), ('AGENTE', 'Agente de Saúde'), ('ADMIN', 'Administrativo'), ('OUTROS', 'Outros')], max_length=20)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Profissional de Saúde',
                'verbose_name_plural': 'Profissionais de Saúde',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='saude_profi_nome_622849_idx'), models.Index(fields=['cargo'], name='saude_profi_cargo_c3d2bb_idx'), models.Index(fields=['ativo'], name='saude_profi_ativo_a7883a_idx')],
            },
        ),
    ]
