# Generated by Django 5.2.11 on 2026-02-18 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalsaude',
            name='unidade',
            field=models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='profissionais_saude', to='org.unidade'),
        ),
        migrations.CreateModel(
            name='AtendimentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('PROCEDIMENTO', 'Procedimento'), ('VACINA', 'Vacina'), ('VISITA', 'Visita domiciliar'), ('TRIAGEM', 'Triagem'), ('OUTROS', 'Outros')], default='CONSULTA', max_length=20)),
                ('paciente_nome', models.CharField(max_length=180)),
                ('paciente_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='saude.profissionalsaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['data'], name='saude_atend_data_824130_idx'), models.Index(fields=['tipo'], name='saude_atend_tipo_ddb9a8_idx'), models.Index(fields=['paciente_nome'], name='saude_atend_pacient_d560b1_idx')],
            },
        ),
    ]
