# Generated by Django 5.2.11 on 2026-02-25 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentoemitido'),
        ('educacao', '0012_aluno_cpf_enc_aluno_cpf_hash_aluno_cpf_last4'),
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        ('saude', '0004_atendimentosaude_paciente_cpf_enc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='carga_horaria_semanal',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='cbo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='conselho_numero',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='EspecialidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('cbo', models.CharField(blank=True, default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='saude_espec_nome_0ef216_idx'), models.Index(fields=['ativo'], name='saude_espec_ativo_679d68_idx')],
            },
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='saude.especialidadesaude'),
        ),
        migrations.CreateModel(
            name='SalaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salas_saude', to='org.setor')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='salas_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Sala de Atendimento',
                'verbose_name_plural': 'Salas de Atendimento',
                'ordering': ['unidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=180)),
                ('paciente_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PRIMEIRA_CONSULTA', 'Primeira consulta'), ('RETORNO', 'Retorno'), ('PROCEDIMENTO', 'Procedimento'), ('ENCAIXE', 'Encaixe')], default='PRIMEIRA_CONSULTA', max_length=20)),
                ('status', models.CharField(choices=[('MARCADO', 'Marcado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('FALTA', 'Falta'), ('CANCELADO', 'Cancelado')], db_index=True, default='MARCADO', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_saude', to='educacao.aluno')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='saude.profissionalsaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_saude', to='org.unidade')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='saude.especialidadesaude')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='saude.salasaude')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcessoProntuarioSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(default='VISUALIZACAO', max_length=60)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_prontuario_saude', to='educacao.aluno')),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_acessos', to='saude.atendimentosaude')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos_prontuario_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Acesso ao Prontuário',
                'verbose_name_plural': 'Auditoria de Acesso ao Prontuário',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['criado_em'], name='saude_audit_criado__6f0ac3_idx'), models.Index(fields=['acao'], name='saude_audit_acao_203f05_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinicoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATESTADO', 'Atestado'), ('DECLARACAO', 'Declaração'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('RELATORIO', 'Relatório'), ('LAUDO', 'Laudo'), ('RECEITA', 'Receita')], max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_clinicos', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_clinicos_saude', to=settings.AUTH_USER_MODEL)),
                ('documento_emitido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_clinicos_saude', to='core.documentoemitido')),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='saude_docum_tipo_cbd6a4_idx'), models.Index(fields=['criado_em'], name='saude_docum_criado__8cd323_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salasaude',
            index=models.Index(fields=['ativo'], name='saude_salas_ativo_d57b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='salasaude',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='uniq_sala_saude_unidade_nome'),
        ),
        migrations.AddIndex(
            model_name='agendamentosaude',
            index=models.Index(fields=['inicio'], name='saude_agend_inicio_c7ad02_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamentosaude',
            index=models.Index(fields=['status'], name='saude_agend_status_73ec4e_idx'),
        ),
    ]
