# Generated by Django 5.2.11 on 2026-02-25 01:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0012_aluno_cpf_enc_aluno_cpf_hash_aluno_cpf_last4'),
        ('saude', '0005_profissionalsaude_carga_horaria_semanal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoAtendimentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('arquivo', models.FileField(upload_to='saude/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_clinicos', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_atendimento_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Atendimento',
                'verbose_name_plural': 'Anexos de Atendimento',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamePedidoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=180)),
                ('prioridade', models.CharField(choices=[('ROTINA', 'Rotina'), ('URGENTE', 'Urgente')], default='ROTINA', max_length=20)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('hipotese_diagnostica', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COLETADO', 'Coletado'), ('RESULTADO', 'Com resultado')], default='SOLICITADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_pedidos', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_pedidos_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Exame',
                'verbose_name_plural': 'Pedidos de Exame',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExameResultadoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resultado', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='saude/exames/')),
                ('data_resultado', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_exames_saude', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='saude.examepedidosaude')),
            ],
            options={
                'verbose_name': 'Resultado de Exame',
                'verbose_name_plural': 'Resultados de Exame',
                'ordering': ['-data_resultado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ALTERADA', 'Alterada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoItemSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=180)),
                ('dose', models.CharField(blank=True, default='', max_length=120)),
                ('via', models.CharField(blank=True, default='', max_length=80)),
                ('frequencia', models.CharField(blank=True, default='', max_length=120)),
                ('duracao', models.CharField(blank=True, default='', max_length=120)),
                ('orientacoes', models.TextField(blank=True, default='')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='saude.prescricaosaude')),
            ],
            options={
                'verbose_name': 'Item da Prescrição',
                'verbose_name_plural': 'Itens da Prescrição',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemaAtivoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('cid', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONTROLADO', 'Controlado'), ('RESOLVIDO', 'Resolvido')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problemas_ativos_saude', to='educacao.aluno')),
            ],
            options={
                'verbose_name': 'Problema Ativo',
                'verbose_name_plural': 'Problemas Ativos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TriagemSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_sistolica', models.PositiveIntegerField(blank=True, null=True)),
                ('pa_diastolica', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacao_o2', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classificacao_risco', models.CharField(blank=True, default='', max_length=40)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triagem', to='saude.atendimentosaude')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-atendimento__data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlergiaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(max_length=180)),
                ('reacao', models.CharField(blank=True, default='', max_length=180)),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave')], default='LEVE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alergias_saude', to='educacao.aluno')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'ordering': ['agente'],
                'indexes': [models.Index(fields=['gravidade'], name='saude_alerg_gravida_b54306_idx'), models.Index(fields=['ativo'], name='saude_alerg_ativo_1c0f9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoClinicaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMAGEM', 'Enfermagem'), ('MULTIPROFISSIONAL', 'Multiprofissional')], default='MULTIPROFISSIONAL', max_length=20)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to='saude.atendimentosaude')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evolução Clínica',
                'verbose_name_plural': 'Evoluções Clínicas',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['criado_em'], name='saude_evolu_criado__0cb182_idx'), models.Index(fields=['tipo'], name='saude_evolu_tipo_9bbc3c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examepedidosaude',
            index=models.Index(fields=['status'], name='saude_exame_status_b7a716_idx'),
        ),
        migrations.AddIndex(
            model_name='examepedidosaude',
            index=models.Index(fields=['prioridade'], name='saude_exame_priorid_e9e249_idx'),
        ),
        migrations.AddIndex(
            model_name='prescricaosaude',
            index=models.Index(fields=['versao'], name='saude_presc_versao_698873_idx'),
        ),
        migrations.AddIndex(
            model_name='prescricaosaude',
            index=models.Index(fields=['status'], name='saude_presc_status_e23601_idx'),
        ),
        migrations.AddIndex(
            model_name='problemaativosaude',
            index=models.Index(fields=['status'], name='saude_probl_status_4cdd26_idx'),
        ),
        migrations.AddIndex(
            model_name='problemaativosaude',
            index=models.Index(fields=['cid'], name='saude_probl_cid_007bfc_idx'),
        ),
    ]
