# Generated by Django 5.2.11 on 2026-02-25 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0012_aluno_cpf_enc_aluno_cpf_hash_aluno_cpf_last4'),
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        ('saude', '0006_anexoatendimentosaude_examepedidosaude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAlteracaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(max_length=64)),
                ('campo', models.CharField(max_length=80)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_novo', models.TextField(blank=True, default='')),
                ('justificativa', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Alteração Clínica',
                'verbose_name_plural': 'Auditoria de Alterações Clínicas',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['entidade'], name='saude_audit_entidad_2e7357_idx'), models.Index(fields=['criado_em'], name='saude_audit_criado__748880_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgendaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('motivo', models.CharField(max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_agenda_saude', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_agenda', to='saude.profissionalsaude')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_agenda', to='saude.salasaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_agenda_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['-inicio', '-id'],
                'indexes': [models.Index(fields=['inicio'], name='saude_bloqu_inicio_bcaba0_idx'), models.Index(fields=['fim'], name='saude_bloqu_fim_e4c622_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilaEsperaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=180)),
                ('paciente_contato', models.CharField(blank=True, default='', max_length=80)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADO', 'Chamado'), ('CONVERTIDO', 'Convertido em agendamento'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fila_espera_saude', to='educacao.aluno')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fila_espera', to='saude.especialidadesaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='fila_espera_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Fila de Espera',
                'verbose_name_plural': 'Fila de Espera',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['status'], name='saude_filae_status_ad3642_idx'), models.Index(fields=['prioridade'], name='saude_filae_priorid_f7c37e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeAgendaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('intervalo_minutos', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='saude.especialidadesaude')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='saude.profissionalsaude')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='saude.salasaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='grades_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Grade de Agenda',
                'verbose_name_plural': 'Grades de Agenda',
                'ordering': ['profissional__nome', 'dia_semana', 'inicio'],
                'indexes': [models.Index(fields=['dia_semana'], name='saude_grade_dia_sem_795e47_idx'), models.Index(fields=['ativo'], name='saude_grade_ativo_dd1975_idx')],
            },
        ),
    ]
