# Generated by Django 5.2.11 on 2026-02-25 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        ('saude', '0007_auditoriaalteracaosaude_bloqueioagendasaude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaminhamentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('ROTINA', 'Rotina'), ('PRIORITARIO', 'Prioritário'), ('URGENTE', 'Urgente')], default='ROTINA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('INDEFERIDO', 'Indeferido')], default='ABERTO', max_length=20)),
                ('justificativa', models.TextField()),
                ('observacoes_regulacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_saude', to=settings.AUTH_USER_MODEL)),
                ('especialidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='saude.especialidadesaude')),
                ('unidade_destino', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'SAUDE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_destino', to='org.unidade')),
                ('unidade_origem', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_origem', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['status'], name='saude_encam_status_e99437_idx'), models.Index(fields=['prioridade'], name='saude_encam_priorid_9e13c2_idx'), models.Index(fields=['criado_em'], name='saude_encam_criado__c86cda_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMBULATORIAL', 'Ambulatorial'), ('CURATIVO', 'Curativo'), ('ADMINISTRACAO_MED', 'Administração de medicamento'), ('COLETA', 'Coleta'), ('OUTROS', 'Outros')], default='AMBULATORIAL', max_length=30)),
                ('descricao', models.CharField(max_length=180)),
                ('materiais', models.TextField(blank=True, default='')),
                ('intercorrencias', models.TextField(blank=True, default='')),
                ('realizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_saude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-realizado_em', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='saude_proce_tipo_0f652e_idx'), models.Index(fields=['realizado_em'], name='saude_proce_realiza_3053ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacinacaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(max_length=180)),
                ('dose', models.CharField(blank=True, default='', max_length=60)),
                ('lote', models.CharField(blank=True, default='', max_length=80)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('data_aplicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('reacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes_aplicadas', to='saude.profissionalsaude')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes_saude', to=settings.AUTH_USER_MODEL)),
                ('unidade_aplicadora', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinação',
                'ordering': ['-data_aplicacao', '-id'],
                'indexes': [models.Index(fields=['data_aplicacao'], name='saude_vacin_data_ap_e566ab_idx'), models.Index(fields=['vacina'], name='saude_vacin_vacina_fa9005_idx')],
            },
        ),
    ]
