# Generated by Django 5.2.11 on 2026-02-25 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0012_aluno_cpf_enc_aluno_cpf_hash_aluno_cpf_last4'),
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        ('saude', '0008_encaminhamentosaude_procedimentosaude_vacinacaosaude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CidSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CID',
                'verbose_name_plural': 'CIDs',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='saude_cidsa_codigo_8bfa09_idx'), models.Index(fields=['ativo'], name='saude_cidsa_ativo_32b87b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PacienteSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Não informado')], default='N', max_length=1)),
                ('cartao_sus', models.CharField(blank=True, default='', max_length=32)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('cpf_enc', models.TextField(blank=True, default='')),
                ('cpf_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('cpf_last4', models.CharField(blank=True, default='', max_length=4)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('endereco', models.TextField(blank=True, default='')),
                ('responsavel_nome', models.CharField(blank=True, default='', max_length=180)),
                ('responsavel_telefone', models.CharField(blank=True, default='', max_length=40)),
                ('vulnerabilidades', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_saude', to='educacao.aluno')),
                ('unidade_referencia', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_saude', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InternacaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INTERNACAO', 'Internação'), ('OBSERVACAO', 'Observação')], default='OBSERVACAO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ALTA', 'Alta'), ('TRANSFERIDA', 'Transferida'), ('OBITO', 'Óbito')], default='ATIVA', max_length=20)),
                ('data_admissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('leito', models.CharField(blank=True, default='', max_length=80)),
                ('motivo', models.TextField()),
                ('resumo_alta', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internacoes_saude', to=settings.AUTH_USER_MODEL)),
                ('profissional_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internacoes_responsavel', to='saude.profissionalsaude')),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='internacoes_saude', to='org.unidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internacoes', to='saude.pacientesaude')),
            ],
            options={
                'verbose_name': 'Internação/Observação',
                'verbose_name_plural': 'Internações/Observações',
                'ordering': ['-data_admissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispensacaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(default='un', max_length=40)),
                ('lote', models.CharField(blank=True, default='', max_length=80)),
                ('validade', models.DateField(blank=True, null=True)),
                ('orientacoes', models.TextField(blank=True, default='')),
                ('dispensado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='saude.atendimentosaude')),
                ('dispensado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes_saude', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes_saude', to='org.unidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='saude.pacientesaude')),
            ],
            options={
                'verbose_name': 'Dispensação',
                'verbose_name_plural': 'Dispensações',
                'ordering': ['-dispensado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckInSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=180)),
                ('motivo_visita', models.TextField(blank=True, default='')),
                ('queixa_principal', models.TextField(blank=True, default='')),
                ('classificacao_risco', models.CharField(blank=True, default='', max_length=40)),
                ('pa_sistolica', models.PositiveIntegerField(blank=True, null=True)),
                ('pa_diastolica', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacao_o2', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_CLASSIFICACAO', 'Aguardando classificação'), ('AGUARDANDO_ATENDIMENTO', 'Aguardando atendimento'), ('EM_ATENDIMENTO', 'Em atendimento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_CLASSIFICACAO', max_length=30)),
                ('chegada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='saude.agendamentosaude')),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='saude.atendimentosaude')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins_saude', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(limit_choices_to={'tipo': 'SAUDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='checkins_saude', to='org.unidade')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='saude.pacientesaude')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-chegada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('CONVENIO', 'Convênio'), ('PROGRAMA', 'Programa')], default='PROGRAMA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programa/Convênio',
                'verbose_name_plural': 'Programas/Convênios',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tipo'], name='saude_progr_tipo_53ca53_idx'), models.Index(fields=['ativo'], name='saude_progr_ativo_85e431_idx')],
                'constraints': [models.UniqueConstraint(fields=('nome', 'tipo'), name='uniq_programa_saude_nome_tipo')],
            },
        ),
        migrations.AddField(
            model_name='pacientesaude',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='saude.programasaude'),
        ),
        migrations.CreateModel(
            name='ExameColetaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COLETA_AGENDADA', 'Coleta agendada'), ('COLETADO', 'Coletado'), ('ENCAMINHADO', 'Encaminhado'), ('RESULTADO_RECEBIDO', 'Resultado recebido')], default='SOLICITADO', max_length=20)),
                ('data_coleta', models.DateTimeField(blank=True, null=True)),
                ('local_coleta', models.CharField(blank=True, default='', max_length=180)),
                ('encaminhado_para', models.CharField(blank=True, default='', max_length=180)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluxos_exame_saude', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_coleta', to='saude.examepedidosaude')),
            ],
            options={
                'verbose_name': 'Fluxo de Exame',
                'verbose_name_plural': 'Fluxos de Exame',
                'ordering': ['-atualizado_em', '-id'],
                'indexes': [models.Index(fields=['status'], name='saude_exame_status_83b205_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternacaoRegistroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EVOLUCAO', 'Evolução'), ('PRESCRICAO_INTERNA', 'Prescrição interna')], max_length=30)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_internacao_saude', to=settings.AUTH_USER_MODEL)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='saude.internacaosaude')),
            ],
            options={
                'verbose_name': 'Registro de Internação',
                'verbose_name_plural': 'Registros de Internação',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='saude_inter_tipo_cc46fc_idx'), models.Index(fields=['criado_em'], name='saude_inter_criado__e7a5d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoUsoContinuoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=180)),
                ('dose', models.CharField(blank=True, default='', max_length=120)),
                ('via', models.CharField(blank=True, default='', max_length=80)),
                ('frequencia', models.CharField(blank=True, default='', max_length=120)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_uso_saude', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_uso', to='saude.pacientesaude')),
            ],
            options={
                'verbose_name': 'Medicamento em Uso Contínuo',
                'verbose_name_plural': 'Medicamentos em Uso Contínuo',
                'ordering': ['paciente__nome', 'medicamento'],
                'indexes': [models.Index(fields=['ativo'], name='saude_medic_ativo_b0ab2b_idx'), models.Index(fields=['medicamento'], name='saude_medic_medicam_4a1a24_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='internacaosaude',
            index=models.Index(fields=['status'], name='saude_inter_status_af31cd_idx'),
        ),
        migrations.AddIndex(
            model_name='internacaosaude',
            index=models.Index(fields=['tipo'], name='saude_inter_tipo_10f758_idx'),
        ),
        migrations.AddIndex(
            model_name='internacaosaude',
            index=models.Index(fields=['data_admissao'], name='saude_inter_data_ad_f28a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensacaosaude',
            index=models.Index(fields=['dispensado_em'], name='saude_dispe_dispens_53a6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensacaosaude',
            index=models.Index(fields=['medicamento'], name='saude_dispe_medicam_099f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsaude',
            index=models.Index(fields=['status'], name='saude_check_status_3d3edc_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsaude',
            index=models.Index(fields=['chegada_em'], name='saude_check_chegada_269646_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientesaude',
            index=models.Index(fields=['nome'], name='saude_pacie_nome_2623de_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientesaude',
            index=models.Index(fields=['ativo'], name='saude_pacie_ativo_508e09_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientesaude',
            index=models.Index(fields=['cpf_hash'], name='saude_pacie_cpf_has_0c38b6_idx'),
        ),
    ]
