# Generated by Django 5.2.11 on 2026-02-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_unidade_cnpj_unidade_email_unidade_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ano_letivo', models.PositiveIntegerField(default=2026)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], default='MANHA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano_letivo', 'nome'],
                'indexes': [models.Index(fields=['ano_letivo'], name='educacao_tu_ano_let_cb0969_idx'), models.Index(fields=['turno'], name='educacao_tu_turno_bb7e11_idx'), models.Index(fields=['ativo'], name='educacao_tu_ativo_401fd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('unidade', 'ano_letivo', 'nome'), name='uniq_turma_por_unidade_ano_nome')],
            },
        ),
    ]
