# Generated by Django 5.2.11 on 2026-02-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('nis', models.CharField(blank=True, default='', max_length=20)),
                ('nome_mae', models.CharField(blank=True, default='', max_length=180)),
                ('nome_pai', models.CharField(blank=True, default='', max_length=180)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('endereco', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='educacao_al_nome_1d1da1_idx'), models.Index(fields=['cpf'], name='educacao_al_cpf_34125d_idx'), models.Index(fields=['nis'], name='educacao_al_nis_fae522_idx'), models.Index(fields=['ativo'], name='educacao_al_ativo_142762_idx')],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ATIVA', 'Ativa'), ('TRANSFERIDO', 'Transferido'), ('CONCLUIDO', 'Concluído'), ('EVADIDO', 'Evadido'), ('CANCELADO', 'Cancelado')], default='ATIVA', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='educacao.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='educacao.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['situacao'], name='educacao_ma_situaca_4cb2fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'turma'), name='uniq_aluno_por_turma')],
            },
        ),
    ]
