# Generated by Django 5.2.11 on 2026-02-11 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0004_remove_aluno_educacao_al_nome_1d1da1_idx_and_more'),
        ('org', '0003_unidade_cnpj_unidade_email_unidade_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turma',
            name='uniq_turma_por_unidade_ano_nome',
        ),
        migrations.RemoveIndex(
            model_name='turma',
            name='educacao_tu_turno_bb7e11_idx',
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['nome'], name='educacao_al_nome_1d1da1_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['cpf'], name='educacao_al_cpf_34125d_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['nis'], name='educacao_al_nis_fae522_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['ativo'], name='educacao_al_ativo_142762_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['data_matricula'], name='educacao_ma_data_ma_54c429_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['nome'], name='educacao_tu_nome_035db6_idx'),
        ),
    ]
