# Generated by Django 5.2.11 on 2026-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0005_remove_turma_uniq_turma_por_unidade_ano_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
