# Generated by Django 5.2.11 on 2026-02-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0007_diarioturma_avaliacao_aula_frequencia_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_horario', to='educacao.turma')),
            ],
        ),
        migrations.CreateModel(
            name='AulaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado')], max_length=3)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('disciplina', models.CharField(max_length=120)),
                ('sala', models.CharField(blank=True, default='', max_length=60)),
                ('observacoes', models.CharField(blank=True, default='', max_length=180)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='educacao.gradehorario')),
            ],
            options={
                'ordering': ['dia', 'inicio'],
                'unique_together': {('grade', 'dia', 'inicio', 'fim')},
            },
        ),
    ]
