# Generated by Django 5.2.11 on 2026-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0008_gradehorario_aulahorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('tipo', models.CharField(choices=[('BIM', 'Bimestre'), ('TRI', 'Trimestre'), ('SEM', 'Semestre')], default='BIM', max_length=3)),
                ('numero', models.PositiveSmallIntegerField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ano_letivo', 'tipo', 'numero'],
                'unique_together': {('ano_letivo', 'tipo', 'numero')},
            },
        ),
    ]
