# Generated by Django 5.2.11 on 2026-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0011_avaliacaonota_componentecurricular_notacurricular_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE educacao_aluno ADD COLUMN cpf_enc text NOT NULL DEFAULT '';"
                        "ALTER TABLE educacao_aluno ADD COLUMN cpf_hash varchar(64) NOT NULL DEFAULT '';"
                        "ALTER TABLE educacao_aluno ADD COLUMN cpf_last4 varchar(4) NOT NULL DEFAULT '';"
                        "CREATE INDEX IF NOT EXISTS educacao_aluno_cpf_hash_idx ON educacao_aluno (cpf_hash);"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS educacao_aluno_cpf_hash_idx;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='aluno',
                    name='cpf_enc',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='aluno',
                    name='cpf_hash',
                    field=models.CharField(blank=True, db_index=True, default='', max_length=64),
                ),
                migrations.AddField(
                    model_name='aluno',
                    name='cpf_last4',
                    field=models.CharField(blank=True, default='', max_length=4),
                ),
            ],
        ),
    ]
