# Generated by Django 5.2.11 on 2026-02-25 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0012_aluno_cpf_enc_aluno_cpf_hash_aluno_cpf_last4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('REMANEJAMENTO', 'Remanejamento'), ('TRANSFERENCIA', 'Transferência'), ('CANCELAMENTO', 'Cancelamento'), ('REATIVACAO', 'Reativação'), ('SITUACAO', 'Mudança de situação')], default='SITUACAO', max_length=30)),
                ('situacao_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('situacao_nova', models.CharField(blank=True, default='', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_matricula', to='educacao.aluno')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='educacao.matricula')),
                ('turma_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='educacao.turma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='educacao.turma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_matricula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de matrícula',
                'verbose_name_plural': 'Movimentações de matrícula',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['aluno'], name='educacao_ma_aluno_i_96ce3e_idx'), models.Index(fields=['tipo'], name='educacao_ma_tipo_60810e_idx'), models.Index(fields=['criado_em'], name='educacao_ma_criado__086d1f_idx')],
            },
        ),
    ]
