# Generated by Django 5.2.11 on 2026-02-25 03:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0013_matriculamovimentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoPeriodoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_corte', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('frequencia_corte', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5)),
                ('total_alunos', models.PositiveIntegerField(default=0)),
                ('aprovados', models.PositiveIntegerField(default=0)),
                ('recuperacao', models.PositiveIntegerField(default=0)),
                ('reprovados', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, default='')),
                ('fechado_em', models.DateTimeField(auto_now=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_periodo_educacao', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_turma', to='educacao.periodoletivo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_periodo', to='educacao.turma')),
            ],
            options={
                'verbose_name': 'Fechamento do período (turma)',
                'verbose_name_plural': 'Fechamentos do período (turma)',
                'ordering': ['-periodo__ano_letivo', 'periodo__numero', 'turma__nome'],
                'unique_together': {('turma', 'periodo')},
            },
        ),
    ]
