# Generated by Django 5.2.11 on 2026-02-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0014_fechamentoperiodoturma'),
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRefeicaoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=20)),
                ('total_servidas', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, default='')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_refeicao_escolar', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Registro de refeição escolar',
                'verbose_name_plural': 'Registros de refeição escolar',
                'ordering': ['-data', 'unidade__nome', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='RotaTransporteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=20)),
                ('veiculo', models.CharField(blank=True, default='', max_length=120)),
                ('motorista', models.CharField(blank=True, default='', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_transporte_escolar', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Rota de transporte escolar',
                'verbose_name_plural': 'Rotas de transporte escolar',
                'ordering': ['unidade__nome', 'nome'],
                'unique_together': {('unidade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTransporteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_previsto', models.PositiveIntegerField(default=0)),
                ('total_transportados', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, default='')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='educacao.rotatransporteescolar')),
            ],
            options={
                'verbose_name': 'Registro de transporte escolar',
                'verbose_name_plural': 'Registros de transporte escolar',
                'ordering': ['-data', 'rota__nome'],
            },
        ),
        migrations.CreateModel(
            name='CardapioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=20)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardapios_escolares', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Cardápio escolar',
                'verbose_name_plural': 'Cardápios escolares',
                'ordering': ['-data', 'unidade__nome', 'turno'],
                'unique_together': {('unidade', 'data', 'turno')},
            },
        ),
    ]
