# Generated by Django 5.2.11 on 2026-02-26 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0017_alter_calendarioeducacionalevento_tipo'),
        ('org', '0007_secretariacadastrobase_secretariaconfiguracao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DECLARACAO_MATRICULA', 'Declaração de matrícula'), ('HISTORICO_ESCOLAR', 'Histórico escolar'), ('CERTIFICADO_CONCLUSAO', 'Certificado de conclusão'), ('CERTIFICADO_CURSO', 'Certificado de curso'), ('DECLARACAO_TRANSFERENCIA', 'Declaração de transferência'), ('OUTRO', 'Outro')], default='CERTIFICADO_CONCLUSAO', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('codigo_verificacao', models.CharField(blank=True, default='', max_length=24, unique=True)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
                ('resultado_final', models.CharField(blank=True, default='', max_length=60)),
                ('observacao', models.TextField(blank=True, default='')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='educacao/certificados/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certificado do aluno',
                'verbose_name_plural': 'Certificados do aluno',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlunoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIDAO_NASCIMENTO', 'Certidão de nascimento'), ('CPF', 'CPF'), ('RG', 'RG'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de residência'), ('CARTAO_VACINA', 'Cartão de vacina'), ('LAUDO', 'Laudo'), ('BOLETIM', 'Boletim'), ('HISTORICO', 'Histórico escolar'), ('DECLARACAO', 'Declaração'), ('CERTIFICADO', 'Certificado'), ('TRANSFERENCIA', 'Documento de transferência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=80)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='educacao/documentos/alunos/%Y/%m/')),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento do aluno',
                'verbose_name_plural': 'Documentos do aluno',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CoordenacaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('REGULAR', 'Ensino Regular'), ('EDUCACAO_INFANTIL', 'Educação Infantil'), ('EJA', 'Educação de Jovens e Adultos (EJA)'), ('EDUCACAO_PROFISSIONAL', 'Educação Profissional'), ('EDUCACAO_ESPECIAL', 'Educação Especial'), ('ATIVIDADE_COMPLEMENTAR', 'Atividade Complementar')], default='REGULAR', max_length=40)),
                ('etapa', models.CharField(blank=True, choices=[('CRECHE', 'Creche'), ('PRE_ESCOLA', 'Pré-escola'), ('FUNDAMENTAL_ANOS_INICIAIS', 'Ensino Fundamental (Anos Iniciais)'), ('FUNDAMENTAL_ANOS_FINAIS', 'Ensino Fundamental (Anos Finais)'), ('ENSINO_MEDIO', 'Ensino Médio'), ('EJA_FUNDAMENTAL', 'EJA - Ensino Fundamental'), ('EJA_MEDIO', 'EJA - Ensino Médio'), ('TECNICO_INTEGRADO', 'Técnico Integrado'), ('TECNICO_CONCOMITANTE', 'Técnico Concomitante'), ('TECNICO_SUBSEQUENTE', 'Técnico Subsequente'), ('FIC', 'Formação Inicial e Continuada (FIC)'), ('AEE', 'Atendimento Educacional Especializado (AEE)')], default='', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fim', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Coordenação de ensino',
                'verbose_name_plural': 'Coordenações de ensino',
                'ordering': ['unidade__nome', 'modalidade', 'coordenador__username'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('modalidade_oferta', models.CharField(choices=[('REGULAR', 'Ensino Regular'), ('EDUCACAO_INFANTIL', 'Educação Infantil'), ('EJA', 'Educação de Jovens e Adultos (EJA)'), ('TECNICA', 'Educação Profissional Técnica'), ('FIC', 'Formação Inicial e Continuada (FIC)'), ('SUPERIOR', 'Educação Superior'), ('LIVRE', 'Curso Livre')], db_index=True, default='REGULAR', max_length=30)),
                ('eixo_tecnologico', models.CharField(blank=True, default='', max_length=120)),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.RenameIndex(
            model_name='calendarioeducacionalevento',
            new_name='educacao_ca_ano_let_9330e7_idx',
            old_name='educacao_ca_ano_let_54ec07_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarioeducacionalevento',
            new_name='educacao_ca_secreta_2f8e98_idx',
            old_name='educacao_ca_secret_69fbe2_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarioeducacionalevento',
            new_name='educacao_ca_tipo_c89e3e_idx',
            old_name='educacao_ca_tipo_9eb90c_idx',
        ),
        migrations.AddField(
            model_name='matricula',
            name='concluinte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matricula',
            name='resultado_final',
            field=models.CharField(blank=True, default='', help_text='Resultado final da matrícula (aprovado, reprovado, curso em andamento etc.).', max_length=30),
        ),
        migrations.AddField(
            model_name='turma',
            name='bilingue_surdos',
            field=models.BooleanField(default=False, help_text='Marque quando a turma for bilíngue de surdos.'),
        ),
        migrations.AddField(
            model_name='turma',
            name='classe_especial',
            field=models.BooleanField(default=False, help_text='Marque quando a turma for de classe especial.'),
        ),
        migrations.AddField(
            model_name='turma',
            name='etapa',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('PRE_ESCOLA', 'Pré-escola'), ('FUNDAMENTAL_ANOS_INICIAIS', 'Ensino Fundamental (Anos Iniciais)'), ('FUNDAMENTAL_ANOS_FINAIS', 'Ensino Fundamental (Anos Finais)'), ('ENSINO_MEDIO', 'Ensino Médio'), ('EJA_FUNDAMENTAL', 'EJA - Ensino Fundamental'), ('EJA_MEDIO', 'EJA - Ensino Médio'), ('TECNICO_INTEGRADO', 'Técnico Integrado'), ('TECNICO_CONCOMITANTE', 'Técnico Concomitante'), ('TECNICO_SUBSEQUENTE', 'Técnico Subsequente'), ('FIC', 'Formação Inicial e Continuada (FIC)'), ('AEE', 'Atendimento Educacional Especializado (AEE)')], db_index=True, default='FUNDAMENTAL_ANOS_INICIAIS', max_length=40),
        ),
        migrations.AddField(
            model_name='turma',
            name='forma_oferta',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('EAD', 'Educação a Distância')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.CharField(choices=[('REGULAR', 'Ensino Regular'), ('EDUCACAO_INFANTIL', 'Educação Infantil'), ('EJA', 'Educação de Jovens e Adultos (EJA)'), ('EDUCACAO_PROFISSIONAL', 'Educação Profissional'), ('EDUCACAO_ESPECIAL', 'Educação Especial'), ('ATIVIDADE_COMPLEMENTAR', 'Atividade Complementar')], db_index=True, default='REGULAR', max_length=40),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['resultado_final'], name='educacao_ma_resulta_4caad9_idx'),
        ),
        migrations.AddField(
            model_name='alunocertificado',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='educacao.aluno'),
        ),
        migrations.AddField(
            model_name='alunocertificado',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alunocertificado',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='educacao.matricula'),
        ),
        migrations.AddField(
            model_name='alunodocumento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='educacao.aluno'),
        ),
        migrations.AddField(
            model_name='alunodocumento',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aluno_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordenacaoensino',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenacoes_ensino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordenacaoensino',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenacoes_ensino', to='org.unidade'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nome'], name='educacao_cu_nome_71f87e_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['codigo'], name='educacao_cu_codigo_1cf934_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['modalidade_oferta'], name='educacao_cu_modalid_b3d03f_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['ativo'], name='educacao_cu_ativo_0e5bef_idx'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('nome', 'codigo'), name='uniq_curso_nome_codigo'),
        ),
        migrations.AddField(
            model_name='alunocertificado',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to='educacao.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='educacao.curso'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['modalidade'], name='educacao_tu_modalid_3c9d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['etapa'], name='educacao_tu_etapa_280ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='alunodocumento',
            index=models.Index(fields=['aluno', 'tipo'], name='educacao_al_aluno_i_7e7709_idx'),
        ),
        migrations.AddIndex(
            model_name='alunodocumento',
            index=models.Index(fields=['ativo'], name='educacao_al_ativo_70fa14_idx'),
        ),
        migrations.AddIndex(
            model_name='coordenacaoensino',
            index=models.Index(fields=['unidade', 'modalidade', 'ativo'], name='educacao_co_unidade_9747fb_idx'),
        ),
        migrations.AddIndex(
            model_name='alunocertificado',
            index=models.Index(fields=['aluno', 'tipo'], name='educacao_al_aluno_i_0e7350_idx'),
        ),
        migrations.AddIndex(
            model_name='alunocertificado',
            index=models.Index(fields=['codigo_verificacao'], name='educacao_al_codigo__b53c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='alunocertificado',
            index=models.Index(fields=['ativo'], name='educacao_al_ativo_19be1c_idx'),
        ),
    ]
