# Generated by Django 5.2.11 on 2026-02-26 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0018_alunocertificado_alunodocumento_coordenacaoensino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo_aula', models.CharField(choices=[('TEORICA', 'Teórica'), ('PRATICA', 'Prática'), ('LABORATORIO', 'Laboratório'), ('OFICINA', 'Oficina'), ('PROJETO', 'Projeto'), ('PERFORMANCE', 'Performance'), ('OUTRA', 'Outra')], default='TEORICA', max_length=20)),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ementa', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='educacao.curso')),
            ],
            options={
                'verbose_name': 'Disciplina do curso',
                'verbose_name_plural': 'Disciplinas do curso',
                'ordering': ['curso__nome', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['curso', 'ordem'], name='educacao_cu_curso_i_71945a_idx'), models.Index(fields=['curso', 'ativo'], name='educacao_cu_curso_i_317028_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'nome'), name='uniq_disciplina_nome_por_curso')],
            },
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=django.utils.timezone.localdate)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('TRANCADO', 'Trancado'), ('CANCELADO', 'Cancelado')], default='MATRICULADO', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frequencia_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_cursos', to='educacao.aluno')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_cursos_registradas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_alunos', to='educacao.curso')),
                ('turma', models.ForeignKey(blank=True, help_text='Opcional: turma/oferta específica deste curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_cursos', to='educacao.turma')),
            ],
            options={
                'verbose_name': 'Matrícula em curso',
                'verbose_name_plural': 'Matrículas em cursos',
                'ordering': ['-data_matricula', '-id'],
                'indexes': [models.Index(fields=['aluno', 'situacao'], name='educacao_ma_aluno_i_f38846_idx'), models.Index(fields=['curso', 'situacao'], name='educacao_ma_curso_i_e4ab3c_idx'), models.Index(fields=['data_matricula'], name='educacao_ma_data_ma_566a20_idx')],
            },
        ),
    ]
