# Generated by Django 5.2.11 on 2026-02-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0019_cursodisciplina_matriculacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_diario', to='educacao.componentecurricular'),
        ),
        migrations.AddField(
            model_name='aula',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aulas_diario', to='educacao.periodoletivo'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='area_codigo_bncc',
            field=models.CharField(blank=True, default='', help_text='Código da área/componente BNCC (ex.: LP, MA, CG, EO, LGG).', max_length=8),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='codigo_bncc_referencia',
            field=models.CharField(blank=True, default='', help_text='Código BNCC principal de referência para o componente.', max_length=20),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='etapa_bncc',
            field=models.CharField(blank=True, choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_ANOS_INICIAIS', 'Fundamental - Anos Iniciais'), ('FUNDAMENTAL_ANOS_FINAIS', 'Fundamental - Anos Finais'), ('ENSINO_MEDIO', 'Ensino Médio')], default='', max_length=36),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='modalidade_bncc',
            field=models.CharField(blank=True, choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ENSINO_FUNDAMENTAL', 'Ensino Fundamental'), ('ENSINO_MEDIO', 'Ensino Médio')], db_index=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='BNCCCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('modalidade', models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ENSINO_FUNDAMENTAL', 'Ensino Fundamental'), ('ENSINO_MEDIO', 'Ensino Médio')], db_index=True, max_length=24)),
                ('etapa', models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_ANOS_INICIAIS', 'Fundamental - Anos Iniciais'), ('FUNDAMENTAL_ANOS_FINAIS', 'Fundamental - Anos Finais'), ('ENSINO_MEDIO', 'Ensino Médio')], db_index=True, max_length=36)),
                ('grupo_codigo', models.CharField(blank=True, default='', help_text='Prefixo etário/faixa (ex.: EI01, EM13).', max_length=8)),
                ('area_codigo', models.CharField(blank=True, db_index=True, default='', help_text='Código da área/componente no padrão BNCC (ex.: LP, MA, EO, LGG).', max_length=8)),
                ('ano_inicial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ano_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fonte_url', models.URLField(blank=True, default='https://basenacionalcomum.mec.gov.br/images/BNCC_EI_EF_110518_versaofinal_site.pdf')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Código BNCC',
                'verbose_name_plural': 'Códigos BNCC',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='educacao_bn_codigo_5b854b_idx'), models.Index(fields=['modalidade', 'etapa'], name='educacao_bn_modalid_c6b5b0_idx'), models.Index(fields=['area_codigo'], name='educacao_bn_area_co_b00446_idx'), models.Index(fields=['ativo'], name='educacao_bn_ativo_030464_idx')],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='bncc_codigos',
            field=models.ManyToManyField(blank=True, related_name='aulas', to='educacao.bncccodigo'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='bncc_codigos',
            field=models.ManyToManyField(blank=True, related_name='componentes_curriculares', to='educacao.bncccodigo'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['data'], name='educacao_au_data_0df79a_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['periodo'], name='educacao_au_periodo_5479bf_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['componente'], name='educacao_au_compone_29658f_idx'),
        ),
        migrations.AddIndex(
            model_name='componentecurricular',
            index=models.Index(fields=['modalidade_bncc', 'etapa_bncc'], name='educacao_co_modalid_0b1d90_idx'),
        ),
        migrations.AddIndex(
            model_name='componentecurricular',
            index=models.Index(fields=['area_codigo_bncc'], name='educacao_co_area_co_eaf9dd_idx'),
        ),
    ]
