# Generated by Django 5.2.11 on 2026-03-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0022_beneficiocampanha_beneficioedital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaFaltaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='educacao/justificativas/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], db_index=True, default='PENDENTE', max_length=12)),
                ('parecer', models.TextField(blank=True, default='')),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_justificativa_falta', to='educacao.aluno')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_falta_analisadas', to=settings.AUTH_USER_MODEL)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_justificativa', to='educacao.aula')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='educacao_ju_status_41d6ab_idx'), models.Index(fields=['aluno', 'status'], name='educacao_ju_aluno_i_74fffc_idx')],
                'constraints': [models.UniqueConstraint(fields=('aula', 'aluno'), name='uniq_justificativa_falta_aula_aluno')],
            },
        ),
    ]
