# Generated by Django 5.2.11 on 2026-03-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0023_justificativafaltapedido'),
        ('org', '0014_municipiothemeconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='serie_ano',
            field=models.CharField(choices=[('INFANTIL_BERCARIO', 'Berçário'), ('INFANTIL_MATERNAL_I', 'Maternal I'), ('INFANTIL_MATERNAL_II', 'Maternal II'), ('INFANTIL_JARDIM_I', 'Jardim I'), ('INFANTIL_JARDIM_II', 'Jardim II'), ('FUNDAMENTAL_1', '1º ano'), ('FUNDAMENTAL_2', '2º ano'), ('FUNDAMENTAL_3', '3º ano'), ('FUNDAMENTAL_4', '4º ano'), ('FUNDAMENTAL_5', '5º ano'), ('FUNDAMENTAL_6', '6º ano'), ('FUNDAMENTAL_7', '7º ano'), ('FUNDAMENTAL_8', '8º ano'), ('FUNDAMENTAL_9', '9º ano'), ('NAO_APLICA', 'Não se aplica')], db_index=True, default='FUNDAMENTAL_1', max_length=40),
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('etapa_base', models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_ANOS_INICIAIS', 'Ensino Fundamental (Anos Iniciais)'), ('FUNDAMENTAL_ANOS_FINAIS', 'Ensino Fundamental (Anos Finais)')], db_index=True, max_length=40)),
                ('serie_ano', models.CharField(choices=[('INFANTIL_BERCARIO', 'Berçário'), ('INFANTIL_MATERNAL_I', 'Maternal I'), ('INFANTIL_MATERNAL_II', 'Maternal II'), ('INFANTIL_JARDIM_I', 'Jardim I'), ('INFANTIL_JARDIM_II', 'Jardim II'), ('FUNDAMENTAL_1', '1º ano'), ('FUNDAMENTAL_2', '2º ano'), ('FUNDAMENTAL_3', '3º ano'), ('FUNDAMENTAL_4', '4º ano'), ('FUNDAMENTAL_5', '5º ano'), ('FUNDAMENTAL_6', '6º ano'), ('FUNDAMENTAL_7', '7º ano'), ('FUNDAMENTAL_8', '8º ano'), ('FUNDAMENTAL_9', '9º ano')], db_index=True, max_length=40)),
                ('ano_referencia', models.PositiveIntegerField(db_index=True, default=2026)),
                ('carga_horaria_anual', models.PositiveIntegerField(default=800)),
                ('dias_letivos_previstos', models.PositiveSmallIntegerField(default=200)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes_curriculares', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Matriz curricular',
                'verbose_name_plural': 'Matrizes curriculares',
                'ordering': ['-ano_referencia', 'etapa_base', 'serie_ano', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MatrizComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('carga_horaria_anual', models.PositiveIntegerField(default=0)),
                ('aulas_semanais', models.PositiveSmallIntegerField(default=0)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrizes', to='educacao.componentecurricular')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='educacao.matrizcurricular')),
            ],
            options={
                'verbose_name': 'Componente da matriz',
                'verbose_name_plural': 'Componentes da matriz',
                'ordering': ['matriz', 'ordem', 'componente__nome'],
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='matriz_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='educacao.matrizcurricular'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['serie_ano'], name='educacao_tu_serie_a_b3afbb_idx'),
        ),
        migrations.AddIndex(
            model_name='matrizcurricular',
            index=models.Index(fields=['unidade', 'ativo'], name='educacao_ma_unidade_edb7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='matrizcurricular',
            index=models.Index(fields=['etapa_base', 'serie_ano'], name='educacao_ma_etapa_b_190bff_idx'),
        ),
        migrations.AddIndex(
            model_name='matrizcurricular',
            index=models.Index(fields=['ano_referencia'], name='educacao_ma_ano_ref_3d24c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrizcurricular',
            constraint=models.UniqueConstraint(fields=('unidade', 'etapa_base', 'serie_ano', 'ano_referencia', 'nome'), name='uniq_matriz_unidade_etapa_serie_ano_nome'),
        ),
        migrations.AddIndex(
            model_name='matrizcomponente',
            index=models.Index(fields=['matriz', 'ordem'], name='educacao_ma_matriz__76acb2_idx'),
        ),
        migrations.AddIndex(
            model_name='matrizcomponente',
            index=models.Index(fields=['matriz', 'ativo'], name='educacao_ma_matriz__cac672_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponente',
            constraint=models.UniqueConstraint(fields=('matriz', 'componente'), name='uniq_matriz_componente'),
        ),
    ]
