# Generated by Django 5.2.11 on 2026-03-04 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0024_turma_serie_ano_matrizcurricular_matrizcomponente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizComponenteRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE_REQUISITO', 'Pré-requisito'), ('CO_REQUISITO', 'Co-requisito'), ('EQUIVALENCIA', 'Equivalência')], db_index=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_destino', to='educacao.matrizcomponente')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_origem', to='educacao.matrizcomponente')),
            ],
            options={
                'verbose_name': 'Relação entre componentes da matriz',
                'verbose_name_plural': 'Relações entre componentes da matriz',
                'ordering': ['tipo', 'origem__ordem', 'destino__ordem', 'id'],
                'indexes': [models.Index(fields=['origem', 'tipo'], name='educacao_ma_origem__4a5db1_idx'), models.Index(fields=['destino', 'tipo'], name='educacao_ma_destino_5e73f6_idx'), models.Index(fields=['ativo'], name='educacao_ma_ativo_f0e294_idx')],
                'constraints': [models.UniqueConstraint(fields=('origem', 'destino', 'tipo'), name='uniq_matriz_comp_relacao')],
            },
        ),
    ]
