# Generated by Django 5.2.11 on 2026-03-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0025_matrizcomponenterelacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizComponenteEquivalenciaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('minimo_componentes', models.PositiveSmallIntegerField(default=1, help_text='Quantidade mínima de componentes equivalentes aceitos para validação.')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_equivalencia', to='educacao.matrizcurricular')),
            ],
            options={
                'verbose_name': 'Grupo de equivalência da matriz',
                'verbose_name_plural': 'Grupos de equivalência da matriz',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrizComponenteEquivalenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='educacao.matrizcomponente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='educacao.matrizcomponenteequivalenciagrupo')),
            ],
            options={
                'verbose_name': 'Item de equivalência da matriz',
                'verbose_name_plural': 'Itens de equivalência da matriz',
                'ordering': ['grupo', 'ordem', 'componente__ordem', 'componente__componente__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='matrizcomponenteequivalenciagrupo',
            index=models.Index(fields=['matriz', 'ativo'], name='educacao_ma_matriz__7cdb00_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponenteequivalenciagrupo',
            constraint=models.UniqueConstraint(fields=('matriz', 'nome'), name='uniq_matriz_equiv_grupo_nome'),
        ),
        migrations.AddIndex(
            model_name='matrizcomponenteequivalenciaitem',
            index=models.Index(fields=['grupo', 'ordem'], name='educacao_ma_grupo_i_748b33_idx'),
        ),
        migrations.AddIndex(
            model_name='matrizcomponenteequivalenciaitem',
            index=models.Index(fields=['grupo', 'ativo'], name='educacao_ma_grupo_i_ae454f_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrizcomponenteequivalenciaitem',
            constraint=models.UniqueConstraint(fields=('grupo', 'componente'), name='uniq_grupo_equiv_componente'),
        ),
    ]
