# Generated by Django 5.2.11 on 2026-03-05

import apps.educacao.models_diario
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educacao", "0026_matrizcomponenteequivalenciagrupo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoEnsinoProfessor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano_letivo", models.PositiveIntegerField(db_index=True, default=apps.educacao.models_diario._current_year)),
                ("titulo", models.CharField(default="Plano de Ensino", max_length=180)),
                ("ementa", models.TextField(blank=True, default="")),
                ("objetivos", models.TextField(blank=True, default="")),
                ("metodologia", models.TextField(blank=True, default="")),
                ("criterios_avaliacao", models.TextField(blank=True, default="")),
                ("cronograma", models.TextField(blank=True, default="")),
                ("referencias", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("SUBMETIDO", "Submetido")],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=12,
                    ),
                ),
                ("submetido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_ensino",
                        to="educacao.diarioturma",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_ensino",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizado_em", "-id"],
                "indexes": [
                    models.Index(fields=["professor", "status"], name="educacao_pl_profess_4ca6f8_idx"),
                    models.Index(fields=["ano_letivo", "status"], name="educacao_pl_ano_le_693ed6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("diario", "professor"), name="uniq_plano_ensino_por_diario_professor")
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialAulaProfessor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=180)),
                ("descricao", models.TextField(blank=True, default="")),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="educacao/materiais/%Y/%m/")),
                ("link_externo", models.URLField(blank=True, default="")),
                ("publico_alunos", models.BooleanField(default=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiais",
                        to="educacao.aula",
                    ),
                ),
                (
                    "diario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiais",
                        to="educacao.diarioturma",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais_aula",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizado_em", "-id"],
                "indexes": [
                    models.Index(fields=["professor", "ativo"], name="educacao_ma_profess_fea8fa_idx"),
                    models.Index(fields=["diario", "ativo"], name="educacao_ma_diario__77a9c6_idx"),
                ],
            },
        ),
    ]
