# Generated by Django 5.2.11 on 2026-03-08 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0027_planoensino_material_professor'),
        ('org', '0014_municipiothemeconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBRIGATORIO', 'Obrigatório'), ('NAO_OBRIGATORIO', 'Não obrigatório')], db_index=True, default='OBRIGATORIO', max_length=20)),
                ('situacao', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=20)),
                ('concedente_nome', models.CharField(max_length=180)),
                ('concedente_cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('supervisor_nome', models.CharField(blank=True, default='', max_length=140)),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('carga_horaria_total', models.PositiveIntegerField(default=0)),
                ('carga_horaria_cumprida', models.PositiveIntegerField(default=0)),
                ('equivalencia_solicitada', models.BooleanField(default=False)),
                ('equivalencia_aprovada', models.BooleanField(default=False)),
                ('termo_compromisso', models.FileField(blank=True, null=True, upload_to='educacao/estagios/termos/%Y/%m/')),
                ('relatorio_final', models.FileField(blank=True, null=True, upload_to='educacao/estagios/relatorios/%Y/%m/')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='materialaulaprofessor',
            new_name='educacao_ma_profess_27e009_idx',
            old_name='educacao_ma_profess_fea8fa_idx',
        ),
        migrations.RenameIndex(
            model_name='materialaulaprofessor',
            new_name='educacao_ma_diario__c4e3c9_idx',
            old_name='educacao_ma_diario__77a9c6_idx',
        ),
        migrations.RenameIndex(
            model_name='planoensinoprofessor',
            new_name='educacao_pl_profess_838c4e_idx',
            old_name='educacao_pl_profess_4ca6f8_idx',
        ),
        migrations.RenameIndex(
            model_name='planoensinoprofessor',
            new_name='educacao_pl_ano_let_71ebbb_idx',
            old_name='educacao_pl_ano_le_693ed6_idx',
        ),
        migrations.AddField(
            model_name='estagio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagios', to='educacao.aluno'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estagio',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estagio',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios', to='educacao.matricula'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_orientados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estagio',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios', to='educacao.turma'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagios_educacao', to='org.unidade'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['unidade', 'situacao'], name='educacao_es_unidade_bc9e28_idx'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['aluno', 'tipo'], name='educacao_es_aluno_i_3c6c49_idx'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['matricula'], name='educacao_es_matricu_0547c3_idx'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['turma'], name='educacao_es_turma_i_77511e_idx'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['criado_em'], name='educacao_es_criado__7d7c69_idx'),
        ),
        migrations.AddIndex(
            model_name='estagio',
            index=models.Index(fields=['ativo'], name='educacao_es_ativo_354eb4_idx'),
        ),
    ]
