# Generated by Django 5.2.11 on 2026-03-09 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0028_estagio_and_more'),
        ('org', '0015_unidade_tipo_educacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformaticaEncontroSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('minutos_aula_efetiva', models.PositiveSmallIntegerField(default=45)),
                ('minutos_intervalo_tecnico', models.PositiveSmallIntegerField(default=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Encontro semanal da turma',
                'verbose_name_plural': 'Encontros semanais da turma',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('modalidade', models.CharField(choices=[('COMPLEMENTAR', 'Complementar'), ('LIVRE', 'Livre'), ('PROFISSIONALIZANTE', 'Profissionalizante')], default='COMPLEMENTAR', max_length=30)),
                ('carga_horaria_total', models.PositiveIntegerField(default=80)),
                ('faixa_etaria', models.CharField(blank=True, default='', max_length=100)),
                ('ano_escolar_permitido', models.CharField(blank=True, default='', max_length=160)),
                ('aulas_por_semana', models.PositiveSmallIntegerField(default=2)),
                ('duracao_bloco_minutos', models.PositiveSmallIntegerField(default=60)),
                ('minutos_aula_efetiva', models.PositiveSmallIntegerField(default=45)),
                ('minutos_intervalo_tecnico', models.PositiveSmallIntegerField(default=15)),
                ('max_alunos_por_turma', models.PositiveSmallIntegerField(default=12)),
                ('permitir_multiplas_turmas_por_aluno', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informatica_cursos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Curso de informática',
                'verbose_name_plural': 'Cursos de informática',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaAulaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(default=django.utils.timezone.localdate)),
                ('conteudo_ministrado', models.TextField(blank=True, default='')),
                ('atividade_realizada', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='educacao/informatica/diario/%Y/%m/')),
                ('encerrada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informatica_aulas_ministradas', to=settings.AUTH_USER_MODEL)),
                ('encontro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='educacao.informaticaencontrosemanal')),
            ],
            options={
                'verbose_name': 'Aula/diário do curso de informática',
                'verbose_name_plural': 'Aulas/diário do curso de informática',
                'ordering': ['-data_aula', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('justificativa', models.CharField(blank=True, default='', max_length=220)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informatica_frequencias', to='educacao.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='educacao.informaticaauladiario')),
            ],
            options={
                'verbose_name': 'Frequência da aula de informática',
                'verbose_name_plural': 'Frequências das aulas de informática',
                'ordering': ['aula', 'aluno__nome'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('endereco', models.CharField(blank=True, default='', max_length=220)),
                ('quantidade_computadores', models.PositiveSmallIntegerField(default=0)),
                ('capacidade_operacional', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('responsavel_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios_informatica_responsavel', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios_informatica', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Laboratório de informática',
                'verbose_name_plural': 'Laboratórios de informática',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('MATRICULADO', 'Matriculado'), ('LISTA_ESPERA', 'Lista de espera'), ('TRANSFERIDO', 'Transferido'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído')], default='MATRICULADO', max_length=20)),
                ('origem_indicacao', models.CharField(blank=True, default='Escola', max_length=80)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('externo_laboratorio', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informatica_matriculas', to='educacao.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informatica_matriculas_criadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='educacao.informaticacurso')),
                ('escola_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informatica_matriculas_origem', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Matrícula do curso de informática',
                'verbose_name_plural': 'Matrículas do curso de informática',
                'ordering': ['-data_matricula', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaAlertaFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BAIXA_FREQUENCIA', 'Baixa frequência (< 75%)'), ('FALTAS_CONSECUTIVAS', 'Faltas consecutivas (>= 3)')], max_length=30)),
                ('percentual_frequencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('faltas_consecutivas', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_frequencia', to='educacao.informaticamatricula')),
            ],
            options={
                'verbose_name': 'Alerta de frequência (informática)',
                'verbose_name_plural': 'Alertas de frequência (informática)',
                'ordering': ['-gerado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaSolicitacaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_preferido', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('QUALQUER', 'Qualquer')], default='QUALQUER', max_length=10)),
                ('disponibilidade', models.CharField(blank=True, default='', max_length=200)),
                ('origem_indicacao', models.CharField(blank=True, default='Escola', max_length=80)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('LISTA_ESPERA', 'Lista de espera'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informatica_solicitacoes', to='educacao.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informatica_solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='educacao.informaticacurso')),
                ('escola_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informatica_solicitacoes_origem', to='org.unidade')),
                ('laboratorio_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_preferidas', to='educacao.informaticalaboratorio')),
            ],
            options={
                'verbose_name': 'Solicitação de vaga (informática)',
                'verbose_name_plural': 'Solicitações de vaga (informática)',
                'ordering': ['status', '-prioridade', 'data_solicitacao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nome', models.CharField(blank=True, default='', max_length=180)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=10)),
                ('ano_letivo', models.PositiveIntegerField(default=2026)),
                ('periodo_letivo', models.CharField(blank=True, default='', max_length=80)),
                ('max_vagas', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('permite_aluno_externo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='educacao.informaticacurso')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_informatica_instrutor', to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='educacao.informaticalaboratorio')),
            ],
            options={
                'verbose_name': 'Turma de informática',
                'verbose_name_plural': 'Turmas de informática',
                'ordering': ['-ano_letivo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFRAESTRUTURA', 'Infraestrutura'), ('PEDAGOGICA', 'Pedagógica'), ('DISCIPLINAR', 'Disciplinar'), ('FREQUENCIA', 'Frequência'), ('OUTRA', 'Outra')], default='OUTRA', max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informatica_ocorrencias', to='educacao.aluno')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='educacao.informaticaauladiario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informatica_ocorrencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='educacao.informaticaturma')),
            ],
            options={
                'verbose_name': 'Ocorrência da aula de informática',
                'verbose_name_plural': 'Ocorrências das aulas de informática',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='informaticamatricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='educacao.informaticaturma'),
        ),
        migrations.CreateModel(
            name='InformaticaListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_preferido', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('QUALQUER', 'Qualquer')], default='QUALQUER', max_length=10)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('posicao', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONVOCADA', 'Convocada'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informatica_lista_espera', to='educacao.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_espera', to='educacao.informaticacurso')),
                ('escola_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informatica_lista_espera_origem', to='org.unidade')),
                ('laboratorio_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera_preferencial', to='educacao.informaticalaboratorio')),
                ('solicitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_lista_espera', to='educacao.informaticasolicitacaovaga')),
                ('turma_preferida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera_preferencial', to='educacao.informaticaturma')),
            ],
            options={
                'verbose_name': 'Lista de espera (informática)',
                'verbose_name_plural': 'Lista de espera (informática)',
                'ordering': ['curso', 'posicao', 'id'],
            },
        ),
        migrations.AddField(
            model_name='informaticaencontrosemanal',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros', to='educacao.informaticaturma'),
        ),
        migrations.AddField(
            model_name='informaticaauladiario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='educacao.informaticaturma'),
        ),
        migrations.AddIndex(
            model_name='informaticacurso',
            index=models.Index(fields=['municipio', 'ativo'], name='educacao_in_municip_02e028_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticacurso',
            index=models.Index(fields=['nome'], name='educacao_in_nome_424ead_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticacurso',
            index=models.Index(fields=['ativo'], name='educacao_in_ativo_ecf77d_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticacurso',
            constraint=models.UniqueConstraint(fields=('municipio', 'nome'), name='uniq_informatica_curso_nome_municipio'),
        ),
        migrations.AddIndex(
            model_name='informaticafrequencia',
            index=models.Index(fields=['aula', 'aluno'], name='educacao_in_aula_id_07c8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticafrequencia',
            index=models.Index(fields=['presente'], name='educacao_in_present_87b0b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticafrequencia',
            constraint=models.UniqueConstraint(fields=('aula', 'aluno'), name='uniq_informatica_freq_aula_aluno'),
        ),
        migrations.AddIndex(
            model_name='informaticalaboratorio',
            index=models.Index(fields=['status'], name='educacao_in_status_623b13_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticalaboratorio',
            index=models.Index(fields=['ativo'], name='educacao_in_ativo_23db56_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticalaboratorio',
            index=models.Index(fields=['unidade'], name='educacao_in_unidade_924f9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticalaboratorio',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='uniq_lab_informatica_unidade_nome'),
        ),
        migrations.AddIndex(
            model_name='informaticaalertafrequencia',
            index=models.Index(fields=['matricula', 'ativo'], name='educacao_in_matricu_240a09_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaalertafrequencia',
            index=models.Index(fields=['tipo', 'ativo'], name='educacao_in_tipo_eb95fc_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticasolicitacaovaga',
            index=models.Index(fields=['status', 'data_solicitacao'], name='educacao_in_status_6958f7_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticasolicitacaovaga',
            index=models.Index(fields=['curso', 'turno_preferido'], name='educacao_in_curso_i_7908b2_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticasolicitacaovaga',
            index=models.Index(fields=['escola_origem'], name='educacao_in_escola__e6943c_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaturma',
            index=models.Index(fields=['curso', 'ano_letivo'], name='educacao_in_curso_i_7443f7_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaturma',
            index=models.Index(fields=['laboratorio', 'turno'], name='educacao_in_laborat_f33a21_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaturma',
            index=models.Index(fields=['status'], name='educacao_in_status_110357_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticaturma',
            constraint=models.UniqueConstraint(fields=('curso', 'codigo', 'ano_letivo'), name='uniq_turma_informatica_codigo_ano'),
        ),
        migrations.AddIndex(
            model_name='informaticaocorrencia',
            index=models.Index(fields=['turma', 'tipo'], name='educacao_in_turma_i_3b80a8_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaocorrencia',
            index=models.Index(fields=['aluno'], name='educacao_in_aluno_i_a607ed_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticamatricula',
            index=models.Index(fields=['curso', 'status'], name='educacao_in_curso_i_f8f31d_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticamatricula',
            index=models.Index(fields=['turma', 'status'], name='educacao_in_turma_i_967dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticamatricula',
            index=models.Index(fields=['aluno', 'status'], name='educacao_in_aluno_i_3f2815_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticalistaespera',
            index=models.Index(fields=['curso', 'status', 'posicao'], name='educacao_in_curso_i_e2a147_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticalistaespera',
            index=models.Index(fields=['aluno', 'status'], name='educacao_in_aluno_i_980bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaencontrosemanal',
            index=models.Index(fields=['dia_semana', 'hora_inicio', 'hora_fim'], name='educacao_in_dia_sem_ce8786_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaencontrosemanal',
            index=models.Index(fields=['turma', 'ativo'], name='educacao_in_turma_i_529c02_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticaencontrosemanal',
            constraint=models.UniqueConstraint(fields=('turma', 'dia_semana'), name='uniq_encontro_turma_dia'),
        ),
        migrations.AddIndex(
            model_name='informaticaauladiario',
            index=models.Index(fields=['turma', 'data_aula'], name='educacao_in_turma_i_8c4cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaauladiario',
            index=models.Index(fields=['encerrada'], name='educacao_in_encerra_0bec95_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticaauladiario',
            constraint=models.UniqueConstraint(fields=('turma', 'data_aula'), name='uniq_informatica_aula_turma_data'),
        ),
    ]
