# Generated by Django 5.2.11 on 2026-03-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0029_informaticaencontrosemanal_informaticacurso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticaauladiario',
            name='duracao_total_minutos',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='informaticaauladiario',
            name='formato_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informaticaauladiario',
            name='pausa_interna_minutos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informaticaauladiario',
            name='status',
            field=models.CharField(choices=[('PREVISTA', 'Prevista'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REMARCADA', 'Remarcada'), ('REPOSTA', 'Reposta')], default='PREVISTA', max_length=20),
        ),
        migrations.AddField(
            model_name='informaticaauladiario',
            name='tipo_encontro',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('ESPECIAL_SEXTA', 'Especial de sexta'), ('REPOSICAO', 'Reposição')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='informaticaencontrosemanal',
            name='formato_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informaticaencontrosemanal',
            name='tipo_encontro',
            field=models.CharField(default='REGULAR', max_length=30),
        ),
        migrations.AddField(
            model_name='informaticaturma',
            name='carga_horaria_semanal_minutos',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='informaticaturma',
            name='encontro_unico_semana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informaticaturma',
            name='modalidade_oferta',
            field=models.CharField(default='PADRAO_SEMANAL', max_length=30),
        ),
        migrations.CreateModel(
            name='InformaticaGradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('codigo', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo_grade', models.CharField(choices=[('PADRAO_SEMANAL', 'Semanal em 2 dias'), ('ESPECIAL_SEXTA', 'Especial de sexta-feira')], default='PADRAO_SEMANAL', max_length=30)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=10)),
                ('dia_semana_1', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado')])),
                ('dia_semana_2', models.IntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado')], null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_total_minutos', models.PositiveSmallIntegerField(default=60)),
                ('duracao_aula_minutos', models.PositiveSmallIntegerField(default=45)),
                ('duracao_intervalo_minutos', models.PositiveSmallIntegerField(default=15)),
                ('pausa_interna_opcional_minutos', models.PositiveSmallIntegerField(default=0)),
                ('ano_letivo', models.PositiveIntegerField(default=2026)),
                ('periodo_letivo', models.CharField(blank=True, default='', max_length=80)),
                ('capacidade_maxima', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_horario', to='educacao.informaticalaboratorio')),
                ('professor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_informatica_principais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade de horário (informática)',
                'verbose_name_plural': 'Grades de horário (informática)',
                'ordering': ['-ano_letivo', 'laboratorio__nome', 'hora_inicio', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='informaticaencontrosemanal',
            name='grade_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encontros_semanais', to='educacao.informaticagradehorario'),
        ),
        migrations.AddField(
            model_name='informaticaturma',
            name='grade_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='educacao.informaticagradehorario'),
        ),
        migrations.AddIndex(
            model_name='informaticagradehorario',
            index=models.Index(fields=['laboratorio', 'status', 'ano_letivo'], name='educacao_in_laborat_d0559f_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticagradehorario',
            index=models.Index(fields=['turno', 'status'], name='educacao_in_turno_8afdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticagradehorario',
            index=models.Index(fields=['tipo_grade', 'status'], name='educacao_in_tipo_gr_50ed29_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticagradehorario',
            index=models.Index(fields=['dia_semana_1', 'dia_semana_2'], name='educacao_in_dia_sem_634ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticagradehorario',
            index=models.Index(fields=['ativo'], name='educacao_in_ativo_7f97be_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticagradehorario',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'codigo', 'ano_letivo'), name='uniq_grade_informatica_lab_codigo_ano'),
        ),
    ]
