# Generated by Django 5.2.11 on 2026-03-09 18:23

import apps.educacao.models_informatica
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0030_informaticaauladiario_duracao_total_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformaticaPlanoEnsinoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(db_index=True, default=apps.educacao.models_informatica._current_year)),
                ('titulo', models.CharField(default='Plano de Ensino • Informática', max_length=180)),
                ('ementa', models.TextField(blank=True, default='')),
                ('objetivos', models.TextField(blank=True, default='')),
                ('metodologia', models.TextField(blank=True, default='')),
                ('criterios_avaliacao', models.TextField(blank=True, default='')),
                ('cronograma', models.TextField(blank=True, default='')),
                ('referencias', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido')], db_index=True, default='RASCUNHO', max_length=12)),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de ensino (informática)',
                'verbose_name_plural': 'Planos de ensino (informática)',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='materialaulaprofessor',
            name='aula_informatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_professor', to='educacao.informaticaauladiario'),
        ),
        migrations.AddField(
            model_name='materialaulaprofessor',
            name='turma_informatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_professor', to='educacao.informaticaturma'),
        ),
        migrations.AddIndex(
            model_name='materialaulaprofessor',
            index=models.Index(fields=['turma_informatica', 'ativo'], name='educacao_ma_turma_i_893595_idx'),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_ensino_informatica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_ensino', to='educacao.informaticaturma'),
        ),
        migrations.AddIndex(
            model_name='informaticaplanoensinoprofessor',
            index=models.Index(fields=['professor', 'status'], name='educacao_in_profess_a89656_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaplanoensinoprofessor',
            index=models.Index(fields=['ano_letivo', 'status'], name='educacao_in_ano_let_5f9120_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticaplanoensinoprofessor',
            constraint=models.UniqueConstraint(fields=('turma', 'professor'), name='uniq_plano_ensino_informatica_turma_professor'),
        ),
    ]
