# Generated by Django 5.2.11 on 2026-03-09 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0031_informaticaplanoensinoprofessor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformaticaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_informatica', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='educacao.informaticaturma')),
            ],
            options={
                'verbose_name': 'Avaliação (informática)',
                'verbose_name_plural': 'Avaliações (informática)',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InformaticaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_informatica', to='educacao.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='educacao.informaticaavaliacao')),
            ],
            options={
                'verbose_name': 'Nota de avaliação (informática)',
                'verbose_name_plural': 'Notas de avaliação (informática)',
                'ordering': ['aluno__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='informaticaavaliacao',
            index=models.Index(fields=['turma', 'data'], name='educacao_in_turma_i_74884c_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaavaliacao',
            index=models.Index(fields=['professor', 'ativo'], name='educacao_in_profess_20572e_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticaavaliacao',
            index=models.Index(fields=['ativo'], name='educacao_in_ativo_cbaeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='informaticanota',
            index=models.Index(fields=['avaliacao', 'aluno'], name='educacao_in_avaliac_5b5aae_idx'),
        ),
        migrations.AddConstraint(
            model_name='informaticanota',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'aluno'), name='uniq_informatica_nota_avaliacao_aluno'),
        ),
    ]
