# Generated by Django 5.2.11 on 2026-03-11 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0032_informaticaavaliacao_informaticanota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformaticaMatriculaMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('REMANEJAMENTO', 'Remanejamento'), ('CANCELAMENTO', 'Cancelamento'), ('REATIVACAO', 'Reativação'), ('SITUACAO', 'Mudança de situação')], default='SITUACAO', max_length=30)),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('status_novo', models.CharField(blank=True, default='', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_matricula_informatica', to='educacao.aluno')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='educacao.informaticamatricula')),
                ('turma_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino_matricula', to='educacao.informaticaturma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem_matricula', to='educacao.informaticaturma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_matricula_informatica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de matrícula (informática)',
                'verbose_name_plural': 'Movimentações de matrícula (informática)',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['aluno'], name='educacao_in_aluno_i_27f85e_idx'), models.Index(fields=['tipo'], name='educacao_in_tipo_0226c3_idx'), models.Index(fields=['criado_em'], name='educacao_in_criado__29fd2a_idx')],
            },
        ),
    ]
