# Generated by Django 5.2.1 on 2026-03-13 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educacao", "0033_informaticamatriculamovimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriculamovimentacao",
            name="data_referencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matriculamovimentacao",
            name="movimentacao_desfeita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="desfeita_por",
                to="educacao.matriculamovimentacao",
            ),
        ),
        migrations.AddField(
            model_name="matriculamovimentacao",
            name="tipo_trancamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOLUNTARIO", "Voluntário"),
                    ("COMPULSORIO", "Compulsório"),
                    ("INTERCAMBIO", "Intercâmbio"),
                    ("OUTRO", "Outro"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("TRANCADO", "Trancado"),
                    ("TRANSFERIDO", "Transferido"),
                    ("CONCLUIDO", "Concluído"),
                    ("EVADIDO", "Evadido"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="ATIVA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="matriculamovimentacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Criação"),
                    ("REMANEJAMENTO", "Remanejamento"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("CANCELAMENTO", "Cancelamento"),
                    ("TRANCAMENTO", "Trancamento"),
                    ("REATIVACAO", "Reativação"),
                    ("DESFAZER", "Desfazer procedimento"),
                    ("SITUACAO", "Mudança de situação"),
                ],
                default="SITUACAO",
                max_length=30,
            ),
        ),
    ]
