# Generated by Django 5.2.12 on 2026-03-14 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0034_matriculamovimentacao_data_referencia_and_more'),
        ('org', '0015_unidade_tipo_educacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovacaoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=220)),
                ('ano_letivo', models.PositiveIntegerField(db_index=True)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('processado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_matricula_criadas', to=settings.AUTH_USER_MODEL)),
                ('periodo_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_matricula', to='educacao.periodoletivo')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_matricula_processadas', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renovacoes_matricula', to='org.secretaria')),
            ],
            options={
                'verbose_name': 'Renovação de matrícula',
                'verbose_name_plural': 'Renovações de matrícula',
                'ordering': ['-ano_letivo', '-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenovacaoMatriculaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_ofertadas', to='educacao.diarioturma')),
                ('renovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='educacao.renovacaomatricula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renovacoes_ofertadas', to='educacao.turma')),
            ],
            options={
                'verbose_name': 'Oferta de renovação',
                'verbose_name_plural': 'Ofertas de renovação',
                'ordering': ['turma__nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RenovacaoMatriculaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.PositiveSmallIntegerField(default=1)),
                ('observacao_aluno', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE', max_length=12)),
                ('observacao_processamento', models.TextField(blank=True, default='')),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_renovacao_matricula', to='educacao.aluno')),
                ('matricula_resultante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_renovacao_resultantes', to='educacao.matricula')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='educacao.renovacaomatriculaoferta')),
                ('origem_matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_renovacao_origem', to='educacao.matricula')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_renovacao_processados', to=settings.AUTH_USER_MODEL)),
                ('renovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='educacao.renovacaomatricula')),
            ],
            options={
                'verbose_name': 'Pedido de renovação de matrícula',
                'verbose_name_plural': 'Pedidos de renovação de matrícula',
                'ordering': ['status', 'prioridade', 'criado_em', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='renovacaomatricula',
            index=models.Index(fields=['secretaria', 'ano_letivo'], name='educacao_re_secreta_22addd_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatricula',
            index=models.Index(fields=['secretaria', 'ativo'], name='educacao_re_secreta_c8e5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatricula',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='educacao_re_data_in_a87d12_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatriculaoferta',
            index=models.Index(fields=['renovacao', 'ativo'], name='educacao_re_renovac_53489e_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatriculaoferta',
            index=models.Index(fields=['turma'], name='educacao_re_turma_i_337355_idx'),
        ),
        migrations.AddConstraint(
            model_name='renovacaomatriculaoferta',
            constraint=models.UniqueConstraint(fields=('renovacao', 'turma'), name='uniq_renovacao_oferta_turma'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatriculapedido',
            index=models.Index(fields=['renovacao', 'status'], name='educacao_re_renovac_2164d7_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatriculapedido',
            index=models.Index(fields=['aluno', 'status'], name='educacao_re_aluno_i_ac988c_idx'),
        ),
        migrations.AddIndex(
            model_name='renovacaomatriculapedido',
            index=models.Index(fields=['renovacao', 'prioridade'], name='educacao_re_renovac_10b389_idx'),
        ),
        migrations.AddConstraint(
            model_name='renovacaomatriculapedido',
            constraint=models.UniqueConstraint(fields=('renovacao', 'aluno', 'oferta'), name='uniq_renovacao_pedido_aluno_oferta'),
        ),
    ]
