# Generated by Django 5.2.12 on 2026-03-14 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0035_renovacaomatricula_renovacaomatriculaoferta_and_more'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovacaomatriculapedido',
            name='processo_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_renovacao', to='processos.processoadministrativo'),
        ),
    ]
