# Generated by Django 5.2.12 on 2026-03-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0036_renovacaomatriculapedido_processo_administrativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_info_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='devolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='devolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_info_devolvidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='homologado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='homologado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_info_homologados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informaticaplanoensinoprofessor',
            name='motivo_devolucao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='devolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='devolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_devolvidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='homologado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='homologado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino_homologados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoensinoprofessor',
            name='motivo_devolucao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informaticaplanoensinoprofessor',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Aguardando aprovação'), ('APROVADO', 'Aguardando homologação'), ('HOMOLOGADO', 'Homologado'), ('DEVOLVIDO', 'Devolvido para ajustes')], db_index=True, default='RASCUNHO', max_length=12),
        ),
        migrations.AlterField(
            model_name='planoensinoprofessor',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Aguardando aprovação'), ('APROVADO', 'Aguardando homologação'), ('HOMOLOGADO', 'Homologado'), ('DEVOLVIDO', 'Devolvido para ajustes')], db_index=True, default='RASCUNHO', max_length=12),
        ),
    ]
