# Generated by Django 5.2.12 on 2026-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0037_informaticaplanoensinoprofessor_aprovado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='quantidade_aulas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo_aula',
            field=models.CharField(choices=[('TEORICA', 'Aula Teórica'), ('PRATICA', 'Aula Prática')], default='TEORICA', max_length=12),
        ),
        migrations.AddField(
            model_name='aula',
            name='url_atividade',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='modo_registro',
            field=models.CharField(choices=[('NOTA', 'Notas'), ('CONCEITO', 'Conceitos')], db_index=True, default='NOTA', max_length=12),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade'), ('PROJETO', 'Projeto'), ('PARTICIPACAO', 'Participação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='informaticaavaliacao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='informaticaavaliacao',
            name='modo_registro',
            field=models.CharField(choices=[('NOTA', 'Notas'), ('CONCEITO', 'Conceitos')], db_index=True, default='NOTA', max_length=12),
        ),
        migrations.AddField(
            model_name='informaticaavaliacao',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='informaticaavaliacao',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade'), ('PROJETO', 'Projeto'), ('PARTICIPACAO', 'Participação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='informaticanota',
            name='conceito',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='nota',
            name='conceito',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
