# Generated by Django 5.2.12 on 2026-03-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0038_aula_quantidade_aulas_aula_tipo_aula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticaturma',
            name='permite_sobreposicao_horario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='permite_sobreposicao_horario',
            field=models.BooleanField(default=False, help_text='Permite matrícula com sobreposição de horário para esta oferta.'),
        ),
        migrations.CreateModel(
            name='ScheduleConflictSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Política padrão de conflitos', max_length=80)),
                ('modo_validacao', models.CharField(choices=[('BLOCK', 'Bloqueio obrigatório'), ('WARN', 'Aviso com permissão especial'), ('ALLOW', 'Apenas aviso')], default='BLOCK', max_length=10)),
                ('permitir_excecao', models.BooleanField(default=True)),
                ('exigir_justificativa_excecao', models.BooleanField(default=True)),
                ('considerar_intervalos_encostados_validos', models.BooleanField(default=True)),
                ('considerar_conflito_entre_modulos', models.BooleanField(default=True)),
                ('validar_importacoes', models.BooleanField(default=True)),
                ('validar_edicao_grade', models.BooleanField(default=True)),
                ('ativar_alerta_visual', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de conflito de horários',
                'verbose_name_plural': 'Configurações de conflito de horários',
                'ordering': ['-ativo', '-id'],
                'indexes': [models.Index(fields=['ativo'], name='educacao_sc_ativo_e41ee8_idx'), models.Index(fields=['modo_validacao', 'ativo'], name='educacao_sc_modo_va_420797_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflictOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(blank=True, default='', max_length=80)),
                ('modo_aplicado', models.CharField(choices=[('BLOCK', 'Bloqueio obrigatório'), ('WARN', 'Aviso com permissão especial'), ('ALLOW', 'Apenas aviso')], default='BLOCK', max_length=10)),
                ('justificativa', models.TextField()),
                ('ip_origem', models.CharField(blank=True, default='', max_length=64)),
                ('nova_oferta_tipo', models.CharField(blank=True, default='', max_length=40)),
                ('nova_oferta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nova_oferta_nome', models.CharField(blank=True, default='', max_length=220)),
                ('oferta_conflitante_tipo', models.CharField(blank=True, default='', max_length=40)),
                ('oferta_conflitante_id', models.PositiveIntegerField(blank=True, null=True)),
                ('oferta_conflitante_nome', models.CharField(blank=True, default='', max_length=220)),
                ('unidade_nome', models.CharField(blank=True, default='', max_length=180)),
                ('secretaria_nome', models.CharField(blank=True, default='', max_length=180)),
                ('payload_resumo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides_conflito_horario', to='educacao.aluno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_conflito_horario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de conflito de horário',
                'verbose_name_plural': 'Overrides de conflito de horário',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['aluno', 'criado_em'], name='educacao_sc_aluno_i_31ea8b_idx'), models.Index(fields=['usuario', 'criado_em'], name='educacao_sc_usuario_c57e83_idx'), models.Index(fields=['contexto'], name='educacao_sc_context_243797_idx'), models.Index(fields=['modo_aplicado'], name='educacao_sc_modo_ap_3ad2c3_idx')],
            },
        ),
    ]
