# Generated by Django 5.2.12 on 2026-03-24 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0039_informaticaturma_permite_sobreposicao_horario_and_more'),
        ('org', '0016_localestrutural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Biblioteca principal'), ('SALA_LEITURA', 'Sala de leitura'), ('ACERVO_COMPLEMENTAR', 'Acervo complementar'), ('INFANTIL', 'Biblioteca infantil'), ('TECNICA', 'Biblioteca técnica'), ('LABORATORIO', 'Biblioteca de laboratório')], default='PRINCIPAL', max_length=30)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], db_index=True, default='ATIVA', max_length=20)),
                ('limite_emprestimos_ativos', models.PositiveSmallIntegerField(default=3)),
                ('dias_prazo_emprestimo', models.PositiveSmallIntegerField(default=7)),
                ('permitir_emprestimo_com_atraso', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotecas_escolares_responsavel', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bibliotecas_escolares', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Biblioteca escolar',
                'verbose_name_plural': 'Bibliotecas escolares',
                'ordering': ['unidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=220)),
                ('autor', models.CharField(blank=True, default='', max_length=180)),
                ('editora', models.CharField(blank=True, default='', max_length=180)),
                ('edicao', models.CharField(blank=True, default='', max_length=40)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, default='', max_length=40)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('assunto', models.CharField(blank=True, default='', max_length=140)),
                ('idioma', models.CharField(blank=True, default='Português', max_length=60)),
                ('descricao', models.TextField(blank=True, default='')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='biblioteca/capas/')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], db_index=True, default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='educacao.bibliotecaescolar')),
            ],
            options={
                'verbose_name': 'Livro da biblioteca',
                'verbose_name_plural': 'Livros da biblioteca',
                'ordering': ['titulo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaExemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exemplar', models.CharField(max_length=40)),
                ('tombo', models.CharField(blank=True, default='', max_length=40)),
                ('localizacao_estante', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('RESERVADO', 'Reservado'), ('MANUTENCAO', 'Em manutenção'), ('PERDIDO', 'Perdido'), ('BAIXADO', 'Baixado')], db_index=True, default='DISPONIVEL', max_length=20)),
                ('condicao_fisica', models.CharField(choices=[('OTIMA', 'Ótima'), ('BOA', 'Boa'), ('REGULAR', 'Regular'), ('DANIFICADO', 'Danificado')], db_index=True, default='BOA', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemplares', to='educacao.bibliotecalivro')),
            ],
            options={
                'verbose_name': 'Exemplar da biblioteca',
                'verbose_name_plural': 'Exemplares da biblioteca',
                'ordering': ['livro__titulo', 'codigo_exemplar'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ano_referencia', models.PositiveIntegerField(db_index=True, default=2026)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('TRANSFERIDA', 'Transferida'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ATIVA', max_length=20)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_ativacao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('motivo_encerramento', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='matricula_institucional', to='educacao.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_institucionais_criadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_institucionais', to='org.municipio')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_institucionais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Matrícula institucional',
                'verbose_name_plural': 'Matrículas institucionais',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_prevista_devolucao', models.DateField(db_index=True)),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado'), ('RENOVADO', 'Renovado')], db_index=True, default='ATIVO', max_length=20)),
                ('renovacoes', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_biblioteca', to='educacao.aluno')),
                ('devolucao_registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_biblioteca_devolvidos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_biblioteca_registrados', to=settings.AUTH_USER_MODEL)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='educacao.bibliotecaescolar')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='educacao.bibliotecaexemplar')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='educacao.bibliotecalivro')),
                ('matricula_institucional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_biblioteca', to='educacao.matriculainstitucional')),
            ],
            options={
                'verbose_name': 'Empréstimo da biblioteca',
                'verbose_name_plural': 'Empréstimos da biblioteca',
                'ordering': ['-data_emprestimo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_biblioteca', to='educacao.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_biblioteca_criados', to=settings.AUTH_USER_MODEL)),
                ('biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios', to='educacao.bibliotecaescolar')),
                ('matricula_institucional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_biblioteca', to='educacao.matriculainstitucional')),
            ],
            options={
                'verbose_name': 'Bloqueio de biblioteca',
                'verbose_name_plural': 'Bloqueios de biblioteca',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaInstitucionalHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('status_novo', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('TRANSFERIDA', 'Transferida'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueada')], db_index=True, max_length=20)),
                ('contexto', models.CharField(blank=True, default='', max_length=80)),
                ('motivo', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='educacao.matriculainstitucional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_institucionais_historico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da matrícula institucional',
                'verbose_name_plural': 'Históricos da matrícula institucional',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bibliotecaescolar',
            index=models.Index(fields=['unidade', 'status'], name='educacao_bi_unidade_ed7098_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaescolar',
            index=models.Index(fields=['codigo'], name='educacao_bi_codigo_e3db18_idx'),
        ),
        migrations.AddConstraint(
            model_name='bibliotecaescolar',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='uniq_biblioteca_por_unidade_nome'),
        ),
        migrations.AddIndex(
            model_name='bibliotecalivro',
            index=models.Index(fields=['biblioteca', 'status'], name='educacao_bi_bibliot_d6b8de_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecalivro',
            index=models.Index(fields=['titulo'], name='educacao_bi_titulo_edef9b_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecalivro',
            index=models.Index(fields=['autor'], name='educacao_bi_autor_6c4c89_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecalivro',
            index=models.Index(fields=['isbn'], name='educacao_bi_isbn_7b7e38_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaexemplar',
            index=models.Index(fields=['livro', 'status'], name='educacao_bi_livro_i_8e5f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaexemplar',
            index=models.Index(fields=['tombo'], name='educacao_bi_tombo_8b2e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaexemplar',
            index=models.Index(fields=['codigo_exemplar'], name='educacao_bi_codigo__83187b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bibliotecaexemplar',
            constraint=models.UniqueConstraint(fields=('livro', 'codigo_exemplar'), name='uniq_exemplar_por_livro_codigo'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucional',
            index=models.Index(fields=['numero_matricula'], name='educacao_ma_numero__7d4b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucional',
            index=models.Index(fields=['status'], name='educacao_ma_status_9c6693_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucional',
            index=models.Index(fields=['ano_referencia'], name='educacao_ma_ano_ref_7c5fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucional',
            index=models.Index(fields=['municipio', 'status'], name='educacao_ma_municip_60e478_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaemprestimo',
            index=models.Index(fields=['biblioteca', 'status'], name='educacao_bi_bibliot_47c10a_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaemprestimo',
            index=models.Index(fields=['aluno', 'status'], name='educacao_bi_aluno_i_cb14e1_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaemprestimo',
            index=models.Index(fields=['matricula_institucional', 'status'], name='educacao_bi_matricu_f548d9_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaemprestimo',
            index=models.Index(fields=['exemplar', 'status'], name='educacao_bi_exempla_e0c426_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaemprestimo',
            index=models.Index(fields=['data_prevista_devolucao', 'status'], name='educacao_bi_data_pr_c085b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecabloqueio',
            index=models.Index(fields=['aluno', 'status'], name='educacao_bi_aluno_i_479186_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecabloqueio',
            index=models.Index(fields=['matricula_institucional', 'status'], name='educacao_bi_matricu_6756ba_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecabloqueio',
            index=models.Index(fields=['biblioteca', 'status'], name='educacao_bi_bibliot_8e68b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecabloqueio',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='educacao_bi_data_in_19c3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucionalhistorico',
            index=models.Index(fields=['matricula_institucional', 'criado_em'], name='educacao_ma_matricu_c24e67_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucionalhistorico',
            index=models.Index(fields=['status_novo'], name='educacao_ma_status__b68c91_idx'),
        ),
        migrations.AddIndex(
            model_name='matriculainstitucionalhistorico',
            index=models.Index(fields=['contexto'], name='educacao_ma_context_d49ea7_idx'),
        ),
    ]
