# Generated by Django 5.2.12 on 2026-03-24 19:15

import apps.educacao.models_biblioteca
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0040_bibliotecaescolar_bibliotecalivro_bibliotecaexemplar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculainstitucional',
            name='ano_referencia',
            field=models.PositiveIntegerField(db_index=True, default=apps.educacao.models_biblioteca.current_year),
        ),
    ]
