# Generated by Django 5.2.12 on 2026-03-24 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0041_alter_matriculainstitucional_ano_referencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_expiracao', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_biblioteca', to='educacao.aluno')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='educacao.bibliotecaescolar')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_biblioteca_criadas', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='educacao.bibliotecaexemplar')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='educacao.bibliotecalivro')),
                ('matricula_institucional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_biblioteca', to='educacao.matriculainstitucional')),
            ],
            options={
                'verbose_name': 'Reserva da biblioteca',
                'verbose_name_plural': 'Reservas da biblioteca',
                'ordering': ['-data_reserva', '-id'],
                'indexes': [models.Index(fields=['biblioteca', 'status'], name='educacao_bi_bibliot_12a89f_idx'), models.Index(fields=['aluno', 'status'], name='educacao_bi_aluno_i_f8ef76_idx'), models.Index(fields=['livro', 'status'], name='educacao_bi_livro_i_708fe3_idx'), models.Index(fields=['exemplar', 'status'], name='educacao_bi_exempla_ea7b1e_idx'), models.Index(fields=['data_expiracao', 'status'], name='educacao_bi_data_ex_b0feb2_idx')],
            },
        ),
    ]
