# Generated by Django 5.2.12 on 2026-03-24 22:39

import apps.educacao.models_programas
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0042_bibliotecareserva'),
        ('org', '0015_unidade_tipo_educacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('INFORMATICA', 'Informática'), ('BALLET', 'Ballet'), ('REFORCO', 'Reforço'), ('OFICINA', 'Oficina'), ('PROJETO', 'Projeto'), ('ESPORTE', 'Esporte'), ('CULTURA', 'Cultura'), ('APOIO_PEDAGOGICO', 'Apoio pedagógico'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('objetivo', models.TextField(blank=True, default='')),
                ('publico_alvo', models.CharField(blank=True, default='', max_length=180)),
                ('faixa_etaria_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faixa_etaria_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exige_vinculo_escolar_ativo', models.BooleanField(default=True)),
                ('permite_multiplas_participacoes', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ENCERRADO', 'Encerrado')], db_index=True, default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('secretaria_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares', to='org.secretaria')),
                ('unidade_gestora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares_gestora', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Programa complementar',
                'verbose_name_plural': 'Programas complementares',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaComplementarOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(db_index=True, default=apps.educacao.models_programas._current_year)),
                ('codigo', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=180)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('FLEXIVEL', 'Flexível')], default='MANHA', max_length=15)),
                ('capacidade_maxima', models.PositiveSmallIntegerField(default=20)),
                ('idade_minima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idade_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PLANEJADA', max_length=20)),
                ('exige_vinculo_escolar_ativo', models.BooleanField(default=True)),
                ('permite_sobreposicao_horario', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('legacy_informatica_turma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_complementar_oferta', to='educacao.informaticaturma')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='educacao.programacomplementar')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_complementares_ofertas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares_ofertas', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Oferta do programa complementar',
                'verbose_name_plural': 'Ofertas dos programas complementares',
                'ordering': ['-ano_letivo', 'programa__nome', 'codigo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaComplementarHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('frequencia_tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ESPECIFICA', 'Data específica')], default='SEMANAL', max_length=20)),
                ('turno', models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('FLEXIVEL', 'Flexível')], default='', max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='educacao.programacomplementaroferta')),
            ],
            options={
                'verbose_name': 'Horário da oferta complementar',
                'verbose_name_plural': 'Horários das ofertas complementares',
                'ordering': ['dia_semana', 'hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaComplementarParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(db_index=True, default=apps.educacao.models_programas._current_year)),
                ('status', models.CharField(choices=[('PRE_INSCRITO', 'Pré-inscrito'), ('ATIVO', 'Ativo'), ('AGUARDANDO_VAGA', 'Aguardando vaga'), ('TRANSFERIDO', 'Transferido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('DESLIGADO', 'Desligado'), ('SUSPENSO', 'Suspenso')], db_index=True, default='ATIVO', max_length=20)),
                ('data_ingresso', models.DateField(default=django.utils.timezone.localdate)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('motivo_saida', models.TextField(blank=True, default='')),
                ('origem_vinculo', models.CharField(blank=True, default='MANUAL', max_length=80)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares_participacoes', to='educacao.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_complementares_participacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('escola_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares_participacoes_origem', to='org.unidade')),
                ('legacy_informatica_matricula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_complementar_participacao', to='educacao.informaticamatricula')),
                ('matricula_institucional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_complementares_participacoes', to='educacao.matriculainstitucional')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='educacao.programacomplementaroferta')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='educacao.programacomplementar')),
            ],
            options={
                'verbose_name': 'Participação em programa complementar',
                'verbose_name_plural': 'Participações em programas complementares',
                'ordering': ['-data_ingresso', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaComplementarFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status_presenca', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('REPOSICAO', 'Reposição'), ('ATRASO', 'Atraso')], default='PRESENTE', max_length=20)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_complementares_frequencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='educacao.programacomplementarparticipacao')),
            ],
            options={
                'verbose_name': 'Frequência em programa complementar',
                'verbose_name_plural': 'Frequências em programas complementares',
                'ordering': ['-data_aula', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaComplementarParticipacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('MUDANCA_STATUS', 'Mudança de status'), ('FREQUENCIA', 'Registro de frequência')], default='ATUALIZACAO', max_length=30)),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('status_novo', models.CharField(blank=True, default='', max_length=20)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_complementares_logs', to=settings.AUTH_USER_MODEL)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='educacao.programacomplementarparticipacao')),
            ],
            options={
                'verbose_name': 'Log de participação em programa complementar',
                'verbose_name_plural': 'Logs de participação em programas complementares',
                'ordering': ['-executado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='programacomplementar',
            index=models.Index(fields=['tipo', 'status'], name='educacao_pr_tipo_56fcde_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementar',
            index=models.Index(fields=['status'], name='educacao_pr_status_a31d17_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementar',
            index=models.Index(fields=['slug'], name='educacao_pr_slug_27a36a_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementaroferta',
            index=models.Index(fields=['programa', 'status'], name='educacao_pr_program_5c3dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementaroferta',
            index=models.Index(fields=['unidade', 'status'], name='educacao_pr_unidade_58d02a_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementaroferta',
            index=models.Index(fields=['ano_letivo', 'status'], name='educacao_pr_ano_let_fed2b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacomplementaroferta',
            constraint=models.UniqueConstraint(fields=('programa', 'codigo', 'ano_letivo'), name='uniq_prog_comp_oferta_codigo_ano'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarhorario',
            index=models.Index(fields=['oferta', 'ativo'], name='educacao_pr_oferta__adf7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarhorario',
            index=models.Index(fields=['dia_semana', 'hora_inicio', 'hora_fim'], name='educacao_pr_dia_sem_4109a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacomplementarhorario',
            constraint=models.UniqueConstraint(fields=('oferta', 'dia_semana', 'hora_inicio', 'hora_fim'), name='uniq_prog_comp_oferta_horario'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacao',
            index=models.Index(fields=['aluno', 'status'], name='educacao_pr_aluno_i_a7ee97_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacao',
            index=models.Index(fields=['programa', 'status'], name='educacao_pr_program_91fc59_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacao',
            index=models.Index(fields=['oferta', 'status'], name='educacao_pr_oferta__155b95_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacao',
            index=models.Index(fields=['matricula_institucional', 'status'], name='educacao_pr_matricu_132d25_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarfrequencia',
            index=models.Index(fields=['participacao', 'data_aula'], name='educacao_pr_partici_46c44a_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarfrequencia',
            index=models.Index(fields=['status_presenca'], name='educacao_pr_status__6d8632_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacomplementarfrequencia',
            constraint=models.UniqueConstraint(fields=('participacao', 'data_aula'), name='uniq_prog_comp_frequencia_por_dia'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacaolog',
            index=models.Index(fields=['participacao', 'executado_em'], name='educacao_pr_partici_55d1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='programacomplementarparticipacaolog',
            index=models.Index(fields=['acao'], name='educacao_pr_acao_df84ae_idx'),
        ),
    ]
