# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_cadastros_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_cadastros', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_cadastros', to='org.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_cadastros', to='org.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_cadastros', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Ponto cadastro',
                'verbose_name_plural': 'Ponto cadastros',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['municipio', 'status'], name='ponto_ponto_municip_b65a89_idx'), models.Index(fields=['codigo'], name='ponto_ponto_codigo_86333f_idx'), models.Index(fields=['nome'], name='ponto_ponto_nome_9cb4e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'codigo'), name='uniq_ponto_cadastro_municipio_codigo')],
            },
        ),
    ]
