# Generated by Django 5.2.11 on 2026-02-25 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        ('ponto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontocadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Escala e turno', 'verbose_name_plural': 'Escalas e turnos'},
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='carga_horaria_semanal',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='dias_semana',
            field=models.CharField(blank=True, default='SEG,TER,QUA,QUI,SEX', max_length=80),
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='tipo_turno',
            field=models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral'), ('PLANTAO', 'Plantão')], default='MATUTINO', max_length=20),
        ),
        migrations.AddField(
            model_name='pontocadastro',
            name='tolerancia_entrada_min',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='PontoVinculoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_vinculos_criados', to=settings.AUTH_USER_MODEL)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='ponto.pontocadastro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_vinculos', to='org.municipio')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_vinculos', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_vinculos', to='org.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponto_vinculos', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Vínculo de escala',
                'verbose_name_plural': 'Vínculos de escala',
                'ordering': ['-ativo', 'servidor__first_name', 'servidor__username'],
            },
        ),
        migrations.CreateModel(
            name='PontoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('tipo', models.CharField(choices=[('ATRASO', 'Atraso'), ('FALTA', 'Falta'), ('ABONO', 'Abono'), ('HORA_EXTRA', 'Hora extra'), ('AJUSTE', 'Ajuste manual')], default='ATRASO', max_length=20)),
                ('minutos', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_ocorrencias_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_ocorrencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_ocorrencias', to='org.municipio')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_ocorrencias', to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ponto.pontovinculoescala')),
            ],
            options={
                'verbose_name': 'Ocorrência de ponto',
                'verbose_name_plural': 'Ocorrências de ponto',
                'ordering': ['-data_ocorrencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PontoFechamentoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
                ('total_servidores', models.PositiveIntegerField(default=0)),
                ('total_ocorrencias', models.PositiveIntegerField(default=0)),
                ('total_pendentes', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, default='')),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_competencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_competencias_fechadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponto_competencias', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Fechamento de competência',
                'verbose_name_plural': 'Fechamentos de competência',
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['municipio', 'status'], name='ponto_ponto_municip_6210d9_idx'), models.Index(fields=['competencia'], name='ponto_ponto_compete_f153b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'competencia'), name='uniq_ponto_competencia_municipio')],
            },
        ),
        migrations.AddIndex(
            model_name='pontovinculoescala',
            index=models.Index(fields=['municipio', 'ativo'], name='ponto_ponto_municip_06b7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='pontovinculoescala',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='ponto_ponto_data_in_1e0ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoocorrencia',
            index=models.Index(fields=['municipio', 'competencia', 'status'], name='ponto_ponto_municip_4670c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoocorrencia',
            index=models.Index(fields=['servidor', 'data_ocorrencia'], name='ponto_ponto_servido_24fd39_idx'),
        ),
        migrations.AddIndex(
            model_name='pontoocorrencia',
            index=models.Index(fields=['tipo'], name='ponto_ponto_tipo_7b5097_idx'),
        ),
    ]
