# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0001_initial'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folhacadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Rubrica de folha', 'verbose_name_plural': 'Rubricas de folha'},
        ),
        migrations.AddField(
            model_name='folhacadastro',
            name='formula_calculo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folhacadastro',
            name='natureza',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=10),
        ),
        migrations.AddField(
            model_name='folhacadastro',
            name='tipo_evento',
            field=models.CharField(choices=[('PROVENTO', 'Provento'), ('DESCONTO', 'Desconto')], default='PROVENTO', max_length=12),
        ),
        migrations.AddField(
            model_name='folhacadastro',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FolhaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PROCESSADA', 'Processada'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=12)),
                ('total_colaboradores', models.PositiveIntegerField(default=0)),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fechamento_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_competencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('fechamento_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_competencias_fechadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folha_competencias', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Competência da folha',
                'verbose_name_plural': 'Competências da folha',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='FolhaIntegracaoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=12)),
                ('total_enviado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referencia_financeiro', models.CharField(blank=True, default='', max_length=60)),
                ('observacao', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracao_financeiro', to='folha.folhacompetencia')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_integracoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folha_integracoes_financeiro', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Integração folha-financeiro',
                'verbose_name_plural': 'Integrações folha-financeiro',
                'ordering': ['-competencia__competencia'],
            },
        ),
        migrations.CreateModel(
            name='FolhaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDADO', 'Validado'), ('ENVIADO_FINANCEIRO', 'Enviado ao financeiro')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='folha.folhacompetencia')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='folha.folhacadastro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folha_lancamentos', to='org.municipio')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folha_lancamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento de folha',
                'verbose_name_plural': 'Lançamentos de folha',
                'ordering': ['-competencia__competencia', 'servidor__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='folhacompetencia',
            index=models.Index(fields=['municipio', 'status'], name='folha_folha_municip_38fb03_idx'),
        ),
        migrations.AddIndex(
            model_name='folhacompetencia',
            index=models.Index(fields=['competencia'], name='folha_folha_compete_672206_idx'),
        ),
        migrations.AddConstraint(
            model_name='folhacompetencia',
            constraint=models.UniqueConstraint(fields=('municipio', 'competencia'), name='uniq_folha_competencia_municipio'),
        ),
        migrations.AddIndex(
            model_name='folhaintegracaofinanceiro',
            index=models.Index(fields=['municipio', 'status'], name='folha_folha_municip_90811d_idx'),
        ),
        migrations.AddIndex(
            model_name='folhalancamento',
            index=models.Index(fields=['municipio', 'status'], name='folha_folha_municip_41652f_idx'),
        ),
        migrations.AddIndex(
            model_name='folhalancamento',
            index=models.Index(fields=['competencia', 'servidor'], name='folha_folha_compete_64bf5a_idx'),
        ),
    ]
