# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=120)),
                ('assunto', models.CharField(max_length=180)),
                ('solicitante_nome', models.CharField(blank=True, default='', max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRAMITACAO', 'Em tramitacao'), ('CONCLUIDO', 'Concluido'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=16)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('prazo_final', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_admin', to='org.municipio')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_admin', to='org.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_admin', to='org.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_admin', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Processo administrativo',
                'verbose_name_plural': 'Processos administrativos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENCAMINHAMENTO', 'Encaminhamento'), ('DESPACHO', 'Despacho'), ('CIENCIA', 'Ciencia'), ('CONCLUSAO', 'Conclusao')], default='ENCAMINHAMENTO', max_length=16)),
                ('despacho', models.TextField(blank=True, default='')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('data_evento', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andamentos_processo_criados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='processos.processoadministrativo')),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_destino', to='org.setor')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_origem', to='org.setor')),
            ],
            options={
                'verbose_name': 'Andamento de processo',
                'verbose_name_plural': 'Andamentos de processo',
                'ordering': ['-data_evento', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='processoadministrativo',
            index=models.Index(fields=['municipio', 'status', 'data_abertura'], name='processos_p_municip_2044b7_idx'),
        ),
        migrations.AddIndex(
            model_name='processoadministrativo',
            index=models.Index(fields=['tipo'], name='processos_p_tipo_e6c156_idx'),
        ),
        migrations.AddIndex(
            model_name='processoadministrativo',
            index=models.Index(fields=['assunto'], name='processos_p_assunto_309c42_idx'),
        ),
        migrations.AddConstraint(
            model_name='processoadministrativo',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_processo_municipio_numero'),
        ),
        migrations.AddIndex(
            model_name='processoandamento',
            index=models.Index(fields=['processo', 'data_evento'], name='processos_p_process_0fc3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='processoandamento',
            index=models.Index(fields=['tipo'], name='processos_p_tipo_789850_idx'),
        ),
    ]
