# Generated by Django 5.2.11 on 2026-02-14 01:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('gerado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem_url', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-gerado_em'],
            },
        ),
    ]
