# Generated by Django 5.2.11 on 2026-02-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentoemitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Página Institucional', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('marca_nome', models.CharField(default='GEPUB', max_length=80)),
                ('marca_logo', models.ImageField(blank=True, null=True, upload_to='institutional/brand/')),
                ('nav_metodo_label', models.CharField(default='Método', max_length=30)),
                ('nav_planos_label', models.CharField(default='Planos', max_length=30)),
                ('nav_servicos_label', models.CharField(default='Serviços', max_length=30)),
                ('nav_simulador_label', models.CharField(default='Simulador', max_length=30)),
                ('botao_login_label', models.CharField(default='Entrar', max_length=40)),
                ('hero_kicker', models.CharField(default='UM SISTEMA SOB MEDIDA PARA PREFEITURAS', max_length=140)),
                ('hero_titulo', models.TextField(default='Elaboramos a estratégia digital da sua gestão para integrar secretarias, acelerar resultados e ampliar controle público.')),
                ('hero_descricao', models.TextField(default='O GEPUB conecta Educação, Saúde, NEE e estrutura administrativa em uma única plataforma SaaS, com onboarding automático, auditoria e gestão de planos por município.')),
                ('hero_cta_primario_label', models.CharField(default='SIMULAR PLANO', max_length=50)),
                ('hero_cta_primario_link', models.CharField(default='#simulador', max_length=120)),
                ('hero_cta_secundario_label', models.CharField(default='VER PLANOS', max_length=50)),
                ('hero_cta_secundario_link', models.CharField(default='#planos', max_length=120)),
                ('oferta_tag', models.CharField(default='ESTRUTURA PRONTA PARA LICITAÇÃO', max_length=140)),
                ('oferta_titulo', models.TextField(default='Essa pode ser a virada da sua gestão: um SaaS único para substituir contratos fragmentados e reduzir retrabalho entre secretarias.')),
                ('oferta_descricao', models.TextField(default='Contratação em formato público com licença SaaS, implantação, migração, treinamento, suporte e manutenção, com vigência mínima de 12 meses e reajuste anual INPC/IPCA.')),
                ('metodo_kicker', models.CharField(default='MÉTODO GEPUB', max_length=80)),
                ('metodo_titulo', models.TextField(default='Um único fluxo para implantar com governança e escalar com previsibilidade.')),
                ('metodo_cta_label', models.CharField(default='QUERO AVALIAR MEU MUNICÍPIO', max_length=50)),
                ('metodo_cta_link', models.CharField(default='#simulador', max_length=120)),
                ('planos_kicker', models.CharField(default='PLANOS MUNICIPAIS', max_length=80)),
                ('planos_titulo', models.TextField(default='O GEPUB respeita o porte do município e cresce conforme a operação.')),
                ('planos_descricao', models.TextField(default='Você contrata uma base mensal com limites objetivos e adicionais transparentes. Sem contrato confuso, sem variação imprevisível de custo.')),
                ('planos_cta_label', models.CharField(default='SIMULAR AGORA', max_length=50)),
                ('planos_cta_link', models.CharField(default='#simulador', max_length=120)),
                ('servicos_kicker', models.CharField(default='NOSSOS SERVIÇOS', max_length=80)),
                ('servicos_titulo', models.TextField(default='Tudo que entregamos para operação municipal de ponta a ponta.')),
                ('servicos_cta_label', models.CharField(default='FALE COM O TIME GEPUB', max_length=50)),
                ('servicos_cta_link', models.CharField(default='#simulador', max_length=120)),
                ('rodape_texto', models.CharField(default='© GEPUB • Gestão Estratégica Pública. Todos os direitos reservados.', max_length=220)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração institucional',
                'verbose_name_plural': 'Configurações institucionais',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalMethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True, default='')),
                ('icone', models.CharField(default='fa-solid fa-circle-check', max_length=80)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_passos', to='core.institutionalpageconfig')),
            ],
            options={
                'verbose_name': 'Passo do método',
                'verbose_name_plural': 'Passos do método',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('icone', models.CharField(default='fa-solid fa-square', max_length=80)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.institutionalpageconfig')),
            ],
            options={
                'verbose_name': 'Card de serviço',
                'verbose_name_plural': 'Cards de serviço',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='institutional/slides/')),
                ('icone', models.CharField(default='fa-solid fa-user-tie', max_length=80)),
                ('cta_label', models.CharField(blank=True, default='', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='', max_length=120)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.institutionalpageconfig')),
            ],
            options={
                'verbose_name': 'Slide institucional',
                'verbose_name_plural': 'Slides institucionais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
