# Generated by Django 5.2.11 on 2026-02-25 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_institutional_page'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('evento', models.CharField(max_length=80)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(max_length=40)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('depois', models.JSONField(blank=True, default=dict)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_eventos', to='org.municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'criado_em'], name='core_audito_municip_31c97e_idx'), models.Index(fields=['entidade', 'entidade_id'], name='core_audito_entidad_861bef_idx'), models.Index(fields=['evento', 'criado_em'], name='core_audito_evento_10bf1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransparenciaEventoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('PROCESSOS', 'Processos'), ('COMPRAS', 'Compras'), ('CONTRATOS', 'Contratos'), ('FINANCEIRO', 'Financeiro'), ('INTEGRACOES', 'Integracoes'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('tipo_evento', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True, default='')),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('publico', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transparencia_eventos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Evento de transparencia',
                'verbose_name_plural': 'Eventos de transparencia',
                'ordering': ['-data_evento', '-id'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'data_evento'], name='core_transp_municip_ffa71c_idx'), models.Index(fields=['tipo_evento', 'data_evento'], name='core_transp_tipo_ev_8a1c7d_idx'), models.Index(fields=['publico', 'data_evento'], name='core_transp_publico_4e0c75_idx')],
            },
        ),
    ]
