# Generated by Django 5.2.11 on 2026-02-26 02:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditoriaevento_transparenciaeventopublico'),
        ('org', '0008_municipio_slug_site_dominio_personalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcursoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('tipo', models.CharField(choices=[('CONCURSO', 'Concurso público'), ('SELETIVO', 'Processo seletivo'), ('CHAMAMENTO', 'Chamamento')], default='CONCURSO', max_length=20)),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('INSCRICOES_ABERTAS', 'Inscrições abertas'), ('EM_ANDAMENTO', 'Em andamento'), ('HOMOLOGADO', 'Homologado'), ('ENCERRADO', 'Encerrado')], default='PREVISTO', max_length=24)),
                ('descricao', models.TextField(blank=True, default='')),
                ('edital_arquivo', models.FileField(blank=True, null=True, upload_to='portal/concursos/editais/%Y/%m/')),
                ('inicio_inscricao', models.DateField(blank=True, null=True)),
                ('fim_inscricao', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos_publicos_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos_publicos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Concurso público',
                'verbose_name_plural': 'Concursos públicos',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConcursoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='portal/concursos/etapas/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.concursopublico')),
            ],
            options={
                'verbose_name': 'Etapa de concurso',
                'verbose_name_plural': 'Etapas de concurso',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiarioOficialEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('data_publicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('resumo', models.CharField(blank=True, default='', max_length=220)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='portal/diario_oficial/%Y/%m/')),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_oficiais_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_oficiais', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Edição do Diário Oficial',
                'verbose_name_plural': 'Edições do Diário Oficial',
                'ordering': ['-data_publicacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=220)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portal/banners/')),
                ('link', models.CharField(blank=True, default='', max_length=220)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_banners', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Banner do portal',
                'verbose_name_plural': 'Banners do portal',
                'ordering': ['ordem', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortalMunicipalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_portal', models.CharField(default='Portal Público Municipal', max_length=180)),
                ('subtitulo_portal', models.CharField(blank=True, default='', max_length=220)),
                ('mensagem_boas_vindas', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal/brand/')),
                ('brasao', models.ImageField(blank=True, null=True, upload_to='portal/brand/')),
                ('cor_primaria', models.CharField(default='#0E4A7E', max_length=9)),
                ('cor_secundaria', models.CharField(default='#2F6EA9', max_length=9)),
                ('endereco', models.CharField(blank=True, default='', max_length=220)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('horario_atendimento', models.CharField(blank=True, default='', max_length=120)),
                ('redes_sociais', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_config', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Configuração do portal municipal',
                'verbose_name_plural': 'Configurações do portal municipal',
                'ordering': ['municipio__nome'],
            },
        ),
        migrations.CreateModel(
            name='PortalNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, default='', max_length=240)),
                ('resumo', models.TextField(blank=True, default='')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(choices=[('GERAL', 'Geral'), ('PREFEITURA', 'Prefeitura'), ('TRANSPARENCIA', 'Transparência'), ('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('OUVIDORIA', 'Ouvidoria'), ('CAMARA', 'Câmara'), ('CONCURSOS', 'Concursos')], default='GERAL', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portal/noticias/')),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_noticias_publicadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_noticias', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Notícia do portal',
                'verbose_name_plural': 'Notícias do portal',
                'ordering': ['-publicado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CamaraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROJETO_LEI', 'Projeto de Lei'), ('REQUERIMENTO', 'Requerimento'), ('MOCACAO', 'Moção'), ('INDICACAO', 'Indicação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('numero', models.CharField(max_length=40)),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('ementa', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('EM_TRAMITE', 'Em trâmite'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('ARQUIVADO', 'Arquivado')], default='EM_TRAMITE', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='portal/camara/materias/%Y/%m/')),
                ('publicado', models.BooleanField(default=True)),
                ('data_publicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camara_materias', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Matéria da Câmara',
                'verbose_name_plural': 'Matérias da Câmara',
                'ordering': ['-data_publicacao', '-id'],
                'indexes': [models.Index(fields=['municipio', 'publicado', 'data_publicacao'], name='core_camara_municip_f507e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'tipo', 'numero', 'ano'), name='uniq_camara_materia_numero')],
            },
        ),
        migrations.CreateModel(
            name='CamaraSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('data_sessao', models.DateField(default=django.utils.timezone.localdate)),
                ('pauta', models.TextField(blank=True, default='')),
                ('ata_arquivo', models.FileField(blank=True, null=True, upload_to='portal/camara/sessoes/%Y/%m/')),
                ('video_url', models.URLField(blank=True, default='')),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camara_sessoes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Sessão da Câmara',
                'verbose_name_plural': 'Sessões da Câmara',
                'ordering': ['-data_sessao', '-id'],
                'indexes': [models.Index(fields=['municipio', 'publicado', 'data_sessao'], name='core_camara_municip_2409e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='concursopublico',
            index=models.Index(fields=['municipio', 'publicado', 'status'], name='core_concur_municip_4f5891_idx'),
        ),
        migrations.AddIndex(
            model_name='concursoetapa',
            index=models.Index(fields=['concurso', 'publicado', 'ordem'], name='core_concur_concurs_b0a50f_idx'),
        ),
        migrations.AddIndex(
            model_name='diariooficialedicao',
            index=models.Index(fields=['municipio', 'publicado', 'data_publicacao'], name='core_diario_municip_84b693_idx'),
        ),
        migrations.AddConstraint(
            model_name='diariooficialedicao',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_diario_oficial_municipio_numero'),
        ),
        migrations.AddIndex(
            model_name='portalbanner',
            index=models.Index(fields=['municipio', 'ativo', 'ordem'], name='core_portal_municip_8da549_idx'),
        ),
        migrations.AddIndex(
            model_name='portalnoticia',
            index=models.Index(fields=['municipio', 'publicado', 'publicado_em'], name='core_portal_municip_20f9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='portalnoticia',
            index=models.Index(fields=['categoria', 'publicado'], name='core_portal_categor_977479_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalnoticia',
            constraint=models.UniqueConstraint(fields=('municipio', 'slug'), name='uniq_portal_noticia_municipio_slug'),
        ),
    ]
