# Generated by Django 5.2.11 on 2026-02-26 02:30

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_concursopublico_concursoetapa_diariooficialedicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaramateria',
            name='ano',
            field=models.PositiveIntegerField(default=apps.core.models._current_year),
        ),
    ]
