# Generated by Django 5.2.11 on 2026-02-26 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_camaramateria_ano'),
        ('org', '0008_municipio_slug_site_dominio_personalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPaginaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, default='', max_length=220)),
                ('resumo', models.TextField(blank=True, default='')),
                ('conteudo', models.TextField(blank=True, default='')),
                ('mostrar_no_menu', models.BooleanField(default=False)),
                ('mostrar_no_rodape', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_paginas_criadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_paginas', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Página pública do portal',
                'verbose_name_plural': 'Páginas públicas do portal',
                'ordering': ['ordem', 'titulo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalMenuPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('tipo_destino', models.CharField(choices=[('INTERNO', 'Rota interna'), ('PAGINA', 'Página pública'), ('EXTERNO', 'Link externo')], default='INTERNO', max_length=10)),
                ('rota_interna', models.CharField(blank=True, choices=[('HOME', 'Início'), ('NOTICIAS', 'Notícias'), ('LICITACOES', 'Licitações'), ('CONTRATOS', 'Contratos'), ('TRANSPARENCIA', 'Transparência'), ('OUVIDORIA', 'e-SIC/Ouvidoria'), ('DIARIO', 'Diário Oficial'), ('CONCURSOS', 'Concursos'), ('CAMARA', 'Câmara'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação')], default='HOME', max_length=20)),
                ('url_externa', models.CharField(blank=True, default='', max_length=240)),
                ('abrir_em_nova_aba', models.BooleanField(default=False)),
                ('posicao', models.CharField(choices=[('HEADER', 'Menu superior'), ('FOOTER', 'Rodapé')], default='HEADER', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_menu_items', to='org.municipio')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.portalpaginapublica')),
            ],
            options={
                'verbose_name': 'Item de menu do portal',
                'verbose_name_plural': 'Itens de menu do portal',
                'ordering': ['posicao', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalHomeBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('icone', models.CharField(blank=True, default='fa-solid fa-circle-info', max_length=80)),
                ('link', models.CharField(blank=True, default='', max_length=240)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_home_blocos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Bloco da home do portal',
                'verbose_name_plural': 'Blocos da home do portal',
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['municipio', 'ativo', 'ordem'], name='core_portal_municip_744913_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='portalpaginapublica',
            index=models.Index(fields=['municipio', 'publicado', 'ordem'], name='core_portal_municip_512100_idx'),
        ),
        migrations.AddIndex(
            model_name='portalpaginapublica',
            index=models.Index(fields=['municipio', 'mostrar_no_menu', 'ordem'], name='core_portal_municip_db7a04_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalpaginapublica',
            constraint=models.UniqueConstraint(fields=('municipio', 'slug'), name='uniq_portal_pagina_municipio_slug'),
        ),
        migrations.AddIndex(
            model_name='portalmenupublico',
            index=models.Index(fields=['municipio', 'posicao', 'ativo', 'ordem'], name='core_portal_municip_9a740d_idx'),
        ),
    ]
