# Generated by Django 5.2.11 on 2026-02-26 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_portalpaginapublica_portalmenupublico_and_more'),
        ('org', '0008_municipio_slug_site_dominio_personalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTransparenciaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('OBRAS_PUBLICAS', 'Obras públicas'), ('OBRAS_PARALISADAS', 'Obras paralisadas'), ('MEDICAMENTOS', 'Medicamentos'), ('EDUCACAO_MATRICULAS', 'Educação • solicitações de matrícula'), ('EDUCACAO_ESPERA_CRECHE', 'Educação • lista de espera de creche'), ('EDUCACAO_LISTA_ALUNOS', 'Educação • lista de alunos'), ('DIARIAS_TABELA_VALORES', 'Diárias • tabela de valores'), ('DADOS_ABERTOS', 'Dados abertos'), ('PRESTACAO_CONTAS', 'Prestação de contas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=40)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True, default='')),
                ('competencia', models.CharField(blank=True, default='', help_text='Competência no formato AAAA-MM (opcional).', max_length=7)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('LINK', 'Link externo')], default='PDF', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='portal/transparencia/%Y/%m/')),
                ('link_externo', models.URLField(blank=True, default='')),
                ('publico', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transparencia_arquivos_publicados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transparencia_arquivos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Arquivo de transparência',
                'verbose_name_plural': 'Arquivos de transparência',
                'ordering': ['categoria', 'ordem', '-publicado_em', '-id'],
                'indexes': [models.Index(fields=['municipio', 'categoria', 'publico'], name='core_portal_municip_b05775_idx'), models.Index(fields=['municipio', 'publico', 'publicado_em'], name='core_portal_municip_56c6cd_idx'), models.Index(fields=['formato'], name='core_portal_formato_d1f77d_idx')],
            },
        ),
    ]
