# Generated by Django 5.2.11 on 2026-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_portaltransparenciaarquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaltransparenciaarquivo',
            name='categoria',
            field=models.CharField(choices=[('ATOS_NORMATIVOS', 'Atos normativos próprios'), ('DIARIO_OFICIAL', 'Diário oficial'), ('EXEC_ORC_GERAL_2025', 'Execução orçamentária geral 2025'), ('EXEC_ORC_2024', 'Execução orçamentária 2024'), ('EMPRESAS_DIVIDA_ATIVA', 'Empresas com dívida ativa'), ('EMENDAS_PARLAMENTARES', 'Emendas parlamentares'), ('CONVENIOS_RECEBIDOS', 'Convênios e transferências recebidas'), ('CONVENIOS_REALIZADOS', 'Convênios e transferências realizadas'), ('ACORDOS_SEM_TRANSFERENCIA', 'Acordos firmados sem transferências'), ('RH_FOLHA_PAGAMENTO', 'Recursos Humanos • Folha de pagamento'), ('RH_CARGOS', 'Recursos Humanos • Cargos'), ('RH_ESTAGIARIOS', 'Recursos Humanos • Estagiários'), ('RH_TERCEIRIZADOS', 'Recursos Humanos • Terceirizados'), ('RH_CONCURSOS', 'Recursos Humanos • Concursos'), ('RH_SERVIDORES', 'Recursos Humanos • Servidores'), ('DIARIAS', 'Diárias'), ('OBRAS_PUBLICAS', 'Obras públicas'), ('OBRAS_PARALISADAS', 'Obras paralisadas'), ('LICITACOES', 'Licitações'), ('CONTRATOS', 'Contratos'), ('ADITIVOS_CONTRATOS', 'Aditivos de contratos'), ('FISCAL_CONTRATOS', 'Fiscal de contratos'), ('LICITANTES_SANCIONADOS', 'Licitantes e/ou contratados sancionados'), ('EMPRESAS_INIDONEAS', 'Empresas inidôneas e suspensas'), ('PRESTACAO_CONTAS_ANTERIORES', 'Prestação de contas de anos anteriores'), ('BALANCO_GERAL', 'Prestação de contas • balanço geral'), ('RELATORIO_GESTAO_ATIVIDADE', 'Relatório de gestão ou atividade'), ('PARECER_PREVIO_TCE', 'Julgamento das contas pelo TCE • parecer prévio'), ('RESULTADO_JULGAMENTO_LEGISLATIVO', 'Resultado de julgamento das contas • legislativo'), ('RGF', 'Relatório de gestão fiscal (RGF)'), ('RREO', 'Relatório resumido de execução orçamentária (RREO)'), ('PEI', 'Plano estratégico institucional (PEI)'), ('PPA', 'Plano plurianual (PPA)'), ('LDO', 'Lei de diretrizes orçamentárias (LDO)'), ('LOA', 'Lei orçamentária anual (LOA)'), ('MEDICAMENTOS', 'Medicamentos'), ('EDUCACAO_MATRICULAS', 'Educação • solicitações de matrícula'), ('EDUCACAO_ESPERA_CRECHE', 'Educação • lista de espera de creche'), ('EDUCACAO_LISTA_ALUNOS', 'Educação • lista de alunos'), ('DIARIAS_TABELA_VALORES', 'Diárias • tabela de valores'), ('DADOS_ABERTOS', 'Dados abertos'), ('PRESTACAO_CONTAS', 'Prestação de contas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=40),
        ),
    ]
