# Generated by Django 5.2.11 on 2026-03-01 21:58

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_portaltransparenciaarquivo_categoria'),
        ('org', '0012_enable_comunicacao_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoRegistroAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, default='', max_length=40)),
                ('titulo', models.CharField(blank=True, default='', max_length=140)),
                ('observacao', models.CharField(blank=True, default='', max_length=220)),
                ('arquivo', models.FileField(upload_to=apps.core.models._registro_operacao_upload_to)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacao_registro_anexos', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_registro_anexos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Anexo de registro operacional',
                'verbose_name_plural': 'Anexos de registros operacionais',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'entidade', 'entidade_id', 'criado_em'], name='core_operac_municip_7756cd_idx'), models.Index(fields=['tipo', 'criado_em'], name='core_operac_tipo_e4b9aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperacaoRegistroComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(max_length=40)),
                ('comentario', models.TextField()),
                ('interno', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacao_registro_comentarios', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_registro_comentarios', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Comentário de registro operacional',
                'verbose_name_plural': 'Comentários de registros operacionais',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'entidade', 'entidade_id', 'criado_em'], name='core_operac_municip_f71aa1_idx'), models.Index(fields=['interno', 'criado_em'], name='core_operac_interno_51961f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperacaoRegistroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=40)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(max_length=40)),
                ('tag', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacao_registro_tags', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_registro_tags', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Tag de registro operacional',
                'verbose_name_plural': 'Tags de registros operacionais',
                'ordering': ['tag', '-criado_em'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'entidade', 'entidade_id'], name='core_operac_municip_7f5d72_idx'), models.Index(fields=['tag'], name='core_operac_tag_c6cec2_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'modulo', 'entidade', 'entidade_id', 'tag'), name='uniq_operacao_registro_tag')],
            },
        ),
    ]
