# Generated by Django 5.2.12 on 2026-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentoemitido_assinatura_emitente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalpageconfig',
            name='hero_cta_secundario_label',
            field=models.CharField(default='VISUALIZAR PLANOS', max_length=50),
        ),
    ]
