# Generated by Django 5.2.11 on 2026-02-25 15:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('data_empenho', models.DateField(default=django.utils.timezone.localdate)),
                ('fornecedor_nome', models.CharField(max_length=180)),
                ('fornecedor_documento', models.CharField(blank=True, default='', max_length=30)),
                ('objeto', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('ORDINARIO', 'Ordinário'), ('GLOBAL', 'Global'), ('ESTIMATIVO', 'Estimativo')], default='ORDINARIO', max_length=12)),
                ('valor_empenhado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('EMPENHADO', 'Empenhado'), ('LIQUIDADO', 'Liquidado'), ('PAGO', 'Pago')], default='EMPENHADO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empenhos_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desp_empenhos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Empenho',
                'verbose_name_plural': 'Empenhos',
                'ordering': ['-data_empenho', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DespLiquidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('data_liquidacao', models.DateField(default=django.utils.timezone.localdate)),
                ('documento_fiscal', models.CharField(blank=True, default='', max_length=60)),
                ('observacao', models.TextField(blank=True, default='')),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes', to='financeiro.despempenho')),
            ],
            options={
                'verbose_name': 'Liquidação',
                'verbose_name_plural': 'Liquidações',
                'ordering': ['-data_liquidacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('banco_nome', models.CharField(max_length=120)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('tipo_conta', models.CharField(choices=[('MOVIMENTO', 'Movimento'), ('VINCULADA', 'Vinculada'), ('APLICACAO', 'Aplicação')], default='MOVIMENTO', max_length=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_contas', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
                'ordering': ['banco_nome', 'agencia', 'conta'],
            },
        ),
        migrations.CreateModel(
            name='DespPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_pagamento', models.CharField(blank=True, default='', max_length=60)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ESTORNADO', 'Estornado')], default='PAGO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('liquidacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.despliquidacao')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.financeirocontabancaria')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=12)),
                ('inicio_em', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_em', models.DateField(blank=True, null=True)),
                ('fechamento_mensal_ate', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_exercicios', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Exercício financeiro',
                'verbose_name_plural': 'Exercícios financeiros',
                'ordering': ['-ano', '-id'],
            },
        ),
        migrations.AddField(
            model_name='despempenho',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='financeiro.financeiroexercicio'),
        ),
        migrations.CreateModel(
            name='FinanceiroLogEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=60)),
                ('entidade', models.CharField(max_length=60)),
                ('entidade_id', models.CharField(max_length=40)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('depois', models.JSONField(blank=True, default=dict)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_logs', to='org.municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log financeiro',
                'verbose_name_plural': 'Logs financeiros',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroUnidadeGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=180)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_ugs', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_ugs', to='org.secretaria')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_ugs', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Unidade gestora',
                'verbose_name_plural': 'Unidades gestoras',
                'ordering': ['codigo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='financeirocontabancaria',
            name='unidade_gestora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='financeiro.financeirounidadegestora'),
        ),
        migrations.AddField(
            model_name='despempenho',
            name='unidade_gestora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='financeiro.financeirounidadegestora'),
        ),
        migrations.CreateModel(
            name='OrcDotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_codigo', models.CharField(max_length=30)),
                ('programa_nome', models.CharField(max_length=180)),
                ('acao_codigo', models.CharField(max_length=30)),
                ('acao_nome', models.CharField(max_length=180)),
                ('elemento_despesa', models.CharField(max_length=30)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_atualizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_empenhado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='financeiro.financeiroexercicio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orc_dotacoes', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orc_dotacoes', to='org.secretaria')),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='financeiro.financeirounidadegestora')),
            ],
            options={
                'verbose_name': 'Dotação orçamentária',
                'verbose_name_plural': 'Dotações orçamentárias',
                'ordering': ['-exercicio__ano', 'programa_codigo', 'acao_codigo'],
            },
        ),
        migrations.AddField(
            model_name='despempenho',
            name='dotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='financeiro.orcdotacao'),
        ),
        migrations.CreateModel(
            name='OrcFonteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=180)),
                ('ativo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orc_fontes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Fonte de recurso',
                'verbose_name_plural': 'Fontes de recurso',
                'ordering': ['codigo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='orcdotacao',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes', to='financeiro.orcfonterecurso'),
        ),
        migrations.CreateModel(
            name='RecArrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arrecadacao', models.DateField(default=django.utils.timezone.localdate)),
                ('rubrica_codigo', models.CharField(max_length=30)),
                ('rubrica_nome', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('documento', models.CharField(blank=True, default='', max_length=60)),
                ('origem', models.CharField(blank=True, default='', max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrecadacoes', to='financeiro.financeirocontabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrecadacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrecadacoes', to='financeiro.financeiroexercicio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_arrecadacoes', to='org.municipio')),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrecadacoes', to='financeiro.financeirounidadegestora')),
            ],
            options={
                'verbose_name': 'Arrecadação',
                'verbose_name_plural': 'Arrecadações',
                'ordering': ['-data_arrecadacao', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='despliquidacao',
            constraint=models.UniqueConstraint(fields=('empenho', 'numero'), name='uniq_fin_liquidacao_empenho_numero'),
        ),
        migrations.AddIndex(
            model_name='financeiroexercicio',
            index=models.Index(fields=['municipio', 'ano'], name='financeiro__municip_350ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='financeiroexercicio',
            index=models.Index(fields=['status'], name='financeiro__status_0bf33f_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeiroexercicio',
            constraint=models.UniqueConstraint(fields=('municipio', 'ano'), name='uniq_fin_exercicio_municipio_ano'),
        ),
        migrations.AddIndex(
            model_name='financeirologevento',
            index=models.Index(fields=['municipio', 'evento', 'criado_em'], name='financeiro__municip_cbf4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='financeirologevento',
            index=models.Index(fields=['entidade', 'entidade_id'], name='financeiro__entidad_371148_idx'),
        ),
        migrations.AddIndex(
            model_name='financeirounidadegestora',
            index=models.Index(fields=['municipio', 'ativo'], name='financeiro__municip_565593_idx'),
        ),
        migrations.AddIndex(
            model_name='financeirounidadegestora',
            index=models.Index(fields=['codigo'], name='financeiro__codigo_af6318_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeirounidadegestora',
            constraint=models.UniqueConstraint(fields=('municipio', 'codigo'), name='uniq_fin_ug_municipio_codigo'),
        ),
        migrations.AddIndex(
            model_name='financeirocontabancaria',
            index=models.Index(fields=['municipio', 'ativo'], name='financeiro__municip_a10af3_idx'),
        ),
        migrations.AddIndex(
            model_name='financeirocontabancaria',
            index=models.Index(fields=['banco_codigo', 'agencia', 'conta'], name='financeiro__banco_c_e85871_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeirocontabancaria',
            constraint=models.UniqueConstraint(fields=('unidade_gestora', 'banco_codigo', 'agencia', 'conta'), name='uniq_fin_conta_ug_banco_agencia_conta'),
        ),
        migrations.AddIndex(
            model_name='despempenho',
            index=models.Index(fields=['municipio', 'exercicio'], name='financeiro__municip_fbaa41_idx'),
        ),
        migrations.AddIndex(
            model_name='despempenho',
            index=models.Index(fields=['status', 'data_empenho'], name='financeiro__status_ed738f_idx'),
        ),
        migrations.AddConstraint(
            model_name='despempenho',
            constraint=models.UniqueConstraint(fields=('exercicio', 'numero'), name='uniq_fin_empenho_exercicio_numero'),
        ),
        migrations.AddIndex(
            model_name='orcfonterecurso',
            index=models.Index(fields=['municipio', 'ativo'], name='financeiro__municip_b4cb52_idx'),
        ),
        migrations.AddConstraint(
            model_name='orcfonterecurso',
            constraint=models.UniqueConstraint(fields=('municipio', 'codigo'), name='uniq_fin_fonte_municipio_codigo'),
        ),
        migrations.AddIndex(
            model_name='orcdotacao',
            index=models.Index(fields=['municipio', 'exercicio'], name='financeiro__municip_167416_idx'),
        ),
        migrations.AddIndex(
            model_name='orcdotacao',
            index=models.Index(fields=['ativo'], name='financeiro__ativo_e74648_idx'),
        ),
        migrations.AddConstraint(
            model_name='orcdotacao',
            constraint=models.UniqueConstraint(fields=('exercicio', 'unidade_gestora', 'programa_codigo', 'acao_codigo', 'elemento_despesa', 'fonte'), name='uniq_fin_dotacao_chave_orc'),
        ),
        migrations.AddIndex(
            model_name='recarrecadacao',
            index=models.Index(fields=['municipio', 'exercicio', 'data_arrecadacao'], name='financeiro__municip_7e8e11_idx'),
        ),
    ]
