# Generated by Django 5.2.11 on 2026-02-25 16:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespRestosPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSADO', 'Processado'), ('NAO_PROCESSADO', 'Não processado')], default='PROCESSADO', max_length=20)),
                ('numero_inscricao', models.CharField(max_length=40)),
                ('data_inscricao', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_inscrito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PARCIAL', 'Pago parcialmente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restos_pagar_criados', to=settings.AUTH_USER_MODEL)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restos_pagar', to='financeiro.despempenho')),
                ('exercicio_inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restos_inscricao', to='financeiro.financeiroexercicio')),
                ('exercicio_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restos_origem', to='financeiro.financeiroexercicio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desp_restos_pagar', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Restos a pagar',
                'verbose_name_plural': 'Restos a pagar',
                'ordering': ['-data_inscricao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DespPagamentoResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_pagamento', models.CharField(blank=True, default='', max_length=60)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('ESTORNADO', 'Estornado')], default='PAGO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_restos', to='financeiro.financeirocontabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_restos_criados', to=settings.AUTH_USER_MODEL)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.desprestospagar')),
            ],
            options={
                'verbose_name': 'Pagamento de resto a pagar',
                'verbose_name_plural': 'Pagamentos de restos a pagar',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrcCreditoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPLEMENTAR', 'Suplementar'), ('ESPECIAL', 'Especial'), ('EXTRAORDINARIO', 'Extraordinário')], default='SUPLEMENTAR', max_length=16)),
                ('numero_ato', models.CharField(max_length=60)),
                ('data_ato', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('origem_recurso', models.CharField(blank=True, default='', max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_adicionais_criados', to=settings.AUTH_USER_MODEL)),
                ('dotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_adicionais', to='financeiro.orcdotacao')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_adicionais', to='financeiro.financeiroexercicio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orc_creditos_adicionais', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Crédito adicional',
                'verbose_name_plural': 'Créditos adicionais',
                'ordering': ['-data_ato', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='desprestospagar',
            index=models.Index(fields=['municipio', 'exercicio_inscricao', 'status'], name='financeiro__municip_d36f97_idx'),
        ),
        migrations.AddIndex(
            model_name='desprestospagar',
            index=models.Index(fields=['empenho', 'status'], name='financeiro__empenho_aac8c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='desprestospagar',
            constraint=models.UniqueConstraint(fields=('exercicio_inscricao', 'numero_inscricao'), name='uniq_fin_restos_exercicio_numero_inscricao'),
        ),
        migrations.AddIndex(
            model_name='desppagamentoresto',
            index=models.Index(fields=['status', 'data_pagamento'], name='financeiro__status_79221f_idx'),
        ),
        migrations.AddIndex(
            model_name='orccreditoadicional',
            index=models.Index(fields=['municipio', 'exercicio', 'data_ato'], name='financeiro__municip_fdd140_idx'),
        ),
        migrations.AddIndex(
            model_name='orccreditoadicional',
            index=models.Index(fields=['tipo', 'data_ato'], name='financeiro__tipo_c1df62_idx'),
        ),
    ]
