# Generated by Django 5.2.11 on 2026-02-25 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_desprestospagar_desppagamentoresto_and_more'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TesExtratoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('CSV', 'CSV'), ('OFX', 'OFX')], default='CSV', max_length=8)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROCESSADA', 'Processada'), ('FALHA', 'Falha')], default='PROCESSADA', max_length=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('total_creditos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_debitos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato_importacoes', to='financeiro.financeirocontabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_importados', to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato_importacoes', to='financeiro.financeiroexercicio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tes_extrato_importacoes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Importação de extrato',
                'verbose_name_plural': 'Importações de extrato',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TesExtratoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField()),
                ('documento', models.CharField(blank=True, default='', max_length=80)),
                ('historico', models.CharField(blank=True, default='', max_length=255)),
                ('identificador_externo', models.CharField(blank=True, default='', max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato_itens', to='financeiro.financeirocontabancaria')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.tesextratoimportacao')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tes_extrato_itens', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Item de extrato',
                'verbose_name_plural': 'Itens de extrato',
                'ordering': ['data_movimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecConciliacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('PAGAMENTO', 'Pagamento'), ('PAGAMENTO_RP', 'Pagamento RP'), ('AJUSTE', 'Ajuste manual')], max_length=16)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('conciliado_em', models.DateTimeField(auto_now_add=True)),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('desp_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='financeiro.desppagamento')),
                ('desp_pagamento_resto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='financeiro.desppagamentoresto')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='org.municipio')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='financeiro.recarrecadacao')),
                ('extrato_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacao', to='financeiro.tesextratoitem')),
            ],
            options={
                'verbose_name': 'Conciliação de extrato',
                'verbose_name_plural': 'Conciliações de extrato',
                'ordering': ['-conciliado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='tesextratoimportacao',
            index=models.Index(fields=['municipio', 'exercicio', 'criado_em'], name='financeiro__municip_361416_idx'),
        ),
        migrations.AddIndex(
            model_name='tesextratoimportacao',
            index=models.Index(fields=['conta_bancaria', 'status'], name='financeiro__conta_b_61890e_idx'),
        ),
        migrations.AddIndex(
            model_name='tesextratoitem',
            index=models.Index(fields=['importacao', 'data_movimento'], name='financeiro__importa_332617_idx'),
        ),
        migrations.AddIndex(
            model_name='tesextratoitem',
            index=models.Index(fields=['conta_bancaria', 'valor'], name='financeiro__conta_b_7a860a_idx'),
        ),
        migrations.AddIndex(
            model_name='tesextratoitem',
            index=models.Index(fields=['municipio', 'data_movimento'], name='financeiro__municip_dbfaab_idx'),
        ),
        migrations.AddIndex(
            model_name='recconciliacaoitem',
            index=models.Index(fields=['municipio', 'referencia_tipo', 'conciliado_em'], name='financeiro__municip_f5ea83_idx'),
        ),
    ]
