# Generated by Django 5.2.11 on 2026-02-26 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0009_enable_paineis_conversor_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCX_TO_PDF', 'DOCX -> PDF'), ('IMG_TO_PDF', 'Imagem -> PDF'), ('PDF_TO_IMAGES', 'PDF -> Imagens'), ('PDF_MERGE', 'Unir PDFs'), ('PDF_SPLIT', 'Separar PDF')], default='DOCX_TO_PDF', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=14)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='conversor/input/%Y/%m/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='conversor/output/%Y/%m/')),
                ('parametros_json', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True, default='')),
                ('tamanho_entrada', models.PositiveIntegerField(default=0)),
                ('tamanho_saida', models.PositiveIntegerField(default=0)),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversao_jobs_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversao_jobs', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversao_jobs', to='org.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversao_jobs', to='org.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversao_jobs', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Job de conversão',
                'verbose_name_plural': 'Jobs de conversão',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConversionJobInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='conversor/input/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='conversor.conversionjob')),
            ],
            options={
                'verbose_name': 'Arquivo adicional do job',
                'verbose_name_plural': 'Arquivos adicionais do job',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['municipio', 'status', 'criado_em'], name='conversor_c_municip_70d3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['tipo', 'status', 'criado_em'], name='conversor_c_tipo_c9ea03_idx'),
        ),
    ]
