# Generated by Django 5.2.11 on 2026-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='tipo',
            field=models.CharField(choices=[('DOCX_TO_PDF', 'DOCX -> PDF'), ('XLSX_TO_PDF', 'Excel -> PDF'), ('IMG_TO_PDF', 'Imagem -> PDF'), ('PDF_TO_IMAGES', 'PDF -> Imagens'), ('PDF_TO_TEXT', 'PDF -> Texto (TXT)'), ('PDF_MERGE', 'Unir PDFs'), ('PDF_SPLIT', 'Separar PDF')], default='DOCX_TO_PDF', max_length=20),
        ),
    ]
