# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectorIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('dominio', models.CharField(choices=[('FINANCEIRO', 'Financeiro'), ('EDUCACAO', 'Educacao'), ('SAUDE', 'Saude'), ('TRANSPARENCIA', 'Transparencia'), ('GOVBR', 'Gov.br'), ('SICONFI', 'SICONFI'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('tipo', models.CharField(choices=[('API', 'API'), ('ARQUIVO', 'Arquivo'), ('ETL', 'ETL')], default='API', max_length=12)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('credenciais', models.JSONField(blank=True, default=dict)),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conectores_integracao_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integracoes_conectores', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Conector de integracao',
                'verbose_name_plural': 'Conectores de integracao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IntegracaoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('IMPORTACAO', 'Importacao'), ('EXPORTACAO', 'Exportacao')], default='IMPORTACAO', max_length=12)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], default='SUCESSO', max_length=10)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('quantidade_registros', models.PositiveIntegerField(default=0)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('conector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='integracoes.conectorintegracao')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes_executadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integracoes_execucoes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Execucao de integracao',
                'verbose_name_plural': 'Execucoes de integracao',
                'ordering': ['-executado_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conectorintegracao',
            constraint=models.UniqueConstraint(fields=('municipio', 'nome'), name='uniq_integracao_conector_municipio_nome'),
        ),
        migrations.AddIndex(
            model_name='integracaoexecucao',
            index=models.Index(fields=['municipio', 'status', 'executado_em'], name='integracoes_municip_c1d077_idx'),
        ),
        migrations.AddIndex(
            model_name='integracaoexecucao',
            index=models.Index(fields=['conector', 'executado_em'], name='integracoes_conecto_d76b43_idx'),
        ),
    ]
