# Generated by Django 5.2.11 on 2026-02-26 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0009_enable_paineis_conversor_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tema', models.CharField(default='institucional', max_length=40)),
                ('layout_json', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_dashboards_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard BI',
                'verbose_name_plural': 'Dashboards BI',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('KPI', 'KPI'), ('LINHA', 'Série temporal'), ('BARRA', 'Barras'), ('TABELA', 'Tabela'), ('PIZZA', 'Pizza')], default='KPI', max_length=12)),
                ('titulo', models.CharField(max_length=140)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graficos', to='paineis.dashboard')),
            ],
            options={
                'verbose_name': 'Gráfico',
                'verbose_name_plural': 'Gráficos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('fonte', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (.xlsx)'), ('GOOGLE_SHEETS', 'Google Sheets'), ('PDF', 'PDF'), ('DOCX', 'Word (.docx)')], default='CSV', max_length=20)),
                ('visibilidade', models.CharField(choices=[('INTERNO', 'Interno'), ('PUBLICO', 'Público')], default='INTERNO', max_length=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('VALIDADO', 'Validado'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_datasets_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_datasets_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bi_datasets', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bi_datasets', to='org.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bi_datasets', to='org.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bi_datasets', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Dataset BI',
                'verbose_name_plural': 'Datasets BI',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='paineis.dataset'),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('fonte', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (.xlsx)'), ('GOOGLE_SHEETS', 'Google Sheets'), ('PDF', 'PDF'), ('DOCX', 'Word (.docx)')], default='CSV', max_length=20)),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to='paineis/original/%Y/%m/')),
                ('arquivo_tratado', models.FileField(blank=True, null=True, upload_to='paineis/tratado/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=14)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('profile_json', models.JSONField(blank=True, default=dict)),
                ('preview_json', models.JSONField(blank=True, default=list)),
                ('logs', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_versoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='paineis.dataset')),
            ],
            options={
                'verbose_name': 'Versão do dataset',
                'verbose_name_plural': 'Versões do dataset',
                'ordering': ['-numero', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('DATA', 'Data'), ('BOOLEANO', 'Booleano')], default='TEXTO', max_length=12)),
                ('papel', models.CharField(choices=[('DIMENSAO', 'Dimensão'), ('MEDIDA', 'Medida')], default='DIMENSAO', max_length=12)),
                ('sensivel', models.BooleanField(default=False)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('amostra', models.CharField(blank=True, default='', max_length=140)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='paineis.datasetversion')),
            ],
            options={
                'verbose_name': 'Coluna do dataset',
                'verbose_name_plural': 'Colunas do dataset',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('CSV', 'CSV'), ('ZIP', 'Pacote ZIP')], default='PDF', max_length=10)),
                ('filtros_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=14)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='paineis/exports/%Y/%m/')),
                ('log', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='paineis.dashboard')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='paineis.dataset')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_exports_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportação BI',
                'verbose_name_plural': 'Exportações BI',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=120)),
                ('parametros_json', models.JSONField(blank=True, default=dict)),
                ('resultado_json', models.JSONField(blank=True, default=dict)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_cache', to='paineis.dataset')),
            ],
            options={
                'verbose_name': 'Cache de consulta BI',
                'verbose_name_plural': 'Cache de consultas BI',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['municipio', 'status', 'criado_em'], name='paineis_dat_municip_bf0109_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['categoria'], name='paineis_dat_categor_709ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['visibilidade'], name='paineis_dat_visibil_11b4c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(fields=('dataset', 'nome'), name='uniq_bi_dataset_dashboard_nome'),
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['dataset', 'status', 'criado_em'], name='paineis_dat_dataset_05731b_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'numero'), name='uniq_bi_dataset_versao'),
        ),
        migrations.AddIndex(
            model_name='datasetcolumn',
            index=models.Index(fields=['versao', 'papel'], name='paineis_dat_versao__0a0e20_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetcolumn',
            index=models.Index(fields=['sensivel'], name='paineis_dat_sensive_c31c88_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetcolumn',
            constraint=models.UniqueConstraint(fields=('versao', 'nome'), name='uniq_bi_versao_coluna'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['dataset', 'status', 'criado_em'], name='paineis_exp_dataset_abfd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['formato', 'criado_em'], name='paineis_exp_formato_68a66e_idx'),
        ),
        migrations.AddConstraint(
            model_name='querycache',
            constraint=models.UniqueConstraint(fields=('dataset', 'chave'), name='uniq_bi_query_cache_chave'),
        ),
    ]
