# Generated by Django 5.2.11 on 2026-02-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacao', '0002_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNecessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Necessidade',
                'verbose_name_plural': 'Tipos de Necessidade',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='nee_tiponec_nome_e34a8e_idx'), models.Index(fields=['ativo'], name='nee_tiponec_ativo_583ce8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApoioMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AEE', 'AEE (Atendimento Educacional Especializado)'), ('CUIDADOR', 'Cuidador(a)'), ('INTERPRETE_LIBRAS', 'Intérprete de Libras'), ('PROFESSOR_APOIO', 'Professor de Apoio'), ('TRANSPORTE', 'Transporte Adaptado'), ('RECURSO', 'Recurso/Adaptação'), ('OUTRO', 'Outro')], max_length=30)),
                ('descricao', models.CharField(blank=True, default='', max_length=180)),
                ('carga_horaria_semanal', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoios', to='educacao.matricula')),
            ],
            options={
                'verbose_name': 'Apoio da Matrícula',
                'verbose_name_plural': 'Apoios da Matrícula',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tipo'], name='nee_apoioma_tipo_b51452_idx'), models.Index(fields=['ativo'], name='nee_apoioma_ativo_d87846_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlunoNecessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, default='', max_length=20, verbose_name='CID (opcional)')),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necessidades', to='educacao.aluno')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='nee.tiponecessidade')),
            ],
            options={
                'verbose_name': 'Necessidade do Aluno',
                'verbose_name_plural': 'Necessidades do Aluno',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['ativo'], name='nee_alunone_ativo_9df419_idx'), models.Index(fields=['cid'], name='nee_alunone_cid_5ce488_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'tipo'), name='uniq_tipo_por_aluno')],
            },
        ),
    ]
