# Generated by ChatGPT patch for GEPUB NEE Fase 2
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("educacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaudoNEE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(blank=True, default="", max_length=60, verbose_name="Número do laudo (opcional)")),
                ("emissor", models.CharField(blank=True, default="", max_length=120, verbose_name="Emissor/Profissional")),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("validade", models.DateField(blank=True, null=True, verbose_name="Validade (opcional)")),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="nee/laudos/")),
                ("observacao", models.TextField(blank=True, default="")),
                ("ativo", models.BooleanField(default=True)),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="laudos_nee", to="educacao.aluno")),
                ("tipo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="laudos", to="nee.tiponecessidade")),
            ],
            options={"ordering": ["-data_emissao", "-id"], "verbose_name": "Laudo NEE", "verbose_name_plural": "Laudos NEE"},
        ),
        migrations.CreateModel(
            name="RecursoNEE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("categoria", models.CharField(blank=True, default="", max_length=80)),
                ("descricao", models.TextField(blank=True, default="")),
                ("ativo", models.BooleanField(default=True)),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recursos_nee", to="educacao.aluno")),
            ],
            options={"ordering": ["nome"], "verbose_name": "Recurso/Adaptação", "verbose_name_plural": "Recursos/Adaptações"},
        ),
        migrations.CreateModel(
            name="AcompanhamentoNEE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField(default=datetime.date.today)),
                ("titulo", models.CharField(max_length=140)),
                ("descricao", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("ABERTO", "Aberto"), ("EM_ANDAMENTO", "Em andamento"), ("CONCLUIDO", "Concluído")], default="ABERTO", max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="acompanhamentos_nee", to="educacao.aluno")),
                ("necessidade", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="acompanhamentos", to="nee.alunonecessidade")),
                ("profissional", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="acompanhamentos_nee", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-data", "-id"], "verbose_name": "Acompanhamento NEE", "verbose_name_plural": "Acompanhamentos NEE"},
        ),
        migrations.AddIndex(model_name="laudonee", index=models.Index(fields=["ativo"], name="nee_laudonee_ativo_1a2b3c")),
        migrations.AddIndex(model_name="laudonee", index=models.Index(fields=["data_emissao"], name="nee_laudonee_data_9d8e7f")),
        migrations.AddIndex(model_name="recursonee", index=models.Index(fields=["ativo"], name="nee_recurso_ativo_11aa22")),
        migrations.AddIndex(model_name="recursonee", index=models.Index(fields=["nome"], name="nee_recurso_nome_33bb44")),
        migrations.AddIndex(model_name="acompanhamentonee", index=models.Index(fields=["data"], name="nee_acomp_data_55cc66")),
        migrations.AddIndex(model_name="acompanhamentonee", index=models.Index(fields=["status"], name="nee_acomp_status_77dd88")),
        migrations.AddIndex(model_name="acompanhamentonee", index=models.Index(fields=["ativo"], name="nee_acomp_ativo_99ee00")),
    ]
