# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0003_tesextratoimportacao_tesextratoitem_and_more'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=220)),
                ('unidade_medida', models.CharField(blank=True, default='UN', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Item da requisicao',
                'verbose_name_plural': 'Itens da requisicao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoLicitatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=40)),
                ('modalidade', models.CharField(choices=[('PREGAO', 'Pregao'), ('CONCORRENCIA', 'Concorrencia'), ('DISPENSA', 'Dispensa'), ('INEXIGIBILIDADE', 'Inexigibilidade')], max_length=20)),
                ('objeto', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('EM_CURSO', 'Em curso'), ('HOMOLOGADO', 'Homologado'), ('FRACASSADO', 'Fracassado'), ('REVOGADO', 'Revogado')], default='PLANEJAMENTO', max_length=16)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('vencedor_nome', models.CharField(blank=True, default='', max_length=180)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_licitacoes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Processo licitatorio',
                'verbose_name_plural': 'Processos licitatorios',
                'ordering': ['-data_abertura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('objeto', models.CharField(max_length=220)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('data_necessidade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em aprovacao'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('HOMOLOGADA', 'Homologada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=16)),
                ('fornecedor_nome', models.CharField(blank=True, default='', max_length=180)),
                ('fornecedor_documento', models.CharField(blank=True, default='', max_length=30)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('dotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_compra', to='financeiro.orcdotacao')),
                ('empenho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_compra', to='financeiro.despempenho')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_requisicoes', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Requisicao de compra',
                'verbose_name_plural': 'Requisicoes de compra',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
