# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('org', '0006_secretariamoduloativo'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_compra', to='processos.processoadministrativo'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_requisicoes', to='org.secretaria'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_requisicoes', to='org.setor'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_requisicoes', to='org.unidade'),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacoes', to='compras.requisicaocompra'),
        ),
        migrations.AddField(
            model_name='requisicaocompraitem',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.requisicaocompra'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['municipio', 'status', 'criado_em'], name='compras_req_municip_f430ac_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['objeto'], name='compras_req_objeto_629d2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaocompra',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_compra_req_municipio_numero'),
        ),
        migrations.AddConstraint(
            model_name='processolicitatorio',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero_processo'), name='uniq_compra_proc_municipio_numero'),
        ),
    ]
