# Generated by Django 5.2.11 on 2026-02-21 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0011_avaliacaonota_componentecurricular_notacurricular_and_more'),
        ('nee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_evento', models.CharField(choices=[('OBSERVACAO', 'Observação'), ('ATENDIMENTO', 'Atendimento'), ('EVOLUCAO', 'Evolução'), ('INTERVENCAO', 'Intervenção'), ('DOCUMENTO', 'Documento')], default='OBSERVACAO', max_length=20)),
                ('descricao', models.TextField()),
                ('visibilidade', models.CharField(choices=[('EQUIPE', 'Equipe (NEE/Saúde)'), ('GESTAO', 'Gestão (Secretaria/Unidade)')], default='EQUIPE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaudoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=80)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('validade', models.DateField(blank=True, null=True)),
                ('profissional', models.CharField(blank=True, default='', max_length=180)),
                ('documento', models.FileField(blank=True, null=True, upload_to='nee/laudos/')),
                ('texto', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecursoNEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_AVALIACAO', 'Em avaliação'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='alunonecessidade',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='apoiomatricula',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='tiponecessidade',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveConstraint(
            model_name='alunonecessidade',
            name='uniq_tipo_por_aluno',
        ),
        migrations.RemoveIndex(
            model_name='alunonecessidade',
            name='nee_alunone_ativo_9df419_idx',
        ),
        migrations.RemoveIndex(
            model_name='alunonecessidade',
            name='nee_alunone_cid_5ce488_idx',
        ),
        migrations.RemoveIndex(
            model_name='apoiomatricula',
            name='nee_apoioma_tipo_b51452_idx',
        ),
        migrations.AlterUniqueTogether(
            name='alunonecessidade',
            unique_together={('aluno', 'tipo')},
        ),
        migrations.RemoveField(
            model_name='apoiomatricula',
            name='carga_horaria_semanal',
        ),
        migrations.RemoveField(
            model_name='apoiomatricula',
            name='tipo',
        ),
        migrations.AddField(
            model_name='alunonecessidade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apoiomatricula',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apoiomatricula',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alunonecessidade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades_nee', to='educacao.aluno'),
        ),
        migrations.AlterField(
            model_name='apoiomatricula',
            name='descricao',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='apoiomatricula',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoios_nee', to='educacao.matricula'),
        ),
        migrations.AlterField(
            model_name='tiponecessidade',
            name='nome',
            field=models.CharField(max_length=140, unique=True),
        ),
        migrations.AddIndex(
            model_name='alunonecessidade',
            index=models.Index(fields=['aluno'], name='nee_alunone_aluno_i_e39e47_idx'),
        ),
        migrations.AddIndex(
            model_name='alunonecessidade',
            index=models.Index(fields=['tipo'], name='nee_alunone_tipo_id_6cc22a_idx'),
        ),
        migrations.AddField(
            model_name='acompanhamentonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos_nee', to='educacao.aluno'),
        ),
        migrations.AddField(
            model_name='acompanhamentonee',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acompanhamentos_nee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laudonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos_nee', to='educacao.aluno'),
        ),
        migrations.AddField(
            model_name='recursonee',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_nee', to='educacao.aluno'),
        ),
        migrations.RemoveField(
            model_name='alunonecessidade',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='alunonecessidade',
            name='cid',
        ),
        migrations.AddIndex(
            model_name='acompanhamentonee',
            index=models.Index(fields=['aluno'], name='nee_acompan_aluno_i_09f4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='acompanhamentonee',
            index=models.Index(fields=['data'], name='nee_acompan_data_b39d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='acompanhamentonee',
            index=models.Index(fields=['tipo_evento'], name='nee_acompan_tipo_ev_a54553_idx'),
        ),
        migrations.AddIndex(
            model_name='laudonee',
            index=models.Index(fields=['data_emissao'], name='nee_laudone_data_em_17d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='laudonee',
            index=models.Index(fields=['aluno'], name='nee_laudone_aluno_i_dead22_idx'),
        ),
        migrations.AddIndex(
            model_name='recursonee',
            index=models.Index(fields=['aluno'], name='nee_recurso_aluno_i_e9261e_idx'),
        ),
        migrations.AddIndex(
            model_name='recursonee',
            index=models.Index(fields=['status'], name='nee_recurso_status_6d057b_idx'),
        ),
    ]
