# Generated by Django 5.2.11 on 2026-02-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nee', '0004_alter_acompanhamentonee_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alunonecessidade',
            name='nee_alunone_aluno_i',
        ),
        migrations.RemoveIndex(
            model_name='alunonecessidade',
            name='nee_alunone_tipo_i',
        ),
        migrations.RemoveIndex(
            model_name='apoiomatricula',
            name='nee_apoiom_ativo_i',
        ),
        migrations.RenameIndex(
            model_name='alunonecessidade',
            new_name='nee_alunone_ativo_9df419_idx',
            old_name='nee_alunone_ativo_i',
        ),
        migrations.RenameIndex(
            model_name='apoiomatricula',
            new_name='nee_apoioma_tipo_b51452_idx',
            old_name='nee_apoiom_tipo_i',
        ),
    ]
