# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RhDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORTARIA', 'Portaria'), ('TERMO', 'Termo'), ('ATO', 'Ato'), ('NOMEACAO', 'Nomeação'), ('OUTRO', 'Outro')], default='PORTARIA', max_length=20)),
                ('numero', models.CharField(max_length=60)),
                ('data_documento', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='rh/documentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento funcional',
                'verbose_name_plural': 'Documentos funcionais',
                'ordering': ['-data_documento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RhMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMISSAO', 'Admissão'), ('LOTACAO', 'Mudança de lotação'), ('FERIAS', 'Férias'), ('AFASTAMENTO', 'Afastamento'), ('PROGRESSAO', 'Progressão'), ('DESLIGAMENTO', 'Desligamento')], default='LOTACAO', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimentação funcional',
                'verbose_name_plural': 'Movimentações funcionais',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='rhcadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Servidor funcional', 'verbose_name_plural': 'Servidores funcionais'},
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='funcao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='regime',
            field=models.CharField(choices=[('ESTATUTARIO', 'Estatutário'), ('CLT', 'CLT'), ('COMISSIONADO', 'Comissionado'), ('TEMPORARIO', 'Temporário')], default='ESTATUTARIO', max_length=20),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_cadastros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rhcadastro',
            name='situacao_funcional',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado'), ('CEDIDO', 'Cedido'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rhcadastro',
            index=models.Index(fields=['municipio', 'situacao_funcional'], name='rh_rhcadast_municip_470615_idx'),
        ),
        migrations.AddIndex(
            model_name='rhcadastro',
            index=models.Index(fields=['matricula'], name='rh_rhcadast_matricu_313f09_idx'),
        ),
        migrations.AddConstraint(
            model_name='rhcadastro',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula', ''), _negated=True), fields=('municipio', 'matricula'), name='uniq_rh_matricula_municipio'),
        ),
        migrations.AddField(
            model_name='rhdocumento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_documentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rhdocumento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rh_documentos', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='rhdocumento',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rh.rhcadastro'),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_movimentacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_movimentacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rh_movimentacoes', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='secretaria_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rh_movimentacoes_destino', to='org.secretaria'),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='rh.rhcadastro'),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='setor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rh_movimentacoes_destino', to='org.setor'),
        ),
        migrations.AddField(
            model_name='rhmovimentacao',
            name='unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rh_movimentacoes_destino', to='org.unidade'),
        ),
        migrations.AddIndex(
            model_name='rhdocumento',
            index=models.Index(fields=['municipio', 'tipo', 'data_documento'], name='rh_rhdocume_municip_4604e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='rhdocumento',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_rh_documento_municipio_numero'),
        ),
        migrations.AddIndex(
            model_name='rhmovimentacao',
            index=models.Index(fields=['municipio', 'status', 'tipo'], name='rh_rhmovime_municip_1ad20e_idx'),
        ),
        migrations.AddIndex(
            model_name='rhmovimentacao',
            index=models.Index(fields=['servidor', 'data_inicio'], name='rh_rhmovime_servido_bf7f10_idx'),
        ),
    ]
