# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almoxarifadocadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Item de estoque', 'verbose_name_plural': 'Itens de estoque'},
        ),
        migrations.AddField(
            model_name='almoxarifadocadastro',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='almoxarifadocadastro',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='almoxarifadocadastro',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilo'), ('LT', 'Litro'), ('MT', 'Metro')], default='UN', max_length=4),
        ),
        migrations.AddField(
            model_name='almoxarifadocadastro',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='AlmoxarifadoMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], default='ENTRADA', max_length=10)),
                ('data_movimento', models.DateField(default=django.utils.timezone.localdate)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('documento', models.CharField(blank=True, default='', max_length=60)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado_movimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='almoxarifado.almoxarifadocadastro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_movimentos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'ordering': ['-data_movimento', '-id'],
                'indexes': [models.Index(fields=['municipio', 'tipo'], name='almoxarifad_municip_b60cb6_idx'), models.Index(fields=['item', 'data_movimento'], name='almoxarifad_item_id_071624_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlmoxarifadoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado_requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado_requisicoes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almoxarifado_requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='almoxarifado.almoxarifadocadastro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_requisicoes', to='org.municipio')),
                ('secretaria_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_requisicoes', to='org.secretaria')),
                ('setor_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_requisicoes', to='org.setor')),
                ('unidade_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_requisicoes', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Requisição de almoxarifado',
                'verbose_name_plural': 'Requisições de almoxarifado',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['municipio', 'status'], name='almoxarifad_municip_710afd_idx'), models.Index(fields=['item', 'status'], name='almoxarifad_item_id_b9aa9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_almoxarifado_req_municipio_numero')],
            },
        ),
    ]
