# Generated by Django 5.2.12 on 2026-03-21 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_alter_almoxarifadocadastro_options_and_more'),
        ('org', '0016_localestrutural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='almoxarifadocadastro',
            name='local_estrutural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_cadastros', to='org.localestrutural'),
        ),
        migrations.AddField(
            model_name='almoxarifadorequisicao',
            name='local_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_requisicoes_legado', to='org.localestrutural'),
        ),
        migrations.CreateModel(
            name='AlmoxarifadoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(blank=True, default='ALMOXARIFADO', max_length=60)),
                ('responsavel', models.CharField(blank=True, default='', max_length=180)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local_estrutural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_locais', to='org.localestrutural')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_locais', to='org.municipio')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_locais', to='org.secretaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_locais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Local de almoxarifado',
                'verbose_name_plural': 'Locais de almoxarifado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilo'), ('LT', 'Litro'), ('MT', 'Metro'), ('PCT', 'Pacote')], default='UN', max_length=4)),
                ('codigo_interno', models.CharField(max_length=40)),
                ('sku', models.CharField(blank=True, default='', max_length=80)),
                ('controla_lote', models.BooleanField(default=False)),
                ('controla_validade', models.BooleanField(default=False)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_produtos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Produto de estoque',
                'verbose_name_plural': 'Produtos de estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução'), ('PERDA', 'Perda')], default='ENTRADA', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, default='', max_length=220)),
                ('documento_referencia', models.CharField(blank=True, default='', max_length=80)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('almoxarifado_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='almoxarifado.almoxarifadolocal')),
                ('almoxarifado_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='almoxarifado.almoxarifadolocal')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_movimentacoes', to='org.municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_movimentacoes', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='almoxarifado.produtoestoque')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-data_movimentacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_reservada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('almoxarifado_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='almoxarifado.almoxarifadolocal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='almoxarifado.produtoestoque')),
            ],
            options={
                'verbose_name': 'Saldo de estoque',
                'verbose_name_plural': 'Saldos de estoque',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('APROVADA', 'Aprovada'), ('PARCIAL', 'Parcialmente atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('RECUSADA', 'Recusada')], default='RASCUNHO', max_length=12)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('local_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoque_requisicoes_solicitadas', to='org.localestrutural')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_requisicoes', to='org.municipio')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='almoxarifado.produtoestoque')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_requisicoes', to='org.secretaria')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_requisicoes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('unidade_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_requisicoes_solicitadas', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Requisição de estoque',
                'verbose_name_plural': 'Requisições de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='almoxarifadolocal',
            index=models.Index(fields=['municipio', 'secretaria', 'unidade'], name='almoxarifad_municip_cccc44_idx'),
        ),
        migrations.AddIndex(
            model_name='almoxarifadolocal',
            index=models.Index(fields=['ativo'], name='almoxarifad_ativo_c97c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='almoxarifadolocal',
            index=models.Index(fields=['nome'], name='almoxarifad_nome_779acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='almoxarifadolocal',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='uniq_almox_local_unidade_nome'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['municipio', 'ativo'], name='almoxarifad_municip_fa74f6_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['nome'], name='almoxarifad_nome_9b4798_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['categoria'], name='almoxarifad_categor_146325_idx'),
        ),
        migrations.AddConstraint(
            model_name='produtoestoque',
            constraint=models.UniqueConstraint(fields=('municipio', 'codigo_interno'), name='uniq_produto_estoque_municipio_codigo'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['municipio', 'tipo_movimentacao'], name='almoxarifad_municip_f4e811_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', 'data_movimentacao'], name='almoxarifad_produto_aafad9_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquesaldo',
            index=models.Index(fields=['produto', 'almoxarifado_local'], name='almoxarifad_produto_1afbad_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquesaldo',
            index=models.Index(fields=['quantidade_disponivel'], name='almoxarifad_quantid_1497e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoquesaldo',
            constraint=models.UniqueConstraint(fields=('produto', 'almoxarifado_local'), name='uniq_estoque_saldo_produto_local'),
        ),
        migrations.AddIndex(
            model_name='requisicaoestoque',
            index=models.Index(fields=['municipio', 'status'], name='almoxarifad_municip_9e00f3_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoestoque',
            index=models.Index(fields=['secretaria', 'unidade_solicitante'], name='almoxarifad_secreta_250788_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaoestoque',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_requisicao_estoque_municipio_numero'),
        ),
    ]
