# Generated by Django 5.2.11 on 2026-02-18 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_unidade_cnpj_unidade_email_unidade_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_inep',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Código INEP'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='org.secretaria'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('AGRICULTURA', 'Agricultura'), ('INFRAESTRUTURA', 'Infraestrutura'), ('ASSISTENCIA', 'Assistência Social'), ('OUTROS', 'Outros')], default='EDUCACAO', max_length=20),
        ),
    ]
