# Generated by Django 5.2.11 on 2026-02-25 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_unidade_cnpj_alter_unidade_codigo_inep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True, default='')),
                ('modulo', models.CharField(choices=[('educacao', 'Educação'), ('saude', 'Saúde/Clínico'), ('obras', 'Obras/Engenharia'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criar_unidade_base', models.BooleanField(default=True)),
                ('nome_unidade_base', models.CharField(default='Sede Administrativa', max_length=140)),
                ('tipo_unidade_base', models.CharField(choices=[('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('AGRICULTURA', 'Agricultura'), ('INFRAESTRUTURA', 'Infraestrutura'), ('ASSISTENCIA', 'Assistência Social'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('perfis_padrao', models.JSONField(blank=True, default=list)),
                ('onboarding_padrao', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de secretaria',
                'verbose_name_plural': 'Templates de secretaria',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['slug'], name='org_secreta_slug_a91b23_idx'), models.Index(fields=['modulo', 'ativo'], name='org_secreta_modulo_833453_idx')],
            },
        ),
        migrations.CreateModel(
            name='MunicipioModuloAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_ativos', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Módulo ativo do município',
                'verbose_name_plural': 'Módulos ativos do município',
                'indexes': [models.Index(fields=['modulo', 'ativo'], name='org_municip_modulo_e6e284_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'modulo'), name='uniq_municipio_modulo_ativo')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('url_name', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='org.secretaria')),
            ],
            options={
                'verbose_name': 'Passo de onboarding',
                'verbose_name_plural': 'Passos de onboarding',
                'ordering': ['modulo', 'ordem', 'id'],
                'indexes': [models.Index(fields=['municipio', 'modulo', 'status'], name='org_onboard_municip_babe37_idx'), models.Index(fields=['secretaria', 'status'], name='org_onboard_secreta_59f1d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'secretaria', 'modulo', 'codigo'), name='uniq_onboarding_step_scope')],
            },
        ),
        migrations.CreateModel(
            name='SecretariaProvisionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em processamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisionamentos_secretarias', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisionamentos', to='org.secretaria')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisionamentos_secretarias_solicitados', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisionamentos', to='org.secretariatemplate')),
            ],
            options={
                'verbose_name': 'Provisionamento de secretaria',
                'verbose_name_plural': 'Provisionamentos de secretaria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='org_secreta_status_e967e4_idx'), models.Index(fields=['municipio', 'template'], name='org_secreta_municip_23b400_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecretariaTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SETOR', 'Setor padrão'), ('UNIDADE', 'Unidade padrão'), ('CARGO', 'Cargo/Função padrão')], default='SETOR', max_length=20)),
                ('nome', models.CharField(max_length=140)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='org.secretariatemplate')),
            ],
            options={
                'verbose_name': 'Item do template de secretaria',
                'verbose_name_plural': 'Itens do template de secretaria',
                'ordering': ['template__nome', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='org_secreta_tipo_e3870f_idx')],
                'constraints': [models.UniqueConstraint(fields=('template', 'tipo', 'nome'), name='uniq_item_template_tipo_nome')],
            },
        ),
    ]
