# Generated by Django 5.2.11 on 2026-02-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_secretariatemplate_municipiomoduloativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariaModuloAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_ativos', to='org.secretaria')),
            ],
            options={
                'verbose_name': 'Módulo ativo da secretaria',
                'verbose_name_plural': 'Módulos ativos da secretaria',
                'indexes': [models.Index(fields=['modulo', 'ativo'], name='org_secreta_modulo_85603e_idx')],
                'constraints': [models.UniqueConstraint(fields=('secretaria', 'modulo'), name='uniq_secretaria_modulo_ativo')],
            },
        ),
    ]
