# Generated by Django 5.2.11 on 2026-02-25 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariaCadastroBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='GERAL', max_length=60)),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('nome', models.CharField(max_length=180)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastro-base da secretaria',
                'verbose_name_plural': 'Cadastros-base da secretaria',
                'ordering': ['secretaria__nome', 'categoria', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SecretariaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, default='', max_length=220)),
                ('valor', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da secretaria',
                'verbose_name_plural': 'Configurações da secretaria',
                'ordering': ['secretaria__nome', 'chave'],
            },
        ),
        migrations.AddField(
            model_name='secretaria',
            name='tipo_modelo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='secretariatemplate',
            name='cadastros_base_padrao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='secretariatemplate',
            name='configuracoes_padrao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='secretariatemplate',
            name='modulos_ativos_padrao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='secretariatemplate',
            name='modulo',
            field=models.CharField(choices=[('educacao', 'Educação'), ('saude', 'Saúde/Clínico'), ('obras', 'Obras/Engenharia'), ('administracao', 'Administração'), ('financas', 'Finanças/Fazenda'), ('planejamento', 'Planejamento/Controle Interno'), ('agricultura', 'Agricultura'), ('tecnologia', 'Tecnologia/Inovação'), ('assistencia', 'Assistência Social'), ('meio_ambiente', 'Meio Ambiente'), ('transporte', 'Transporte/Mobilidade'), ('cultura', 'Cultura/Turismo/Esporte'), ('desenvolvimento', 'Desenvolvimento Econômico'), ('habitacao', 'Habitação/Urbanismo'), ('servicos_publicos', 'Serviços Públicos'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='secretariatemplate',
            name='tipo_unidade_base',
            field=models.CharField(choices=[('ADMINISTRACAO', 'Administração'), ('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('AGRICULTURA', 'Agricultura'), ('FINANCAS', 'Finanças/Fazenda'), ('PLANEJAMENTO', 'Planejamento/Controle'), ('TECNOLOGIA', 'Tecnologia/Inovação'), ('MEIO_AMBIENTE', 'Meio Ambiente'), ('TRANSPORTE', 'Transporte/Mobilidade'), ('CULTURA', 'Cultura/Turismo/Esporte'), ('DESENVOLVIMENTO', 'Desenvolvimento Econômico'), ('HABITACAO', 'Habitação/Urbanismo'), ('SERVICOS_PUBLICOS', 'Serviços Públicos'), ('INFRAESTRUTURA', 'Infraestrutura'), ('ASSISTENCIA', 'Assistência Social'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRACAO', 'Administração'), ('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('AGRICULTURA', 'Agricultura'), ('FINANCAS', 'Finanças/Fazenda'), ('PLANEJAMENTO', 'Planejamento/Controle'), ('TECNOLOGIA', 'Tecnologia/Inovação'), ('MEIO_AMBIENTE', 'Meio Ambiente'), ('TRANSPORTE', 'Transporte/Mobilidade'), ('CULTURA', 'Cultura/Turismo/Esporte'), ('DESENVOLVIMENTO', 'Desenvolvimento Econômico'), ('HABITACAO', 'Habitação/Urbanismo'), ('SERVICOS_PUBLICOS', 'Serviços Públicos'), ('INFRAESTRUTURA', 'Infraestrutura'), ('ASSISTENCIA', 'Assistência Social'), ('OUTROS', 'Outros')], default='EDUCACAO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['tipo_modelo'], name='org_secreta_tipo_mo_0cbce2_idx'),
        ),
        migrations.AddField(
            model_name='secretariacadastrobase',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_base', to='org.secretaria'),
        ),
        migrations.AddField(
            model_name='secretariaconfiguracao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaria_configuracoes_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretariaconfiguracao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='org.secretaria'),
        ),
        migrations.AddIndex(
            model_name='secretariacadastrobase',
            index=models.Index(fields=['categoria', 'ativo'], name='org_secreta_categor_89d5bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='secretariacadastrobase',
            constraint=models.UniqueConstraint(fields=('secretaria', 'categoria', 'nome'), name='uniq_secretaria_cadastro_base'),
        ),
        migrations.AddIndex(
            model_name='secretariaconfiguracao',
            index=models.Index(fields=['chave'], name='org_secreta_chave_400441_idx'),
        ),
        migrations.AddConstraint(
            model_name='secretariaconfiguracao',
            constraint=models.UniqueConstraint(fields=('secretaria', 'chave'), name='uniq_secretaria_config_chave'),
        ),
    ]
