# Generated by Django 5.2.11 on 2026-03-01 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_enable_avaliacoes_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('SECRETARIA', 'Secretaria'), ('UNIDADE', 'Unidade'), ('SETOR', 'Setor'), ('GARAGEM', 'Garagem'), ('ESCOLA', 'Escola'), ('UBS', 'UBS'), ('ALMOXARIFADO', 'Almoxarifado'), ('OUTROS', 'Outros')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='Principal', max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('logradouro', models.CharField(blank=True, default='', max_length=180)),
                ('numero', models.CharField(blank=True, default='', max_length=30)),
                ('complemento', models.CharField(blank=True, default='', max_length=120)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('pais', models.CharField(blank=True, default='BR', max_length=2)),
                ('reference_point', models.CharField(blank=True, default='', max_length=220)),
                ('coverage_area', models.CharField(blank=True, default='', max_length=220)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geocode_provider', models.CharField(choices=[('google', 'Google'), ('osm', 'OpenStreetMap'), ('manual', 'Manual'), ('none', 'Não definido')], default='none', max_length=20)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pendente'), ('ok', 'OK'), ('failed', 'Falhou'), ('manual', 'Manual')], default='pending', max_length=20)),
                ('maps_url', models.URLField(blank=True, default='', max_length=520)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_addresses_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_addresses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['entity_type', 'entity_id', '-is_primary', 'id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'is_active'], name='org_address_entity__2489bb_idx'), models.Index(fields=['entity_type', 'entity_id', 'is_primary'], name='org_address_entity__770482_idx'), models.Index(fields=['is_public', 'is_active'], name='org_address_is_publ_e9dacb_idx'), models.Index(fields=['geocode_status'], name='org_address_geocode_1101a2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('entity_type', 'entity_id', 'is_primary'), name='uniq_primary_active_address_per_entity')],
            },
        ),
    ]
