# Generated by Django 5.2.11 on 2026-03-02 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_enable_comunicacao_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioOnboardingWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('total_steps', models.PositiveSmallIntegerField(default=9)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_wizards', to='org.municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_wizard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de onboarding municipal',
                'verbose_name_plural': 'Sessões de onboarding municipal',
                'indexes': [models.Index(fields=['municipio', 'completed_at'], name='org_municip_municip_9d1067_idx'), models.Index(fields=['current_step'], name='org_municip_current_1221a9_idx')],
            },
        ),
    ]
