# Generated by Django 5.2.11 on 2026-03-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_municipioonboardingwizard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(choices=[('kassya', 'Kassya'), ('inclusao', 'Inclusão'), ('institucional', 'Institucional')], default='kassya', max_length=30)),
                ('lock_theme_for_users', models.BooleanField(default=False)),
                ('allow_user_theme_override', models.BooleanField(default=True)),
                ('token_overrides', models.JSONField(blank=True, default=dict, help_text="Override de tokens CSS por tenant. Ex.: {'--gp-primary': '#0055aa'}")),
                ('ds_version', models.CharField(default='GEPUB DS v2.0', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='org.municipio')),
            ],
            options={
                'verbose_name': 'Configuração de tema do município',
                'verbose_name_plural': 'Configurações de tema dos municípios',
                'ordering': ['municipio__nome'],
            },
        ),
    ]
