# Generated by Codex on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0014_municipiothemeconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidade",
            name="tipo_educacional",
            field=models.CharField(
                choices=[
                    ("NAO_APLICA", "Não se aplica"),
                    ("ESCOLA", "Escola"),
                    ("CRECHE", "Creche"),
                    ("CMEI", "CMEI"),
                    ("LABORATORIO", "Sala/Laboratório"),
                    ("BIBLIOTECA", "Biblioteca Escolar"),
                    ("POLO", "Polo educacional"),
                    ("OUTRA", "Outra unidade educacional"),
                ],
                db_index=True,
                default="NAO_APLICA",
                max_length=20,
                verbose_name="Identificação educacional",
            ),
        ),
    ]
