# Generated by Django 5.2.12 on 2026-03-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_unidade_tipo_educacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstrutural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo_local', models.CharField(choices=[('SETOR', 'Setor'), ('SALA', 'Sala'), ('LABORATORIO', 'Laboratório'), ('DEPOSITO', 'Depósito'), ('ALMOXARIFADO', 'Almoxarifado interno'), ('SECRETARIA', 'Secretaria interna'), ('COORDENACAO', 'Coordenação'), ('CONSULTORIO', 'Consultório'), ('RECEPCAO', 'Recepção'), ('BLOCO', 'Bloco'), ('OUTRO', 'Outro')], default='SETOR', max_length=30)),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('responsavel', models.CharField(blank=True, default='', max_length=180)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('legacy_setor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_estrutural', to='org.setor')),
                ('local_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='org.localestrutural')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_estruturais', to='org.municipio')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_estruturais', to='org.secretaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_estruturais', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Local estrutural',
                'verbose_name_plural': 'Locais estruturais',
                'ordering': ['unidade__nome', 'nome'],
                'indexes': [models.Index(fields=['municipio', 'secretaria', 'unidade'], name='org_locales_municip_1c6263_idx'), models.Index(fields=['tipo_local', 'status'], name='org_locales_tipo_lo_c858ec_idx'), models.Index(fields=['nome'], name='org_locales_nome_6f0fca_idx'), models.Index(fields=['codigo'], name='org_locales_codigo_eb5d41_idx'), models.Index(fields=['local_pai'], name='org_locales_local_p_cf90c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('unidade', 'local_pai', 'nome'), name='uniq_local_estrutural_unidade_pai_nome'), models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('municipio', 'codigo'), name='uniq_local_estrutural_codigo_municipio')],
            },
        ),
    ]
