# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrotaAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateField(default=django.utils.timezone.localdate)),
                ('litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quilometragem', models.PositiveIntegerField(default=0)),
                ('posto', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FrotaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], default='PREVENTIVA', max_length=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=12)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('oficina', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manutenção de veículo',
                'verbose_name_plural': 'Manutenções de veículo',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FrotaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=180)),
                ('finalidade', models.TextField(blank=True, default='')),
                ('data_saida', models.DateField(default=django.utils.timezone.localdate)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('km_saida', models.PositiveIntegerField(default=0)),
                ('km_retorno', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='frotacadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Veículo da frota', 'verbose_name_plural': 'Veículos da frota'},
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('ETANOL', 'Etanol'), ('FLEX', 'Flex'), ('ELETRICO', 'Elétrico')], default='FLEX', max_length=12),
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='marca_modelo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='placa',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='quilometragem_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frotacadastro',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em manutenção'), ('INDISPONIVEL', 'Indisponível'), ('BAIXADO', 'Baixado')], default='DISPONIVEL', max_length=15),
        ),
        migrations.AddIndex(
            model_name='frotacadastro',
            index=models.Index(fields=['municipio', 'situacao'], name='frota_frota_municip_864003_idx'),
        ),
        migrations.AddIndex(
            model_name='frotacadastro',
            index=models.Index(fields=['placa'], name='frota_frota_placa_bbd708_idx'),
        ),
        migrations.AddConstraint(
            model_name='frotacadastro',
            constraint=models.UniqueConstraint(condition=models.Q(('placa', ''), _negated=True), fields=('municipio', 'placa'), name='uniq_frota_placa_municipio'),
        ),
        migrations.AddField(
            model_name='frotaabastecimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frota_abastecimentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frotaabastecimento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frota_abastecimentos', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='frotaabastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='frota.frotacadastro'),
        ),
        migrations.AddField(
            model_name='frotamanutencao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frota_manutencoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frotamanutencao',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frota_manutencoes', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='frotamanutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.frotacadastro'),
        ),
        migrations.AddField(
            model_name='frotaviagem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frota_viagens_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frotaviagem',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frota_viagens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frotaviagem',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frota_viagens', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='frotaviagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='frota.frotacadastro'),
        ),
        migrations.AddIndex(
            model_name='frotaabastecimento',
            index=models.Index(fields=['municipio', 'data_abastecimento'], name='frota_frota_municip_40ea1d_idx'),
        ),
        migrations.AddIndex(
            model_name='frotaabastecimento',
            index=models.Index(fields=['veiculo', 'data_abastecimento'], name='frota_frota_veiculo_64028c_idx'),
        ),
        migrations.AddIndex(
            model_name='frotamanutencao',
            index=models.Index(fields=['municipio', 'status'], name='frota_frota_municip_d493d0_idx'),
        ),
        migrations.AddIndex(
            model_name='frotamanutencao',
            index=models.Index(fields=['veiculo', 'status'], name='frota_frota_veiculo_59d75b_idx'),
        ),
        migrations.AddIndex(
            model_name='frotaviagem',
            index=models.Index(fields=['municipio', 'status'], name='frota_frota_municip_45b4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='frotaviagem',
            index=models.Index(fields=['veiculo', 'status'], name='frota_frota_veiculo_9fec17_idx'),
        ),
    ]
