from django.urls import path
from . import views
from . import views_codes

app_name = "core"

urlpatterns = [
    path("institucional/", views.institucional_public, name="institucional_public"),
    path("paginas/<slug:slug>/", views.portal_pagina_public, name="portal_pagina_public"),
    path("noticias/", views.portal_noticias_public, name="portal_noticias_public"),
    path("noticias/<slug:slug>/", views.portal_noticia_detail_public, name="portal_noticia_detail_public"),
    path("esic-ouvidoria/", views.portal_ouvidoria_public, name="portal_ouvidoria_public"),
    path("licitacoes/", views.portal_licitacoes_public, name="portal_licitacoes_public"),
    # Evita colisao com o app administrativo "contratos" em /contratos/.
    path("contratos-publicos/", views.portal_contratos_public, name="portal_contratos_public"),
    path("diario-oficial/", views.portal_diario_public, name="portal_diario_public"),
    path("concursos/", views.portal_concursos_public, name="portal_concursos_public"),
    path("camara/", views.portal_camara_public, name="portal_camara_public"),
    path("saude-publica/", views.portal_saude_public, name="portal_saude_public"),
    path("educacao-publica/", views.portal_educacao_public, name="portal_educacao_public"),
    path("sobre/", views.sobre_public, name="sobre_public"),
    path("funcionalidades/", views.funcionalidades_public, name="funcionalidades_public"),
    path("por-que-usar/", views.por_que_usar_public, name="por_que_usar_public"),
    path("documentacao/", views.documentacao_public, name="documentacao_public"),
    path("transparencia/", views.transparencia_public, name="transparencia_public"),
    path("", views.institucional_public, name="home"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("sistema/institucional/", views.institutional_admin, name="institutional_admin"),
    path("sistema/institucional/slides/novo/", views.institutional_slide_create, name="institutional_slide_create"),
    path("sistema/institucional/slides/<int:pk>/editar/", views.institutional_slide_update, name="institutional_slide_update"),
    path("sistema/institucional/slides/<int:pk>/remover/", views.institutional_slide_delete, name="institutional_slide_delete"),
    path("sistema/institucional/metodo/novo/", views.institutional_method_step_create, name="institutional_method_step_create"),
    path("sistema/institucional/metodo/<int:pk>/editar/", views.institutional_method_step_update, name="institutional_method_step_update"),
    path("sistema/institucional/metodo/<int:pk>/remover/", views.institutional_method_step_delete, name="institutional_method_step_delete"),
    path("sistema/institucional/servicos/novo/", views.institutional_service_card_create, name="institutional_service_card_create"),
    path("sistema/institucional/servicos/<int:pk>/editar/", views.institutional_service_card_update, name="institutional_service_card_update"),
    path("sistema/institucional/servicos/<int:pk>/remover/", views.institutional_service_card_delete, name="institutional_service_card_delete"),
    path("sistema/publicacoes/", views.publicacoes_admin, name="publicacoes_admin"),
    path("sistema/publicacoes/config/", views.publicacoes_config_edit, name="publicacoes_config_edit"),
    path("sistema/publicacoes/noticias/nova/", views.noticia_create, name="noticia_create"),
    path("sistema/publicacoes/noticias/<int:pk>/editar/", views.noticia_update, name="noticia_update"),
    path("sistema/publicacoes/noticias/<int:pk>/remover/", views.noticia_delete, name="noticia_delete"),
    path("sistema/publicacoes/banners/novo/", views.banner_create, name="banner_create"),
    path("sistema/publicacoes/banners/<int:pk>/editar/", views.banner_update, name="banner_update"),
    path("sistema/publicacoes/banners/<int:pk>/remover/", views.banner_delete, name="banner_delete"),
    path("sistema/publicacoes/paginas/nova/", views.pagina_create, name="pagina_create"),
    path("sistema/publicacoes/paginas/<int:pk>/editar/", views.pagina_update, name="pagina_update"),
    path("sistema/publicacoes/paginas/<int:pk>/remover/", views.pagina_delete, name="pagina_delete"),
    path("sistema/publicacoes/menus/novo/", views.menu_create, name="menu_create"),
    path("sistema/publicacoes/menus/<int:pk>/editar/", views.menu_update, name="menu_update"),
    path("sistema/publicacoes/menus/<int:pk>/remover/", views.menu_delete, name="menu_delete"),
    path("sistema/publicacoes/home-blocos/novo/", views.home_bloco_create, name="home_bloco_create"),
    path("sistema/publicacoes/home-blocos/<int:pk>/editar/", views.home_bloco_update, name="home_bloco_update"),
    path("sistema/publicacoes/home-blocos/<int:pk>/remover/", views.home_bloco_delete, name="home_bloco_delete"),
    path("sistema/publicacoes/transparencia/arquivos/novo/", views.transparencia_arquivo_create, name="transparencia_arquivo_create"),
    path("sistema/publicacoes/transparencia/arquivos/<int:pk>/editar/", views.transparencia_arquivo_update, name="transparencia_arquivo_update"),
    path("sistema/publicacoes/transparencia/arquivos/<int:pk>/remover/", views.transparencia_arquivo_delete, name="transparencia_arquivo_delete"),
    path("sistema/publicacoes/diario/novo/", views.diario_create, name="diario_create"),
    path("sistema/publicacoes/diario/<int:pk>/editar/", views.diario_update, name="diario_update"),
    path("sistema/publicacoes/diario/<int:pk>/remover/", views.diario_delete, name="diario_delete"),
    path("sistema/publicacoes/concursos/novo/", views.concurso_create, name="concurso_create"),
    path("sistema/publicacoes/concursos/<int:pk>/editar/", views.concurso_update, name="concurso_update"),
    path("sistema/publicacoes/concursos/<int:pk>/remover/", views.concurso_delete, name="concurso_delete"),
    path("sistema/publicacoes/concursos/<int:concurso_pk>/etapas/nova/", views.concurso_etapa_create, name="concurso_etapa_create"),
    path("sistema/publicacoes/concursos/etapas/<int:pk>/remover/", views.concurso_etapa_delete, name="concurso_etapa_delete"),
    path("sistema/publicacoes/camara/materias/nova/", views.camara_materia_create, name="camara_materia_create"),
    path("sistema/publicacoes/camara/materias/<int:pk>/editar/", views.camara_materia_update, name="camara_materia_update"),
    path("sistema/publicacoes/camara/materias/<int:pk>/remover/", views.camara_materia_delete, name="camara_materia_delete"),
    path("sistema/publicacoes/camara/sessoes/nova/", views.camara_sessao_create, name="camara_sessao_create"),
    path("sistema/publicacoes/camara/sessoes/<int:pk>/editar/", views.camara_sessao_update, name="camara_sessao_update"),
    path("sistema/publicacoes/camara/sessoes/<int:pk>/remover/", views.camara_sessao_delete, name="camara_sessao_delete"),

    path("aluno/", views.dashboard_view, name="dashboard_aluno"),

    path("avisos/novo/", views.aviso_create, name="aviso_create"),
    path("arquivos/novo/", views.arquivo_create, name="arquivo_create"),

    # ✅ atalhos por código (novo)
    path("go/", views_codes.go_code, name="go_code"),
    path("go/<str:codigo>/", views_codes.go_code, name="go_code_path"),
    path("guia/", views_codes.guia_telas, name="guia_telas"),


    # path("validar/<uuid:codigo>/", views.validar_documento, name="validar_documento"),
]
