# Generated by Django 5.2.11 on 2026-03-01 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacao', '0021_carteiraestudantil'),
        ('org', '0012_enable_comunicacao_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('to_name', models.CharField(blank=True, default='', max_length=140)),
                ('destination', models.CharField(max_length=180)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('subject_rendered', models.CharField(blank=True, default='', max_length=220)),
                ('body_rendered', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('FALHA', 'Falha'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('priority', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('NORMAL', 'Normal'), ('BAIXA', 'Baixa')], db_index=True, default='NORMAL', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('fallback_channels', models.JSONField(blank=True, default=list)),
                ('fallback_index', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('entity_module', models.CharField(blank=True, default='', max_length=40)),
                ('entity_type', models.CharField(blank=True, default='', max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=60)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_jobs', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_jobs', to='org.secretaria')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_jobs', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Job de notificação',
                'verbose_name_plural': 'Jobs de notificação',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('FALHA', 'Falha'), ('CANCELADO', 'Cancelado')], db_index=True, max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('destination', models.CharField(blank=True, default='', max_length=180)),
                ('subject', models.CharField(blank=True, default='', max_length=220)),
                ('body', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comunicacao.notificationjob')),
            ],
            options={
                'verbose_name': 'Log de notificação',
                'verbose_name_plural': 'Logs de notificação',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, default='', max_length=140)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('opt_out', models.BooleanField(default=False)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='educacao.aluno')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_preferences_updated', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_preferences', to='org.municipio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('MUNICIPIO', 'Município'), ('SECRETARIA', 'Secretaria'), ('UNIDADE', 'Unidade')], default='MUNICIPIO', max_length=20)),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('nome', models.CharField(max_length=140)),
                ('subject', models.CharField(blank=True, default='', max_length=220)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('nee_safe', models.BooleanField(default=False, help_text='Quando ativo, indica template neutro para comunicações sensíveis.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_updated', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='org.secretaria')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Template de notificação',
                'verbose_name_plural': 'Templates de notificação',
                'ordering': ['event_key', 'channel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('TWILIO', 'Twilio'), ('ZENVIA', 'Zenvia'), ('META', 'Meta Cloud API'), ('MOCK', 'Mock interno'), ('OUTRO', 'Outro')], default='MOCK', max_length=20)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('sender_identifier', models.CharField(blank=True, default='', help_text='E-mail remetente ou número/identificador do canal.', max_length=180)),
                ('credentials_json', models.JSONField(blank=True, default=dict)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('prioridade', models.PositiveSmallIntegerField(default=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels_updated', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_channels', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_channels', to='org.secretaria')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_channels', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Canal de comunicação',
                'verbose_name_plural': 'Canais de comunicação',
                'ordering': ['municipio__nome', 'channel', 'prioridade', 'id'],
                'indexes': [models.Index(fields=['municipio', 'channel', 'is_active'], name='comunicacao_municip_a02855_idx'), models.Index(fields=['secretaria', 'channel', 'is_active'], name='comunicacao_secreta_c44b3b_idx'), models.Index(fields=['unidade', 'channel', 'is_active'], name='comunicacao_unidade_79ac9d_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipio', 'secretaria', 'unidade', 'channel', 'provider'), name='uniq_notification_channel_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['municipio', 'status', 'scheduled_at'], name='comunicacao_municip_f63d09_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['channel', 'status', 'scheduled_at'], name='comunicacao_channel_55bfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['event_key', 'created_at'], name='comunicacao_event_k_4f95e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['entity_module', 'entity_type', 'entity_id'], name='comunicacao_entity__6d69ff_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='comunicacao_channel_1bdcb3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['provider', 'created_at'], name='comunicacao_provide_6073f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['municipio', 'opt_out'], name='comunicacao_municip_4904a6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'municipio'], name='comunicacao_user_id_b3df98_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['aluno', 'municipio'], name='comunicacao_aluno_i_c394f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('municipio', 'user', 'aluno', 'email', 'telefone', 'whatsapp'), name='uniq_notification_preference_identity'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['municipio', 'event_key', 'channel', 'is_active'], name='comunicacao_municip_3d7182_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['secretaria', 'event_key', 'channel', 'is_active'], name='comunicacao_secreta_02ffb8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['unidade', 'event_key', 'channel', 'is_active'], name='comunicacao_unidade_ef4c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('municipio', 'secretaria', 'unidade', 'event_key', 'channel', 'nome'), name='uniq_notification_template_scope_event'),
        ),
    ]
