# Generated by Django 5.2.12 on 2026-03-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0001_initial'),
        ('org', '0015_unidade_tipo_educacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='', max_length=140)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('sending_domain', models.CharField(blank=True, default='', max_length=180)),
                ('default_email_provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SES', 'Amazon SES'), ('POSTMARK', 'Postmark'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('TWILIO', 'Twilio'), ('ZENVIA', 'Zenvia'), ('META', 'Meta Cloud API'), ('MOCK', 'Mock interno'), ('OUTRO', 'Outro')], default='SMTP', max_length=20)),
                ('default_whatsapp_provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SES', 'Amazon SES'), ('POSTMARK', 'Postmark'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('TWILIO', 'Twilio'), ('ZENVIA', 'Zenvia'), ('META', 'Meta Cloud API'), ('MOCK', 'Mock interno'), ('OUTRO', 'Outro')], default='TWILIO', max_length=20)),
                ('support_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('dns_spf_ok', models.BooleanField(default=False)),
                ('dns_dkim_ok', models.BooleanField(default=False)),
                ('dns_dmarc_ok', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('last_validation_status', models.CharField(choices=[('NAO_TESTADO', 'Não testado'), ('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], default='NAO_TESTADO', max_length=20)),
                ('last_validation_message', models.TextField(blank=True, default='')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('wizard_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de comunicação da prefeitura',
                'verbose_name_plural': 'Configurações de comunicação das prefeituras',
                'ordering': ['municipio__nome'],
            },
        ),
        migrations.CreateModel(
            name='NotificationWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SES', 'Amazon SES'), ('POSTMARK', 'Postmark'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('TWILIO', 'Twilio'), ('ZENVIA', 'Zenvia'), ('META', 'Meta Cloud API'), ('MOCK', 'Mock interno'), ('OUTRO', 'Outro')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('external_event_id', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('channel', models.CharField(blank=True, choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='', max_length=20)),
                ('destination', models.CharField(blank=True, default='', max_length=180)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado'), ('ERRO', 'Erro')], db_index=True, default='RECEBIDO', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de webhook de comunicação',
                'verbose_name_plural': 'Eventos de webhook de comunicação',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='notificationchannelconfig',
            name='credentials_encrypted',
            field=models.TextField(blank=True, default='', help_text='Credenciais cifradas em repouso para este canal.'),
        ),
        migrations.AddField(
            model_name='notificationchannelconfig',
            name='last_test_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationchannelconfig',
            name='last_test_status',
            field=models.CharField(choices=[('NAO_TESTADO', 'Não testado'), ('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], default='NAO_TESTADO', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationchannelconfig',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='correlation_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='message_kind',
            field=models.CharField(choices=[('TRANSACIONAL', 'Transacional'), ('CAMPANHA', 'Campanha'), ('INTERNA', 'Interna')], db_index=True, default='TRANSACIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationchannelconfig',
            name='credentials_json',
            field=models.JSONField(blank=True, default=dict, help_text='Legado. Novas credenciais são persistidas em credentials_encrypted.'),
        ),
        migrations.AlterField(
            model_name='notificationchannelconfig',
            name='provider',
            field=models.CharField(choices=[('SMTP', 'SMTP'), ('SES', 'Amazon SES'), ('POSTMARK', 'Postmark'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('TWILIO', 'Twilio'), ('ZENVIA', 'Zenvia'), ('META', 'Meta Cloud API'), ('MOCK', 'Mock interno'), ('OUTRO', 'Outro')], default='MOCK', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['municipio', 'message_kind', 'status'], name='comunicacao_municip_05215f_idx'),
        ),
        migrations.AddField(
            model_name='notificationtenantsettings',
            name='municipio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='org.municipio'),
        ),
        migrations.AddField(
            model_name='notificationtenantsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_settings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationwebhookevent',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_webhook_events', to='org.municipio'),
        ),
        migrations.AddIndex(
            model_name='notificationtenantsettings',
            index=models.Index(fields=['default_email_provider', 'is_active'], name='comunicacao_default_2df271_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtenantsettings',
            index=models.Index(fields=['default_whatsapp_provider', 'is_active'], name='comunicacao_default_0b99f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwebhookevent',
            index=models.Index(fields=['provider', 'received_at'], name='comunicacao_provide_bf9007_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwebhookevent',
            index=models.Index(fields=['processing_status', 'received_at'], name='comunicacao_process_d65aba_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwebhookevent',
            index=models.Index(fields=['municipio', 'received_at'], name='comunicacao_municip_8bbb8c_idx'),
        ),
    ]
