# Generated by Django 5.2.11 on 2026-02-26 23:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educacao', '0021_carteiraestudantil'),
        ('org', '0010_enable_avaliacoes_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('disciplina', models.CharField(blank=True, default='', max_length=120)),
                ('data_aplicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DISCURSIVA', 'Discursiva'), ('MISTA', 'Mista')], default='OBJETIVA', max_length=12)),
                ('opcoes', models.PositiveSmallIntegerField(default=5)),
                ('qtd_questoes', models.PositiveIntegerField(default=10)),
                ('tem_versoes', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas_modulo', to='educacao.avaliacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_provas_criadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_provas', to='org.municipio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_provas', to='org.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_provas', to='org.setor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_provas', to='educacao.turma')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_provas', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Avaliação (Prova)',
                'verbose_name_plural': 'Avaliações (Provas)',
                'ordering': ['-data_aplicacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacaoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='A', max_length=1)),
                ('status', models.CharField(choices=[('GERADA', 'Gerada'), ('ENTREGUE', 'Entregue'), ('CORRIGIDA', 'Corrigida')], default='GERADA', max_length=12)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('corrigido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_provas', to='educacao.aluno')),
                ('corrigido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_provas_corrigidas', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_provas', to='educacao.matricula')),
                ('nota_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_provas', to='educacao.nota')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='avaliacoes.avaliacaoprova')),
            ],
            options={
                'verbose_name': 'Aplicação da avaliação',
                'verbose_name_plural': 'Aplicações da avaliação',
                'ordering': ['avaliacao_id', 'aluno__nome'],
            },
        ),
        migrations.CreateModel(
            name='FolhaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('versao', models.CharField(default='A', max_length=1)),
                ('respostas_marcadas', models.JSONField(blank=True, default=dict)),
                ('imagem_original', models.FileField(blank=True, null=True, upload_to='avaliacoes/respostas/%Y/%m/')),
                ('confianca_omr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hash_assinado', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folha', to='avaliacoes.aplicacaoavaliacao')),
            ],
            options={
                'verbose_name': 'Folha de resposta',
                'verbose_name_plural': 'Folhas de resposta',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GabaritoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(choices=[('A', 'Versão A'), ('B', 'Versão B'), ('C', 'Versão C')], default='A', max_length=1)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('chave_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gabaritos_provas_atualizados', to=settings.AUTH_USER_MODEL)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gabaritos', to='avaliacoes.avaliacaoprova')),
            ],
            options={
                'verbose_name': 'Gabarito',
                'verbose_name_plural': 'Gabaritos',
                'ordering': ['avaliacao_id', 'versao'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DISCURSIVA', 'Discursiva')], default='OBJETIVA', max_length=12)),
                ('alternativas', models.JSONField(blank=True, default=dict)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='avaliacoes.avaliacaoprova')),
            ],
            options={
                'verbose_name': 'Questão da prova',
                'verbose_name_plural': 'Questões da prova',
                'ordering': ['numero', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='avaliacaoprova',
            index=models.Index(fields=['municipio', 'data_aplicacao'], name='avaliacoes__municip_04e36d_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoprova',
            index=models.Index(fields=['turma', 'data_aplicacao'], name='avaliacoes__turma_i_a10d03_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoprova',
            index=models.Index(fields=['tipo', 'ativo'], name='avaliacoes__tipo_59f74c_idx'),
        ),
        migrations.AddIndex(
            model_name='aplicacaoavaliacao',
            index=models.Index(fields=['avaliacao', 'status'], name='avaliacoes__avaliac_301efa_idx'),
        ),
        migrations.AddIndex(
            model_name='aplicacaoavaliacao',
            index=models.Index(fields=['aluno', 'status'], name='avaliacoes__aluno_i_d20c32_idx'),
        ),
        migrations.AddConstraint(
            model_name='aplicacaoavaliacao',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'aluno'), name='uniq_aplicacao_avaliacao_aluno'),
        ),
        migrations.AddConstraint(
            model_name='gabaritoprova',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'versao'), name='uniq_gabarito_avaliacao_versao'),
        ),
        migrations.AddConstraint(
            model_name='questaoprova',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'numero'), name='uniq_avaliacao_questao_numero'),
        ),
    ]
