# Generated by Django 5.2.11 on 2026-02-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_secretariamoduloativo'),
        ('tributos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TributoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tributo', models.CharField(choices=[('IPTU', 'IPTU'), ('ISS', 'ISS'), ('ITBI', 'ITBI'), ('TAXA', 'Taxa')], default='IPTU', max_length=10)),
                ('exercicio', models.PositiveIntegerField(default=2026)),
                ('competencia', models.CharField(blank=True, default='', help_text='YYYY-MM opcional', max_length=7)),
                ('referencia', models.CharField(blank=True, default='', max_length=40)),
                ('valor_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_vencimento', models.DateField(default=django.utils.timezone.localdate)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('banco_recebedor', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('EMITIDO', 'Emitido'), ('PAGO', 'Pago'), ('PARCELADO', 'Parcelado'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lançamento tributário',
                'verbose_name_plural': 'Lançamentos tributários',
                'ordering': ['-exercicio', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tributoscadastro',
            options={'ordering': ['nome'], 'verbose_name': 'Contribuinte', 'verbose_name_plural': 'Contribuintes'},
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='documento',
            field=models.CharField(blank=True, default='', help_text='CPF/CNPJ', max_length=20),
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='endereco',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='inscricao_municipal',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='tributoscadastro',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='tributoscadastro',
            name='nome',
            field=models.CharField(max_length=180, verbose_name='Contribuinte'),
        ),
        migrations.AddIndex(
            model_name='tributoscadastro',
            index=models.Index(fields=['documento'], name='tributos_tr_documen_6b85fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='tributoscadastro',
            constraint=models.UniqueConstraint(condition=models.Q(('inscricao_municipal', ''), _negated=True), fields=('municipio', 'inscricao_municipal'), name='uniq_tributos_inscricao_municipio'),
        ),
        migrations.AddField(
            model_name='tributolancamento',
            name='contribuinte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='tributos.tributoscadastro'),
        ),
        migrations.AddField(
            model_name='tributolancamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tributos_lancamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tributolancamento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tributos_lancamentos', to='org.municipio'),
        ),
        migrations.AddIndex(
            model_name='tributolancamento',
            index=models.Index(fields=['municipio', 'tipo_tributo', 'status'], name='tributos_tr_municip_b1ae72_idx'),
        ),
        migrations.AddIndex(
            model_name='tributolancamento',
            index=models.Index(fields=['contribuinte', 'exercicio'], name='tributos_tr_contrib_755828_idx'),
        ),
    ]
