# Generated by Django 5.2.11 on 2026-02-25 16:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('financeiro', '0003_tesextratoimportacao_tesextratoitem_and_more'),
        ('org', '0006_secretariamoduloativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('objeto', models.CharField(max_length=240)),
                ('fornecedor_nome', models.CharField(max_length=180)),
                ('fornecedor_documento', models.CharField(blank=True, default='', max_length=30)),
                ('fiscal_nome', models.CharField(blank=True, default='', max_length=160)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
                ('empenho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='financeiro.despempenho')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_admin', to='org.municipio')),
                ('processo_licitatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='compras.processolicitatorio')),
                ('requisicao_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='compras.requisicaocompra')),
            ],
            options={
                'verbose_name': 'Contrato administrativo',
                'verbose_name_plural': 'Contratos administrativos',
                'ordering': ['-vigencia_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo'), ('VALOR', 'Valor'), ('ESCOPO', 'Escopo')], max_length=12)),
                ('numero', models.CharField(max_length=40)),
                ('data_ato', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_aditivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('nova_vigencia_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contratoadministrativo')),
            ],
            options={
                'verbose_name': 'Aditivo contratual',
                'verbose_name_plural': 'Aditivos contratuais',
                'ordering': ['-data_ato', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('data_medicao', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_medido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATESTADA', 'Atestada'), ('LIQUIDADA', 'Liquidada')], default='PENDENTE', max_length=12)),
                ('atestado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atestado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_atestadas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='contratos.contratoadministrativo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('liquidacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_contrato', to='financeiro.despliquidacao')),
            ],
            options={
                'verbose_name': 'Medicao contratual',
                'verbose_name_plural': 'Medicoes contratuais',
                'ordering': ['-data_medicao', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contratoadministrativo',
            index=models.Index(fields=['municipio', 'status', 'vigencia_fim'], name='contratos_c_municip_467f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratoadministrativo',
            constraint=models.UniqueConstraint(fields=('municipio', 'numero'), name='uniq_contrato_municipio_numero'),
        ),
        migrations.AddConstraint(
            model_name='aditivocontrato',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero'), name='uniq_aditivo_contrato_numero'),
        ),
        migrations.AddConstraint(
            model_name='medicaocontrato',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero'), name='uniq_medicao_contrato_numero'),
        ),
    ]
